import { buildDataGridTableCss } from './dataGridStylesTable';
import { buildDataGridBodyCss } from './dataGridStylesBody';
import { buildDataGridScrollbarCss } from './dataGridStylesScrollbars';
import { buildDataGridPaginationCss } from './dataGridStylesPagination';

type DataGridCssTextParams = Record<string, any>;
export type DataGridCssVars = DataGridCssTextParams & {
    fixedColumnFill: string;
    selectionColumnFill: string;
};

export const buildDataGridCssText = ({
    darkMode,
    bgContent,
    dataGridBackdropFilter,
    dataTableVerticalBorderRule,
    densityParams,
    floatingScrollbarBottomOffset,
    floatingScrollbarHeight,
    floatingScrollbarInset,
    floatingScrollbarThumbBg,
    floatingScrollbarThumbBorderColor,
    floatingScrollbarThumbHoverBg,
    floatingScrollbarThumbShadow,
    gridId,
    horizontalScrollbarThumbBg,
    horizontalScrollbarThumbBorderColor,
    horizontalScrollbarThumbHoverBg,
    horizontalScrollbarThumbShadow,
    horizontalScrollbarTrackBg,
    horizontalScrollbarTrackBorderColor,
    horizontalScrollbarTrackShadow,
    paginationAccentBg,
    paginationAccentBorderColor,
    paginationActiveItemBg,
    paginationActiveItemBorderColor,
    paginationActiveItemTextColor,
    paginationChipBg,
    paginationChipBorderColor,
    paginationHoverBg,
    paginationPrimaryTextColor,
    paginationSecondaryTextColor,
    paginationShellBg,
    paginationShellBorderColor,
    paginationShellShadow,
    panelRadius,
    rowAddedBg,
    rowModBg,
    selectionAccentHex,
    selectionAccentRgb,
    tableBodyBottomPadding,
    verticalScrollbarTrackBg,
}: DataGridCssTextParams) => {
    const fixedColumnFill = `rgb(from var(--gn-bg-panel, ${bgContent}) r g b / 1)`;
    const selectionColumnFill = `rgb(from var(--gn-bg-panel-2, ${bgContent}) r g b / 1)`;
    const vars: DataGridCssVars = {
        darkMode,
        bgContent,
        dataGridBackdropFilter,
        dataTableVerticalBorderRule,
        densityParams,
        floatingScrollbarBottomOffset,
        floatingScrollbarHeight,
        floatingScrollbarInset,
        floatingScrollbarThumbBg,
        floatingScrollbarThumbBorderColor,
        floatingScrollbarThumbHoverBg,
        floatingScrollbarThumbShadow,
        gridId,
        horizontalScrollbarThumbBg,
        horizontalScrollbarThumbBorderColor,
        horizontalScrollbarThumbHoverBg,
        horizontalScrollbarThumbShadow,
        horizontalScrollbarTrackBg,
        horizontalScrollbarTrackBorderColor,
        horizontalScrollbarTrackShadow,
        paginationAccentBg,
        paginationAccentBorderColor,
        paginationActiveItemBg,
        paginationActiveItemBorderColor,
        paginationActiveItemTextColor,
        paginationChipBg,
        paginationChipBorderColor,
        paginationHoverBg,
        paginationPrimaryTextColor,
        paginationSecondaryTextColor,
        paginationShellBg,
        paginationShellBorderColor,
        paginationShellShadow,
        panelRadius,
        rowAddedBg,
        rowModBg,
        selectionAccentHex,
        selectionAccentRgb,
        tableBodyBottomPadding,
        verticalScrollbarTrackBg,
        fixedColumnFill,
        selectionColumnFill,
    };
    return [
        buildDataGridTableCss(vars),
        buildDataGridBodyCss(vars),
        buildDataGridScrollbarCss(vars),
        buildDataGridPaginationCss(vars),
    ].join('');
};
