import { useDataGridV2ColumnActions } from './dataGrid/v2Actions/useDataGridV2ColumnActions';
import { useDataGridV2CopyExport } from './dataGrid/v2Actions/useDataGridV2CopyExport';
import { useDataGridV2CellActions } from './dataGrid/v2Actions/useDataGridV2CellActions';

export type DataGridV2ActionsContext = Record<string, any>;

export const useDataGridV2Actions = (ctx: DataGridV2ActionsContext) => {
  const {
    GONAVI_ROW_KEY,
    addTab,
    allTableColumnNames,
    applyColumnSort,
    autoFitColumnWidth,
    buildClipboardCsv,
    buildClipboardJson,
    buildClipboardMarkdown,
    buildClipboardTsv,
    buildCopyDeleteSQL,
    buildCopyInsertSQL,
    buildCopyUpdateSQL,
    buildDataGridSelectBaseSql,
    buildEffectiveFilterConditions,
    buildBackendExportOptions,
    buildOrderBySQL,
    buildPaginatedSelectSQL,
    buildRpcConnectionConfig,
    buildSelectedCellClipboardPayload,
    buildTableExportTab,
    buildWhereSQL,
    cellContextMenu,
    cellEditMode,
    canExportInsertSQL,
    closeCellEditMode,
    columnMetaMap,
    columnMetaMapByLowerName,
    columnTypeMapByLowerName,
    connectionId,
    connections,
    copiedCellPatch,
    copyRowsForPaste,
    copyToClipboard,
    currentConnConfig,
    currentSelectionRef,
    dbName,
    dbType,
    ddlText,
    displayColumnNames,
    displayData,
    displayDataRef,
    displayOutputColumnNames,
    escapeLiteral,
    exportData,
    filterConditions,
    handleBatchFillToSelected,
    handleCellSetNull,
    handleSetNullForSelectedCells,
    handleCopyColumnData,
    handleCopyContextMenuFieldName,
    handleOpenContextMenuCellEditor,
    handleOpenContextMenuRowEditor,
    handlePasteCopiedColumnsToSelectedRows,
    handlePasteCopiedRowsAsNew,
    handleUndoContextMenuCellChange,
    hasChanges,
    hasExplicitSort,
    hasFilteredExportSql,
    isActive,
    isTableSurfaceActive,
    isQueryResultExport,
    mergedDisplayData,
    modal,
    navigator,
    objectType,
    pagination,
    pickDataGridOutputRows,
    pickRowsForClipboard,
    pkColumns,
    quickWhereCondition,
    quoteIdentPart,
    resetCellSelection,
    resolveContextMenuFieldName,
    resolveDataSourceType,
    resultExportAllSql,
    resultSql,
    rootRef,
    rowKeyStr,
    runExportWithProgress,
    selectedCells,
    selectedRowKeys,
    selectedRowKeysRef,
    setCellContextMenu,
    setQueryOptions,
    setSelectedRowKeys,
    sortInfo,
    splitCellKey,
    supportsCopyInsert,
    supportsSqlQueryExport,
    tableName,
    pinnedLeftColumnScope,
    toggleColumnVisibility,
    pinnedLeftColumnNames,
    setTablePinnedLeftColumns,
    translateDataGrid,
    uniqueKeyGroups,
    withSortBufferTuningSQL,
  } = ctx;

const {
  handleV2ColumnHeaderContextMenuAction, getClipboardColumnNames, handleCopyQueryResultCsv,
  handleCopyQueryResultJson, handleCopyQueryResultMarkdown, handleCopyDdl,
  handleCopySelectedCellsToClipboard, getTargets, getContextMenuTargetRows, translateCopySqlError,
} = useDataGridV2ColumnActions({
  resolveContextMenuFieldName, cellContextMenu, translateDataGrid, setCellContextMenu,
  copyToClipboard, columnMetaMap, columnMetaMapByLowerName, handleCopyColumnData, applyColumnSort,
  autoFitColumnWidth, connectionId, dbName, pinnedLeftColumnScope, pinnedLeftColumnNames,
  setTablePinnedLeftColumns, displayColumnNames, toggleColumnVisibility, setQueryOptions,
  pickRowsForClipboard, mergedDisplayData, selectedRowKeys, displayOutputColumnNames,
  GONAVI_ROW_KEY, rowKeyStr, buildClipboardCsv, buildClipboardJson, buildClipboardMarkdown, ddlText,
  navigator, currentSelectionRef, selectedCells, splitCellKey, buildSelectedCellClipboardPayload,
  isActive, isTableSurfaceActive, cellEditMode, closeCellEditMode, resetCellSelection, rootRef,
  selectedRowKeysRef, displayDataRef,
});

  const {
    buildCopySqlBatchText, handleCopyInsert, handleCopyUpdate, handleCopyDelete, handleCopyJson,
    handleCopyCsv, handleCopyRowData, buildConnConfig, resolveExportTitle, buildCurrentPageSql,
    buildAllRowsSql, buildFilteredAllSql, queryResultCurrentPageRows, exportQueryResultRows,
    handleExportSelected,
  } = useDataGridV2CopyExport({
    supportsCopyInsert, translateDataGrid, displayOutputColumnNames, buildCopyInsertSQL, dbType,
    tableName, columnTypeMapByLowerName, buildCopyUpdateSQL, pkColumns, uniqueKeyGroups,
    allTableColumnNames, buildCopyDeleteSQL, getTargets, translateCopySqlError, copyToClipboard,
    pickDataGridOutputRows, getContextMenuTargetRows, buildClipboardTsv, columnMetaMap,
    columnMetaMapByLowerName, currentConnConfig, connectionId, connections, runExportWithProgress,
    buildRpcConnectionConfig, dbName, buildBackendExportOptions, quoteIdentPart, escapeLiteral,
    pagination, buildEffectiveFilterConditions, filterConditions, quickWhereCondition,
    buildWhereSQL, buildDataGridSelectBaseSql, buildOrderBySQL, sortInfo, hasExplicitSort,
    buildPaginatedSelectSQL, withSortBufferTuningSQL, isQueryResultExport, mergedDisplayData,
    selectedRowKeys, rowKeyStr, GONAVI_ROW_KEY, exportData, resultExportAllSql, resultSql,
    hasChanges, resolveDataSourceType,
  });

  const { handleV2CellContextMenuAction, handleOpenExportDialog } = useDataGridV2CellActions({
    cellContextMenu, setCellContextMenu, handleCopyContextMenuFieldName, GONAVI_ROW_KEY,
    translateDataGrid, setSelectedRowKeys, copyRowsForPaste, handlePasteCopiedRowsAsNew,
    handleCopyColumnData, handleUndoContextMenuCellChange, handleCellSetNull,
    handleSetNullForSelectedCells, handleOpenContextMenuRowEditor, handleOpenContextMenuCellEditor,
    selectedRowKeys, handleBatchFillToSelected, copiedCellPatch,
    handlePasteCopiedColumnsToSelectedRows, copyToClipboard, buildClipboardMarkdown,
    handleCopyRowData, handleCopyInsert, handleCopyUpdate, handleCopyDelete, handleCopyJson,
    handleCopyCsv, getTargets, getClipboardColumnNames, handleExportSelected, resultExportAllSql,
    resultSql, mergedDisplayData, isQueryResultExport, modal, displayOutputColumnNames,
    canExportInsertSQL, connectionId, resolveDataSourceType, hasChanges, supportsSqlQueryExport,
    objectType, hasFilteredExportSql, pagination, addTab, buildTableExportTab, dbName, tableName,
    displayData, buildBackendExportOptions, queryResultCurrentPageRows, exportQueryResultRows,
    buildConnConfig, buildCurrentPageSql, buildFilteredAllSql, buildAllRowsSql, resolveExportTitle,
  });

  return {
    handleV2ColumnHeaderContextMenuAction,
    buildConnConfig,
    buildCopySqlBatchText,
    getTargets,
    handleCopyCsv,
    handleCopyDdl,
    handleCopyDelete,
    handleCopyInsert,
    handleCopyJson,
    handleCopyQueryResultCsv,
    handleCopyQueryResultJson,
    handleCopyQueryResultMarkdown,
    handleCopyRowData,
    handleCopySelectedCellsToClipboard,
    handleCopyUpdate,
    handleExportSelected,
    handleV2CellContextMenuAction,
    handleOpenExportDialog,
  };
};
