// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connection} from '../models';
import {sqlaudit} from '../models';
import {app} from '../models';
import {context} from '../models';
import {sync} from '../models';
import {syncjob} from '../models';
import {requesttrace} from '../models';
import {jvm} from '../models';
import {redis} from '../models';
import {resultdiff} from '../models';

export function ApplyChanges(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:connection.ChangeSet):Promise<connection.QueryResult>;

export function ApplyDataRootDirectory(arg1:string,arg2:boolean):Promise<connection.QueryResult>;

export function ApplyLogDirectory(arg1:string):Promise<connection.QueryResult>;

export function ApplySavedQueryDirectory(arg1:string):Promise<connection.QueryResult>;

export function AuthorizeMCPConnectionSQL(arg1:connection.ConnectionConfig,arg2:string):Promise<void>;

export function BootstrapConnectionSidebarLayout(arg1:connection.ConnectionSidebarLayoutInput):Promise<connection.ConnectionSidebarLayout>;

export function BuildDatabaseDiagnosticPackage():Promise<connection.QueryResult>;

export function BuildReproductionBundle(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function BuildSQLAuditExport(arg1:sqlaudit.Filter,arg2:string):Promise<connection.QueryResult>;

export function CancelApplicationQuit():Promise<connection.QueryResult>;

export function CancelConnectionTest(arg1:string):Promise<connection.QueryResult>;

export function CancelImportJob(arg1:string):Promise<connection.QueryResult>;

export function CancelQuery(arg1:string):Promise<connection.QueryResult>;

export function CancelSQLFileExecution(arg1:string):Promise<connection.QueryResult>;

export function CancelSavedConnectionsHealthRun(arg1:string):Promise<connection.ConnectionHealthRun>;

export function CheckDriverNetworkStatus():Promise<connection.QueryResult>;

export function CheckForUpdates():Promise<connection.QueryResult>;

export function CheckForUpdatesSilently():Promise<connection.QueryResult>;

export function ClearSQLAuditEvents(arg1:number):Promise<connection.QueryResult>;

export function ClearSlowQueries(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function ClearTables(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function CloudBackupGetConfig():Promise<app.CloudBackupConfig>;

export function CloudBackupGetStatus():Promise<app.CloudBackupStatus>;

export function CloudBackupListRestorePoints():Promise<Array<app.CloudBackupRestorePoint>>;

export function CloudBackupPreviewRestore():Promise<app.CloudBackupRestorePreview>;

export function CloudBackupRestore(arg1:app.CloudBackupRestoreRequest):Promise<app.CloudBackupRestorePreview>;

export function CloudBackupSyncNow():Promise<app.CloudBackupStatus>;

export function ConfigureDriverRuntimeDirectory(arg1:string):Promise<connection.QueryResult>;

export function ConfigureGlobalProxy(arg1:boolean,arg2:connection.ProxyConfig):Promise<connection.QueryResult>;

export function CopyTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function CreateDatabase(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function CreateSQLDirectory(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function CreateSQLFile(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function CreateSchema(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBCommitTransaction(arg1:string):Promise<connection.QueryResult>;

export function DBCommitTransactionWithTrigger(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function DBConnect(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function DBGetAllColumns(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function DBGetAllColumnsContext(arg1:context.Context,arg2:connection.ConnectionConfig,arg3:string):Promise<connection.QueryResult>;

export function DBGetColumns(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBGetColumnsContext(arg1:context.Context,arg2:connection.ConnectionConfig,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBGetDatabaseForeignKeys(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function DBGetDatabases(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function DBGetDatabasesContext(arg1:context.Context,arg2:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function DBGetForeignKeys(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBGetForeignKeysContext(arg1:context.Context,arg2:connection.ConnectionConfig,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBGetIndexes(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBGetIndexesContext(arg1:context.Context,arg2:connection.ConnectionConfig,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBGetObjects(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function DBGetObjectsContext(arg1:context.Context,arg2:connection.ConnectionConfig,arg3:string):Promise<connection.QueryResult>;

export function DBGetTables(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function DBGetTablesContext(arg1:context.Context,arg2:connection.ConnectionConfig,arg3:string):Promise<connection.QueryResult>;

export function DBGetTriggers(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBGetTriggersContext(arg1:context.Context,arg2:connection.ConnectionConfig,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBGetViews(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function DBGetViewsContext(arg1:context.Context,arg2:connection.ConnectionConfig,arg3:string):Promise<connection.QueryResult>;

export function DBQuery(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBQueryAI(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBQueryAudited(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBQueryIsolated(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBQueryMulti(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBQueryMultiInTransaction(arg1:string,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBQueryMultiTransactional(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBQueryWithCancel(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBRefreshTableStats(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function DBReleaseConnection(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function DBRollbackTransaction(arg1:string):Promise<connection.QueryResult>;

export function DBRollbackTransactionWithTrigger(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function DBShowCreateTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DBShowCreateTableContext(arg1:context.Context,arg2:connection.ConnectionConfig,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DBTableExists(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DataImportCapability(arg1:connection.ConnectionConfig):Promise<app.DataImportCapability>;

export function DataSourceCapability(arg1:connection.ConnectionConfig):Promise<app.DataSourceCapability>;

export function DataSync(arg1:sync.SyncConfig):Promise<sync.SyncResult>;

export function DataSyncAnalyze(arg1:sync.SyncConfig):Promise<connection.QueryResult>;

export function DataSyncCDCAdapterList():Promise<connection.QueryResult>;

export function DataSyncCDCProbe(arg1:string,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DataSyncCapability(arg1:connection.ConnectionConfig,arg2:connection.ConnectionConfig):Promise<sync.MigrationCapability>;

export function DataSyncCapabilityResolve(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<connection.QueryResult>;

export function DataSyncCheckpointGet(arg1:string):Promise<connection.QueryResult>;

export function DataSyncCheckpointReset(arg1:string,arg2:number):Promise<connection.QueryResult>;

export function DataSyncDatabaseList(arg1:string):Promise<connection.QueryResult>;

export function DataSyncErrorRowDiscard(arg1:string):Promise<connection.QueryResult>;

export function DataSyncErrorRowGet(arg1:string):Promise<connection.QueryResult>;

export function DataSyncErrorRowList(arg1:string,arg2:string,arg3:number):Promise<connection.QueryResult>;

export function DataSyncErrorRowRetry(arg1:string,arg2:number,arg3:string):Promise<connection.QueryResult>;

export function DataSyncFieldList(arg1:string,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DataSyncJobApprovalBegin(arg1:syncjob.JobDefinition):Promise<connection.QueryResult>;

export function DataSyncJobApprove(arg1:syncjob.JobDefinition,arg2:string):Promise<connection.QueryResult>;

export function DataSyncJobDelete(arg1:string):Promise<connection.QueryResult>;

export function DataSyncJobGet(arg1:string):Promise<connection.QueryResult>;

export function DataSyncJobList():Promise<connection.QueryResult>;

export function DataSyncJobPreflight(arg1:syncjob.JobDefinition):Promise<connection.QueryResult>;

export function DataSyncJobSave(arg1:syncjob.JobDefinition,arg2:string):Promise<connection.QueryResult>;

export function DataSyncObjectList(arg1:string,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DataSyncPreview(arg1:sync.SyncConfig,arg2:string,arg3:number):Promise<connection.QueryResult>;

export function DataSyncRunCancel(arg1:string):Promise<connection.QueryResult>;

export function DataSyncRunClearTerminal(arg1:string):Promise<connection.QueryResult>;

export function DataSyncRunDelete(arg1:string):Promise<connection.QueryResult>;

export function DataSyncRunEventList(arg1:string,arg2:number,arg3:number):Promise<connection.QueryResult>;

export function DataSyncRunGet(arg1:string):Promise<connection.QueryResult>;

export function DataSyncRunList(arg1:string,arg2:number):Promise<connection.QueryResult>;

export function DataSyncRunPage(arg1:string,arg2:number,arg3:string,arg4:number):Promise<connection.QueryResult>;

export function DataSyncRunResume(arg1:string):Promise<connection.QueryResult>;

export function DataSyncRunRetry(arg1:string):Promise<connection.QueryResult>;

export function DataSyncRunStart(arg1:string,arg2:number,arg3:string):Promise<connection.QueryResult>;

export function DataSyncSchedulePreview(arg1:syncjob.JobDefinition,arg2:number):Promise<connection.QueryResult>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteConnectionGroup(arg1:connection.DeleteConnectionGroupInput):Promise<void>;

export function DeleteConnections(arg1:Array<string>):Promise<void>;

export function DeleteImportJob(arg1:string):Promise<connection.QueryResult>;

export function DeleteQuery(arg1:string):Promise<void>;

export function DeleteSQLDirectory(arg1:string):Promise<connection.QueryResult>;

export function DeleteSQLFile(arg1:string):Promise<connection.QueryResult>;

export function DeleteSavedQueryGroup(arg1:string):Promise<void>;

export function DiagnoseQuery(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DismissSecurityUpdateReminder():Promise<app.SecurityUpdateStatus>;

export function DownloadDriverPackage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DownloadUpdate():Promise<connection.QueryResult>;

export function DropDatabase(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function DropFunction(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function DropSchema(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DropTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DropView(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function DuplicateConnection(arg1:string):Promise<connection.SavedConnectionView>;

export function ExecuteElasticsearchConsole(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<app.ElasticsearchConsoleExecutionResult>;

export function ExecuteSQLFile(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function ExportConnectionsPackage(arg1:app.ConnectionExportOptions):Promise<connection.QueryResult>;

export function ExportConnectionsPayload(arg1:app.ConnectionExportOptions):Promise<connection.QueryResult>;

export function ExportData(arg1:Array<Record<string, any>>,arg2:Array<string>,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function ExportDataWithOptions(arg1:Array<Record<string, any>>,arg2:Array<string>,arg3:string,arg4:app.ExportFileOptions):Promise<connection.QueryResult>;

export function ExportDatabaseDiagnosticPackage():Promise<connection.QueryResult>;

export function ExportDatabaseSQL(arg1:connection.ConnectionConfig,arg2:string,arg3:boolean):Promise<connection.QueryResult>;

export function ExportDatabaseSQLWithOptions(arg1:connection.ConnectionConfig,arg2:string,arg3:boolean,arg4:app.ExportFileOptions):Promise<connection.QueryResult>;

export function ExportDatabasesSQLWithOptions(arg1:connection.ConnectionConfig,arg2:Array<string>,arg3:boolean,arg4:app.ExportFileOptions):Promise<connection.QueryResult>;

export function ExportImportErrorRows(arg1:string):Promise<connection.QueryResult>;

export function ExportQuery(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:string):Promise<connection.QueryResult>;

export function ExportQueryWithOptions(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:app.ExportFileOptions):Promise<connection.QueryResult>;

export function ExportReproductionBundle(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function ExportSQLAuditFile(arg1:sqlaudit.Filter,arg2:string):Promise<connection.QueryResult>;

export function ExportSQLFile(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function ExportSchemaSQL(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:boolean):Promise<connection.QueryResult>;

export function ExportSchemaSQLWithOptions(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:boolean,arg5:app.ExportFileOptions):Promise<connection.QueryResult>;

export function ExportTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function ExportTableWithOptions(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:app.ExportFileOptions):Promise<connection.QueryResult>;

export function ExportTablesDataSQL(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function ExportTablesSQL(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>,arg4:boolean):Promise<connection.QueryResult>;

export function ExportTablesSQLWithOptions(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>,arg4:boolean,arg5:boolean,arg6:app.ExportFileOptions):Promise<connection.QueryResult>;

export function ForceQuitApplication():Promise<connection.QueryResult>;

export function GenerateQueryID():Promise<string>;

export function GetAppInfo():Promise<connection.QueryResult>;

export function GetDataRootDirectoryInfo():Promise<connection.QueryResult>;

export function GetDatabaseDiagnosticPackagePreview():Promise<connection.QueryResult>;

export function GetDownloadSourceConfig():Promise<app.DownloadSourceConfig>;

export function GetDriverStatusList(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function GetDriverVersionList(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function GetDriverVersionPackageSize(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function GetEditableSavedConnection(arg1:string):Promise<connection.SavedConnectionView>;

export function GetGlobalProxyConfig():Promise<connection.QueryResult>;

export function GetImportJob(arg1:string):Promise<connection.QueryResult>;

export function GetRequestDiagnostic(arg1:string):Promise<connection.QueryResult>;

export function GetRequestDiagnostics(arg1:requesttrace.Filter):Promise<connection.QueryResult>;

export function GetSQLAuditEvents(arg1:sqlaudit.Filter):Promise<connection.QueryResult>;

export function GetSQLAuditHealth():Promise<connection.QueryResult>;

export function GetSQLAuditSettings():Promise<connection.QueryResult>;

export function GetSavedConnections():Promise<Array<connection.SavedConnectionView>>;

export function GetSavedConnectionsHealthRun(arg1:string):Promise<connection.ConnectionHealthRun>;

export function GetSavedQueries():Promise<Array<connection.SavedQuery>>;

export function GetSavedQueryGroups():Promise<Array<connection.SavedQueryGroup>>;

export function GetSecurityUpdateStatus():Promise<app.SecurityUpdateStatus>;

export function GetSlowQueries(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:number):Promise<connection.QueryResult>;

export function GetUnboundSavedQueries():Promise<Array<connection.SavedQuery>>;

export function GetUpdateChannel():Promise<connection.QueryResult>;

export function GetUpdateDownloadTask():Promise<connection.QueryResult>;

export function ImportConfigFile():Promise<connection.QueryResult>;

export function ImportConnectionsPayload(arg1:string,arg2:string):Promise<app.ConnectionPackageImportResult>;

export function ImportData(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function ImportDataWithProgress(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function ImportDataWithProgressOptions(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:app.ImportFileOptions):Promise<connection.QueryResult>;

export function ImportDatabaseSQL(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<connection.QueryResult>;

export function ImportDatabaseSQLWithOptions(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<connection.QueryResult>;

export function ImportLegacyConnections(arg1:Array<connection.SavedConnectionInput>):Promise<Array<connection.SavedConnectionView>>;

export function ImportLegacyGlobalProxy(arg1:connection.SaveGlobalProxyInput):Promise<connection.GlobalProxyView>;

export function ImportSavedQueries(arg1:connection.SavedQueryImportPayload):Promise<Array<connection.SavedQuery>>;

export function InspectElasticsearchConsole(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<app.ElasticsearchConsoleInspection>;

export function InspectSavedConnectionHealth(arg1:string):Promise<connection.ConnectionHealthReport>;

export function InspectSavedConnectionsHealth(arg1:Array<string>):Promise<Array<connection.ConnectionHealthReport>>;

export function InstallLocalDriverPackage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function InstallUpdateAndRestart(arg1:boolean):Promise<connection.QueryResult>;

export function JVMApplyChange(arg1:connection.ConnectionConfig,arg2:jvm.ChangeRequest):Promise<connection.QueryResult>;

export function JVMCancelDiagnosticCommand(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function JVMExecuteDiagnosticCommand(arg1:connection.ConnectionConfig,arg2:string,arg3:jvm.DiagnosticCommandRequest):Promise<connection.QueryResult>;

export function JVMGetMonitoringHistory(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function JVMGetValue(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function JVMListAuditRecords(arg1:string,arg2:number):Promise<connection.QueryResult>;

export function JVMListDiagnosticAuditRecords(arg1:string,arg2:number):Promise<connection.QueryResult>;

export function JVMListResources(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function JVMPreviewChange(arg1:connection.ConnectionConfig,arg2:jvm.ChangeRequest):Promise<connection.QueryResult>;

export function JVMProbeCapabilities(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function JVMProbeDiagnosticCapabilities(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function JVMStartDiagnosticSession(arg1:connection.ConnectionConfig,arg2:jvm.DiagnosticSessionRequest):Promise<connection.QueryResult>;

export function JVMStartMonitoring(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function JVMStopMonitoring(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function ListDatabaseCharsets(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function ListDatabaseCollations(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function ListDriverDownloadTasks():Promise<connection.QueryResult>;

export function ListImportJobs():Promise<connection.QueryResult>;

export function ListInstalledFontFamilies():Promise<connection.QueryResult>;

export function ListReproductionBundleSources():Promise<connection.QueryResult>;

export function ListSQLDirectory(arg1:string):Promise<connection.QueryResult>;

export function LoadConnectionSidebarLayout():Promise<connection.ConnectionSidebarLayout>;

export function LogWindowDiagnostic(arg1:string,arg2:string):Promise<void>;

export function MongoDiscoverMembers(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function MoveSavedQueryGroup(arg1:string,arg2:string):Promise<void>;

export function MoveSavedQueryToGroup(arg1:string,arg2:string):Promise<void>;

export function MySQLConnect(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function MySQLGetDatabases(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function MySQLGetTables(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function MySQLQuery(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function MySQLShowCreateTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function NacosConnect(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function NacosCreateNamespace(arg1:connection.ConnectionConfig,arg2:app.NacosCreateNamespacePayload):Promise<connection.QueryResult>;

export function NacosCreateService(arg1:connection.ConnectionConfig,arg2:app.NacosServicePayload):Promise<connection.QueryResult>;

export function NacosDeleteConfig(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function NacosDeleteNamespace(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function NacosDeleteService(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function NacosDeregisterInstance(arg1:connection.ConnectionConfig,arg2:app.NacosInstancePayload):Promise<connection.QueryResult>;

export function NacosExportConfigs(arg1:connection.ConnectionConfig,arg2:app.NacosExportConfigsOptions):Promise<connection.QueryResult>;

export function NacosGetBetaConfig(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function NacosGetConfig(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function NacosGetConfigHistory(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string,arg5:string):Promise<connection.QueryResult>;

export function NacosGetInstance(arg1:connection.ConnectionConfig,arg2:app.NacosInstancePayload):Promise<connection.QueryResult>;

export function NacosGetService(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function NacosImportConfigs(arg1:connection.ConnectionConfig,arg2:app.NacosImportConfigsOptions):Promise<connection.QueryResult>;

export function NacosListConfigGroups(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function NacosListConfigHistory(arg1:connection.ConnectionConfig,arg2:app.NacosHistoryQuery):Promise<connection.QueryResult>;

export function NacosListInstances(arg1:connection.ConnectionConfig,arg2:app.NacosInstanceQuery):Promise<connection.QueryResult>;

export function NacosListNamespaces(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function NacosListServices(arg1:connection.ConnectionConfig,arg2:app.NacosServiceQuery):Promise<connection.QueryResult>;

export function NacosPreviewImportConfigs(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function NacosPublishConfig(arg1:connection.ConnectionConfig,arg2:app.NacosPublishConfigPayload):Promise<connection.QueryResult>;

export function NacosRegisterInstance(arg1:connection.ConnectionConfig,arg2:app.NacosInstancePayload):Promise<connection.QueryResult>;

export function NacosSearchConfigs(arg1:connection.ConnectionConfig,arg2:app.NacosConfigQuery):Promise<connection.QueryResult>;

export function NacosStartConfigListen(arg1:connection.ConnectionConfig,arg2:app.NacosStartConfigListenPayload):Promise<connection.QueryResult>;

export function NacosStopBetaConfig(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function NacosStopConfigListen(arg1:string):Promise<connection.QueryResult>;

export function NacosTestConnection(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function NacosTestConnectionWithProgress(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function NacosUpdateConfigListenMD5(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function NacosUpdateInstance(arg1:connection.ConnectionConfig,arg2:app.NacosInstancePayload):Promise<connection.QueryResult>;

export function NacosUpdateInstanceHealth(arg1:connection.ConnectionConfig,arg2:app.NacosInstancePayload):Promise<connection.QueryResult>;

export function NacosUpdateNamespace(arg1:connection.ConnectionConfig,arg2:app.NacosUpdateNamespacePayload):Promise<connection.QueryResult>;

export function NacosUpdateService(arg1:connection.ConnectionConfig,arg2:app.NacosServicePayload):Promise<connection.QueryResult>;

export function OpenDataRootDirectory():Promise<connection.QueryResult>;

export function OpenDownloadedUpdateDirectory():Promise<connection.QueryResult>;

export function OpenDriverDownloadDirectory(arg1:string):Promise<connection.QueryResult>;

export function OpenLogDirectory():Promise<connection.QueryResult>;

export function OpenSQLFile():Promise<connection.QueryResult>;

export function OpenSavedQueryDirectory():Promise<connection.QueryResult>;

export function PreflightDatabaseSQLImport(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function PreviewChanges(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:connection.ChangeSet):Promise<connection.QueryResult>;

export function PreviewImportFile(arg1:string):Promise<connection.QueryResult>;

export function PreviewImportFileWithOptions(arg1:string,arg2:app.ImportFileOptions):Promise<connection.QueryResult>;

export function PreviewReproductionBundle(arg1:string):Promise<connection.QueryResult>;

export function ReadAppLogTail(arg1:number,arg2:string):Promise<connection.QueryResult>;

export function ReadSQLFile(arg1:string):Promise<connection.QueryResult>;

export function RebindSavedQuery(arg1:string,arg2:string):Promise<connection.SavedQuery>;

export function RedisConnect(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisDeleteHashField(arg1:connection.ConnectionConfig,arg2:string,arg3:any):Promise<connection.QueryResult>;

export function RedisDeleteKeys(arg1:connection.ConnectionConfig,arg2:Array<string>):Promise<connection.QueryResult>;

export function RedisExecuteCommand(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function RedisExportKeys(arg1:connection.ConnectionConfig,arg2:app.RedisExportKeysOptions):Promise<connection.QueryResult>;

export function RedisFlushDB(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisGetDatabases(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisGetListValue(arg1:connection.ConnectionConfig,arg2:string,arg3:boolean):Promise<connection.QueryResult>;

export function RedisGetServerInfo(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisGetValue(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function RedisImportKeys(arg1:connection.ConnectionConfig,arg2:app.RedisImportKeysOptions):Promise<connection.QueryResult>;

export function RedisKeyExists(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function RedisListPush(arg1:connection.ConnectionConfig,arg2:string,arg3:app.RedisListPushOptions):Promise<connection.QueryResult>;

export function RedisListRemove(arg1:connection.ConnectionConfig,arg2:string,arg3:number,arg4:string):Promise<connection.QueryResult>;

export function RedisListSet(arg1:connection.ConnectionConfig,arg2:string,arg3:number,arg4:string):Promise<connection.QueryResult>;

export function RedisPreviewImportKeys(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisRenameKey(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function RedisScanKeys(arg1:connection.ConnectionConfig,arg2:string,arg3:any,arg4:number):Promise<connection.QueryResult>;

export function RedisSelectDB(arg1:connection.ConnectionConfig,arg2:number):Promise<connection.QueryResult>;

export function RedisSetAdd(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function RedisSetHashField(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function RedisSetRemove(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function RedisSetString(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:number):Promise<connection.QueryResult>;

export function RedisSetTTL(arg1:connection.ConnectionConfig,arg2:string,arg3:number):Promise<connection.QueryResult>;

export function RedisStreamAdd(arg1:connection.ConnectionConfig,arg2:string,arg3:Record<string, string>,arg4:string):Promise<connection.QueryResult>;

export function RedisStreamDelete(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function RedisTestConnection(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function RedisZSetAdd(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<redis.ZSetMember>):Promise<connection.QueryResult>;

export function RedisZSetRemove(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function RefreshWebViewBounds():Promise<connection.QueryResult>;

export function RemoveDriverPackage(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function RenameDatabase(arg1:connection.ConnectionConfig,arg2:string,arg3:string):Promise<connection.QueryResult>;

export function RenameSQLDirectory(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function RenameSQLFile(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function RenameSavedQuery(arg1:string,arg2:string):Promise<connection.SavedQuery>;

export function RenameSchema(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function RenameTable(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function RenameView(arg1:connection.ConnectionConfig,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function ReplayReproductionBundle(arg1:string):Promise<connection.QueryResult>;

export function ResetWebViewZoom():Promise<connection.QueryResult>;

export function ResolveDriverDownloadDirectory(arg1:string):Promise<connection.QueryResult>;

export function ResolveDriverPackageDownloadURL(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function ResolveDriverRepositoryURL(arg1:string):Promise<connection.QueryResult>;

export function RestartSecurityUpdate(arg1:app.RestartSecurityUpdateRequest):Promise<app.SecurityUpdateStatus>;

export function ResultDiffClose(arg1:string):Promise<connection.QueryResult>;

export function ResultDiffCompute(arg1:string):Promise<connection.QueryResult>;

export function ResultDiffPage(arg1:resultdiff.PageRequest):Promise<connection.QueryResult>;

export function ResultDiffStart(arg1:app.ResultDiffStartRequest):Promise<connection.QueryResult>;

export function ResultDiffUploadChunk(arg1:resultdiff.UploadChunkRequest):Promise<connection.QueryResult>;

export function ResumeImportJob(arg1:string):Promise<connection.QueryResult>;

export function RetryImportJobFailedRows(arg1:string):Promise<connection.QueryResult>;

export function RetrySecurityUpdateCurrentRound(arg1:app.RetrySecurityUpdateRequest):Promise<app.SecurityUpdateStatus>;

export function RevealSavedConnectionPrimaryPassword(arg1:string):Promise<string>;

export function RevealSavedQueryInFolder(arg1:string):Promise<connection.QueryResult>;

export function SaveCloudBackupConfig(arg1:app.CloudBackupConfigInput):Promise<app.CloudBackupConfig>;

export function SaveConnection(arg1:connection.SavedConnectionInput):Promise<connection.SavedConnectionView>;

export function SaveConnectionSidebarLayout(arg1:connection.SaveConnectionSidebarLayoutInput):Promise<connection.SaveConnectionSidebarLayoutResult>;

export function SaveDownloadSourceConfig(arg1:string):Promise<app.DownloadSourceConfig>;

export function SaveGlobalProxy(arg1:connection.SaveGlobalProxyInput):Promise<connection.GlobalProxyView>;

export function SaveQuery(arg1:connection.SavedQuery):Promise<connection.SavedQuery>;

export function SaveSavedQueryGroup(arg1:connection.SavedQueryGroup):Promise<connection.SavedQueryGroup>;

export function SelectCertificateFile(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function SelectDataRootDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectDatabaseFile(arg1:string,arg2:string):Promise<connection.QueryResult>;

export function SelectDriverDownloadDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectDriverPackageDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectDriverPackageFile(arg1:string):Promise<connection.QueryResult>;

export function SelectLogDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectSQLDirectory(arg1:string):Promise<connection.QueryResult>;

export function SelectSQLFileForExecution():Promise<connection.QueryResult>;

export function SelectSSHKeyFile(arg1:string):Promise<connection.QueryResult>;

export function SelectSSHKnownHostsFile(arg1:string):Promise<connection.QueryResult>;

export function SelectSavedQueryDirectory(arg1:string):Promise<connection.QueryResult>;

export function SetApplicationBrandIcon(arg1:string):Promise<connection.QueryResult>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetMacNativeWindowControls(arg1:boolean):Promise<void>;

export function SetUpdateChannel(arg1:string):Promise<connection.QueryResult>;

export function SetWindowTranslucency(arg1:number,arg2:number):Promise<void>;

export function Shutdown():Promise<void>;

export function StartDriverPackageDownload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<connection.QueryResult>;

export function StartSavedConnectionsHealthRun(arg1:Array<string>):Promise<connection.ConnectionHealthRun>;

export function StartSecurityUpdate(arg1:app.StartSecurityUpdateRequest):Promise<app.SecurityUpdateStatus>;

export function StartUpdateDownload():Promise<connection.QueryResult>;

export function TestConnection(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function TestConnectionWithProgress(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function TestGlobalProxyConnection(arg1:connection.TestGlobalProxyInput):Promise<connection.QueryResult>;

export function TestJVMConnection(arg1:connection.ConnectionConfig):Promise<connection.QueryResult>;

export function TruncateTables(arg1:connection.ConnectionConfig,arg2:string,arg3:Array<string>):Promise<connection.QueryResult>;

export function TrustSSHHostKey(arg1:string,arg2:number,arg3:string):Promise<connection.QueryResult>;

export function TrustSSHHostKeyForConnection(arg1:connection.ConnectionConfig,arg2:string):Promise<connection.QueryResult>;

export function UpdateConnectionVisibility(arg1:connection.ConnectionVisibilityInput):Promise<connection.SavedConnectionView>;

export function UpdateSQLAuditSettings(arg1:sqlaudit.Settings):Promise<connection.QueryResult>;

export function VerifySQLAuditIntegrity():Promise<connection.QueryResult>;

export function WriteSQLFile(arg1:string,arg2:string):Promise<connection.QueryResult>;
