// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {aiservice} from '../models';
import {ai} from '../models';
import {runharness} from '../models';

export function AIApplyAgentDataDirectory(arg1:string,arg2:boolean):Promise<aiservice.AgentDataDirectoryInfo>;

export function AICallMCPTool(arg1:string,arg2:string):Promise<ai.MCPToolCallResult>;

export function AICheckSQL(arg1:string):Promise<ai.SafetyResult>;

export function AIClearAgentData():Promise<aiservice.AgentDataMaintenanceResult>;

export function AIControlAgentRun(arg1:runharness.RunControlRequest):Promise<runharness.RunSnapshot>;

export function AIDeleteMCPServer(arg1:string):Promise<void>;

export function AIDeleteProvider(arg1:string):Promise<void>;

export function AIDeleteSkill(arg1:string):Promise<void>;

export function AIGetActiveProvider():Promise<string>;

export function AIGetAgentDataDirectoryInfo():Promise<aiservice.AgentDataDirectoryInfo>;

export function AIGetAgentLedgerStatus():Promise<runharness.LedgerStatus>;

export function AIGetBuiltinPrompts():Promise<Record<string, string>>;

export function AIGetCLICapabilities():Promise<Array<ai.CLICapabilityView>>;

export function AIGetCLIModelCatalog(arg1:ai.ProviderConfig):Promise<Record<string, any>>;

export function AIGetContextLevel():Promise<string>;

export function AIGetEditableProvider(arg1:string):Promise<ai.ProviderConfig>;

export function AIGetMCPClientInstallStatuses():Promise<Array<ai.MCPClientInstallStatus>>;

export function AIGetMCPHTTPServerStatus():Promise<ai.MCPHTTPServerStatus>;

export function AIGetMCPServers():Promise<Array<ai.MCPServerConfig>>;

export function AIGetProviders():Promise<Array<ai.ProviderConfig>>;

export function AIGetResultMaskingSettings():Promise<ai.ResultMaskingSettings>;

export function AIGetRunPolicy():Promise<runharness.RunPolicySnapshot>;

export function AIGetSafetyLevel():Promise<string>;

export function AIGetSkills():Promise<Array<ai.SkillConfig>>;

export function AIGetUserPromptSettings():Promise<ai.UserPromptSettings>;

export function AIInstallClaudeCodeMCP():Promise<ai.MCPClientInstallResult>;

export function AIInstallCodexMCP():Promise<ai.MCPClientInstallResult>;

export function AIInstallDeepSeekHarnessMCP():Promise<ai.MCPClientInstallResult>;

export function AIInstallGrokBuildMCP():Promise<ai.MCPClientInstallResult>;

export function AIInstallKimiMCP():Promise<ai.MCPClientInstallResult>;

export function AIInstallOpenCodeMCP():Promise<ai.MCPClientInstallResult>;

export function AIInstallZCodeMCP():Promise<ai.MCPClientInstallResult>;

export function AIListAgentSessions(arg1:runharness.SessionListRequest):Promise<runharness.SessionListResult>;

export function AIListCLIModels(arg1:string):Promise<Array<string>>;

export function AIListMCPTools():Promise<Array<ai.MCPToolDescriptor>>;

export function AIListModels():Promise<Record<string, any>>;

export function AIListProviderModels(arg1:ai.ProviderConfig):Promise<Record<string, any>>;

export function AIMutateAgentSession(arg1:runharness.SessionMutationRequest):Promise<runharness.SessionProjection>;

export function AIOpenAgentDataDirectory():Promise<void>;

export function AIOptimizeAgentData():Promise<aiservice.AgentDataMaintenanceResult>;

export function AIReadAgentRun(arg1:runharness.RunReadRequest):Promise<runharness.RunReadResult>;

export function AIReadAgentSession(arg1:runharness.SessionReadRequest):Promise<runharness.SessionProjection>;

export function AISaveMCPServer(arg1:ai.MCPServerConfig):Promise<void>;

export function AISaveProvider(arg1:ai.ProviderConfig):Promise<void>;

export function AISaveResultMaskingSettings(arg1:ai.ResultMaskingSettings):Promise<void>;

export function AISaveRunPolicy(arg1:runharness.RunPolicyMutationRequest):Promise<runharness.RunPolicySnapshot>;

export function AISaveSkill(arg1:ai.SkillConfig):Promise<void>;

export function AISaveUserPromptSettings(arg1:ai.UserPromptSettings):Promise<void>;

export function AISelectAgentDataDirectory(arg1:string):Promise<string>;

export function AISetActiveProvider(arg1:string):Promise<void>;

export function AISetContextLevel(arg1:string):Promise<void>;

export function AISetLanguage(arg1:string):Promise<void>;

export function AISetSafetyLevel(arg1:string):Promise<void>;

export function AIStartMCPHTTPServer(arg1:ai.MCPHTTPServerOptions):Promise<ai.MCPHTTPServerStatus>;

export function AIStopMCPHTTPServer():Promise<ai.MCPHTTPServerStatus>;

export function AISubmitAgentInput(arg1:runharness.AgentInputRequest):Promise<runharness.AgentInputReceipt>;

export function AITestMCPServer(arg1:ai.MCPServerConfig):Promise<Record<string, any>>;

export function AITestProvider(arg1:ai.ProviderConfig):Promise<Record<string, any>>;

export function AIUpdateWorkspaceSnapshot(arg1:runharness.WorkspaceSnapshot):Promise<runharness.SnapshotAck>;

export function Shutdown():Promise<void>;
