// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AICallMCPTool(arg1, arg2) {
  return window['go']['aiservice']['Service']['AICallMCPTool'](arg1, arg2);
}

export function AICheckSQL(arg1) {
  return window['go']['aiservice']['Service']['AICheckSQL'](arg1);
}

export function AIControlAgentRun(arg1) {
  return window['go']['aiservice']['Service']['AIControlAgentRun'](arg1);
}

export function AIDeleteMCPServer(arg1) {
  return window['go']['aiservice']['Service']['AIDeleteMCPServer'](arg1);
}

export function AIDeleteProvider(arg1) {
  return window['go']['aiservice']['Service']['AIDeleteProvider'](arg1);
}

export function AIDeleteSkill(arg1) {
  return window['go']['aiservice']['Service']['AIDeleteSkill'](arg1);
}

export function AIGetActiveProvider() {
  return window['go']['aiservice']['Service']['AIGetActiveProvider']();
}

export function AIGetAgentLedgerStatus() {
  return window['go']['aiservice']['Service']['AIGetAgentLedgerStatus']();
}

export function AIGetBuiltinPrompts() {
  return window['go']['aiservice']['Service']['AIGetBuiltinPrompts']();
}

export function AIGetCLICapabilities() {
  return window['go']['aiservice']['Service']['AIGetCLICapabilities']();
}

export function AIGetCLIModelCatalog(arg1) {
  return window['go']['aiservice']['Service']['AIGetCLIModelCatalog'](arg1);
}

export function AIGetContextLevel() {
  return window['go']['aiservice']['Service']['AIGetContextLevel']();
}

export function AIGetEditableProvider(arg1) {
  return window['go']['aiservice']['Service']['AIGetEditableProvider'](arg1);
}

export function AIGetMCPClientInstallStatuses() {
  return window['go']['aiservice']['Service']['AIGetMCPClientInstallStatuses']();
}

export function AIGetMCPHTTPServerStatus() {
  return window['go']['aiservice']['Service']['AIGetMCPHTTPServerStatus']();
}

export function AIGetMCPServers() {
  return window['go']['aiservice']['Service']['AIGetMCPServers']();
}

export function AIGetProviders() {
  return window['go']['aiservice']['Service']['AIGetProviders']();
}

export function AIGetRunPolicy() {
  return window['go']['aiservice']['Service']['AIGetRunPolicy']();
}

export function AIGetSafetyLevel() {
  return window['go']['aiservice']['Service']['AIGetSafetyLevel']();
}

export function AIGetSkills() {
  return window['go']['aiservice']['Service']['AIGetSkills']();
}

export function AIGetUserPromptSettings() {
  return window['go']['aiservice']['Service']['AIGetUserPromptSettings']();
}

export function AIInstallClaudeCodeMCP() {
  return window['go']['aiservice']['Service']['AIInstallClaudeCodeMCP']();
}

export function AIInstallCodexMCP() {
  return window['go']['aiservice']['Service']['AIInstallCodexMCP']();
}

export function AIInstallDeepSeekHarnessMCP() {
  return window['go']['aiservice']['Service']['AIInstallDeepSeekHarnessMCP']();
}

export function AIInstallGrokBuildMCP() {
  return window['go']['aiservice']['Service']['AIInstallGrokBuildMCP']();
}

export function AIInstallKimiMCP() {
  return window['go']['aiservice']['Service']['AIInstallKimiMCP']();
}

export function AIInstallOpenCodeMCP() {
  return window['go']['aiservice']['Service']['AIInstallOpenCodeMCP']();
}

export function AIInstallZCodeMCP() {
  return window['go']['aiservice']['Service']['AIInstallZCodeMCP']();
}

export function AIListAgentSessions(arg1) {
  return window['go']['aiservice']['Service']['AIListAgentSessions'](arg1);
}

export function AIListCLIModels(arg1) {
  return window['go']['aiservice']['Service']['AIListCLIModels'](arg1);
}

export function AIListMCPTools() {
  return window['go']['aiservice']['Service']['AIListMCPTools']();
}

export function AIListModels() {
  return window['go']['aiservice']['Service']['AIListModels']();
}

export function AIMutateAgentSession(arg1) {
  return window['go']['aiservice']['Service']['AIMutateAgentSession'](arg1);
}

export function AIReadAgentRun(arg1) {
  return window['go']['aiservice']['Service']['AIReadAgentRun'](arg1);
}

export function AIReadAgentSession(arg1) {
  return window['go']['aiservice']['Service']['AIReadAgentSession'](arg1);
}

export function AISaveMCPServer(arg1) {
  return window['go']['aiservice']['Service']['AISaveMCPServer'](arg1);
}

export function AISaveProvider(arg1) {
  return window['go']['aiservice']['Service']['AISaveProvider'](arg1);
}

export function AISaveRunPolicy(arg1) {
  return window['go']['aiservice']['Service']['AISaveRunPolicy'](arg1);
}

export function AISaveSkill(arg1) {
  return window['go']['aiservice']['Service']['AISaveSkill'](arg1);
}

export function AISaveUserPromptSettings(arg1) {
  return window['go']['aiservice']['Service']['AISaveUserPromptSettings'](arg1);
}

export function AISetActiveProvider(arg1) {
  return window['go']['aiservice']['Service']['AISetActiveProvider'](arg1);
}

export function AISetContextLevel(arg1) {
  return window['go']['aiservice']['Service']['AISetContextLevel'](arg1);
}

export function AISetLanguage(arg1) {
  return window['go']['aiservice']['Service']['AISetLanguage'](arg1);
}

export function AISetSafetyLevel(arg1) {
  return window['go']['aiservice']['Service']['AISetSafetyLevel'](arg1);
}

export function AIStartMCPHTTPServer(arg1) {
  return window['go']['aiservice']['Service']['AIStartMCPHTTPServer'](arg1);
}

export function AIStopMCPHTTPServer() {
  return window['go']['aiservice']['Service']['AIStopMCPHTTPServer']();
}

export function AISubmitAgentInput(arg1) {
  return window['go']['aiservice']['Service']['AISubmitAgentInput'](arg1);
}

export function AITestMCPServer(arg1) {
  return window['go']['aiservice']['Service']['AITestMCPServer'](arg1);
}

export function AITestProvider(arg1) {
  return window['go']['aiservice']['Service']['AITestProvider'](arg1);
}

export function AIUpdateWorkspaceSnapshot(arg1) {
  return window['go']['aiservice']['Service']['AIUpdateWorkspaceSnapshot'](arg1);
}

export function Shutdown() {
  return window['go']['aiservice']['Service']['Shutdown']();
}
