package sync

import (
	"strings"
	"testing"

	"GoNavi-Wails/internal/connection"
)

// custom driver（Type=custom, Driver=dm 等）只有经过 resolveMigrationDBType
// 才能落到达梦等具体类型；capability 与 legacy planner 都按解析后的类型判定，
// 否则 custom 驱动的自动建表会被误拒。
func TestCustomDriverAutoCreateResolvesDriver(t *testing.T) {
	t.Parallel()

	source := connection.ConnectionConfig{Type: "custom", Driver: "dm"}
	target := connection.ConnectionConfig{Type: "mysql"}
	if got := resolveMigrationDBType(source); got != "dameng" {
		t.Fatalf("resolveMigrationDBType(custom,dm) = %q, want dameng", got)
	}

	capability := ResolveMigrationCapability(source, target)
	if !capability.CanExecute {
		t.Fatalf("custom(dm)->mysql must be executable: %+v", capability)
	}
	// planner 选 generic-legacy-planner 时，自动建表能力必须与解析后的类型一致。
	if capability.Planner == "generic-legacy-planner" && !capability.SupportsAutoCreate {
		t.Fatalf("custom(dm)->mysql resolved to dameng must support auto-create: %+v", capability)
	}
}

func TestOracleIdentityClausePerDialect(t *testing.T) {
	t.Parallel()

	autoIncrement := connection.ColumnDefinition{
		Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI", Extra: "auto_increment",
	}

	// Oracle 12c+ 只认 GENERATED BY DEFAULT AS IDENTITY，裸 IDENTITY(1,1) 语法错误。
	oracleDef, warnings := buildMySQLToOracleLikeColumnDefinition("oracle", autoIncrement)
	if !strings.Contains(oracleDef, "GENERATED BY DEFAULT AS IDENTITY") {
		t.Fatalf("oracle identity def: %q (warnings=%v)", oracleDef, warnings)
	}
	if strings.Contains(oracleDef, "IDENTITY(1,1)") {
		t.Fatalf("oracle must not use bare IDENTITY(1,1): %q", oracleDef)
	}

	// 达梦原生模式不识别 Oracle 12c 的 GENERATED BY DEFAULT 语法；真实实例
	// 会在 GENERATED 处报 Error -2007，必须使用其 IDENTITY(seed, increment)
	// 形式。
	damengDef, _ := buildMySQLToOracleLikeColumnDefinition("dameng", autoIncrement)
	if !strings.HasPrefix(damengDef, "BIGINT ") {
		t.Fatalf("dameng identity must use an integer column type: %q", damengDef)
	}
	if !strings.Contains(damengDef, "IDENTITY(1,1)") {
		t.Fatalf("dameng identity def: %q", damengDef)
	}
	if strings.Contains(damengDef, "GENERATED BY DEFAULT AS IDENTITY") {
		t.Fatalf("dameng must not use Oracle identity syntax: %q", damengDef)
	}

	// IRIS 不支持 IDENTITY，自增列建为普通数字列并告警。
	irisDef, irisWarnings := buildMySQLToOracleLikeColumnDefinition("iris", autoIncrement)
	if strings.Contains(strings.ToUpper(irisDef), "IDENTITY") {
		t.Fatalf("iris must not emit identity clause: %q", irisDef)
	}
	if len(irisWarnings) == 0 {
		t.Fatalf("iris 丢弃自增语义后未告警: %q", irisDef)
	}
}

func TestHighPrecisionDecimalClampedWithWarning(t *testing.T) {
	t.Parallel()

	big := connection.ColumnDefinition{Name: "v", Type: "decimal(65,30)", Nullable: "YES"}
	small := connection.ColumnDefinition{Name: "v", Type: "decimal(10,2)", Nullable: "YES"}

	oracleDef, oracleWarnings := buildMySQLToOracleLikeColumnDefinition("dameng", big)
	if oracleDef != "NUMBER(38,30)" {
		t.Fatalf("decimal(65,30) -> dameng = %q, want NUMBER(38,30)", oracleDef)
	}
	if len(oracleWarnings) == 0 {
		t.Fatalf("clamped precision must produce a warning")
	}

	sqlServerDef, ssWarnings := buildMySQLToSQLServerColumnDefinition(big)
	if sqlServerDef != "DECIMAL(38,30)" {
		t.Fatalf("decimal(65,30) -> sqlserver = %q, want DECIMAL(38,30)", sqlServerDef)
	}
	if len(ssWarnings) == 0 {
		t.Fatalf("clamped precision must produce a warning")
	}

	// 38 以内保持原样。
	oracleSmall, _ := buildMySQLToOracleLikeColumnDefinition("dameng", small)
	if oracleSmall != "NUMBER(10,2)" {
		t.Fatalf("decimal(10,2) -> dameng = %q, want NUMBER(10,2)", oracleSmall)
	}
	ssSmall, _ := buildMySQLToSQLServerColumnDefinition(small)
	if ssSmall != "DECIMAL(10,2)" {
		t.Fatalf("decimal(10,2) -> sqlserver = %q, want DECIMAL(10,2)", ssSmall)
	}
}

func TestCurrentDateAndTimeDefaultsSurvivePerDialect(t *testing.T) {
	t.Parallel()

	dateCol := connection.ColumnDefinition{Name: "d", Type: "date", Nullable: "YES", Default: stringPtr("CURRENT_DATE")}
	timeCol := connection.ColumnDefinition{Name: "t", Type: "time", Nullable: "YES", Default: stringPtr("CURRENT_TIME")}

	pgDef, pgWarn := buildMySQLToPGLikeColumnDefinition(dateCol)
	if !strings.Contains(pgDef, "DEFAULT CURRENT_DATE") || strings.Contains(pgDef, "'CURRENT_DATE'") {
		t.Fatalf("pg CURRENT_DATE def: %q (warnings=%v) —— 不得加引号", pgDef, pgWarn)
	}
	pgTimeDef, _ := buildMySQLToPGLikeColumnDefinition(timeCol)
	if !strings.Contains(pgTimeDef, "DEFAULT CURRENT_TIME") || strings.Contains(pgTimeDef, "'CURRENT_TIME'") {
		t.Fatalf("pg CURRENT_TIME def: %q", pgTimeDef)
	}

	oracleDef, oracleWarn := buildMySQLToOracleLikeColumnDefinition("dameng", dateCol)
	if !strings.Contains(oracleDef, "DEFAULT CURRENT_DATE") {
		t.Fatalf("oracle-like CURRENT_DATE def: %q (warnings=%v) —— 不得丢弃", oracleDef, oracleWarn)
	}

	// SQL Server 不实现 ANSI 的 CURRENT_DATE / CURRENT_TIME，断言这两个函数名
	// 不得出现在 DDL 里，只能是 GETDATE() 加类型转换。
	ssDef, ssWarn := buildMySQLToSQLServerColumnDefinition(dateCol)
	if !strings.Contains(ssDef, "DEFAULT CAST(GETDATE() AS DATE)") {
		t.Fatalf("sqlserver CURRENT_DATE def: %q (warnings=%v) —— 应为 CAST(GETDATE() AS DATE)", ssDef, ssWarn)
	}
	if strings.Contains(ssDef, "CURRENT_DATE") {
		t.Fatalf("sqlserver def 仍含 SQL Server 不支持的 CURRENT_DATE: %q", ssDef)
	}
	ssTimeDef, _ := buildMySQLToSQLServerColumnDefinition(timeCol)
	if !strings.Contains(ssTimeDef, "DEFAULT CAST(GETDATE() AS TIME)") {
		t.Fatalf("sqlserver CURRENT_TIME def: %q —— 应为 CAST(GETDATE() AS TIME)", ssTimeDef)
	}
	if strings.Contains(ssTimeDef, "CURRENT_TIME") {
		t.Fatalf("sqlserver def 仍含 SQL Server 不支持的 CURRENT_TIME: %q", ssTimeDef)
	}

	sqliteDef, _ := buildMySQLToSQLiteColumnDefinition(dateCol)
	if !strings.Contains(sqliteDef, "DEFAULT CURRENT_DATE") {
		t.Fatalf("sqlite CURRENT_DATE def: %q", sqliteDef)
	}
}

// TestCrossDialectDefaultNormalization 覆盖归一层的三类易错默认值：
// SQL Server 的 N 前缀 Unicode 字面量、PG 字面量内部的 ::、以及未知源类型降级。
func TestCrossDialectDefaultNormalization(t *testing.T) {
	t.Parallel()

	// N'abc' 必须剥掉 N 前缀与引号，否则目标侧再加一层会存成 N'N''abc'''。
	unicodeCol := connection.ColumnDefinition{Name: "c", Type: "nvarchar(50)", Nullable: "YES", Default: stringPtr("(N'abc')")}
	normalized, warning := normalizeCrossDialectDefault(unicodeCol)
	if normalized == nil || *normalized != "abc" {
		t.Fatalf("N'abc' 归一结果 = %v (warning=%q), want \"abc\"", normalized, warning)
	}
	ssUnicodeDef, _ := buildColumnDefinitionForTargetType("sqlserver", mustIntermediate(t, "sqlserver", "sqlserver", unicodeCol))
	if !strings.Contains(ssUnicodeDef, "DEFAULT N'abc'") {
		t.Fatalf("sqlserver N'abc' 往返结果: %q, want DEFAULT N'abc'", ssUnicodeDef)
	}

	// 'a::b'::text 的 :: 在字面量内部，不得当成转型运算符切断字符串。
	castCol := connection.ColumnDefinition{Name: "c", Type: "text", Nullable: "YES", Default: stringPtr("'a::b'::text")}
	castNormalized, castWarning := normalizeCrossDialectDefault(castCol)
	if castNormalized == nil || *castNormalized != "a::b" {
		t.Fatalf("'a::b'::text 归一结果 = %v (warning=%q), want \"a::b\"", castNormalized, castWarning)
	}

	// 普通转型仍要正常剥掉。
	plainCast := connection.ColumnDefinition{Name: "c", Type: "text", Nullable: "YES", Default: stringPtr("'abc'::character varying")}
	plainNormalized, _ := normalizeCrossDialectDefault(plainCast)
	if plainNormalized == nil || *plainNormalized != "abc" {
		t.Fatalf("'abc'::character varying 归一结果 = %v, want \"abc\"", plainNormalized)
	}

	// 转型带精度声明仍属纯类型，正常剥掉。
	precisionCast := connection.ColumnDefinition{Name: "c", Type: "text", Nullable: "YES", Default: stringPtr("'abc'::numeric(10,2)")}
	precisionNormalized, precisionWarning := normalizeCrossDialectDefault(precisionCast)
	if precisionNormalized == nil || *precisionNormalized != "abc" || precisionWarning != "" {
		t.Fatalf("'abc'::numeric(10,2) 归一结果 = %v (warning=%q), want \"abc\"/无告警", precisionNormalized, precisionWarning)
	}

	// nextval('s'::regclass) 是序列默认值，由自增语义承载，必须静默丢弃。
	nextvalCol := connection.ColumnDefinition{Name: "c", Type: "integer", Nullable: "YES", Default: stringPtr("nextval('s'::regclass)")}
	nextvalNormalized, nextvalWarning := normalizeCrossDialectDefault(nextvalCol)
	if nextvalNormalized != nil || nextvalWarning != "" {
		t.Fatalf("nextval 带转型的归一结果 = %v (warning=%q), want nil/无告警", nextvalNormalized, nextvalWarning)
	}

	// 转型后还跟着表达式时只取字面量会静默截断语义，必须丢弃并告警。
	exprCast := connection.ColumnDefinition{Name: "c", Type: "text", Nullable: "YES", Default: stringPtr("'a'::text || 'b'")}
	exprNormalized, exprWarning := normalizeCrossDialectDefault(exprCast)
	if exprNormalized != nil || exprWarning == "" {
		t.Fatalf("'a'::text || 'b' 归一结果 = %v (warning=%q), want nil + 告警", exprNormalized, exprWarning)
	}

	// 时刻函数带转型（now()::timestamp）保留"当前时刻"语义，不得静默丢弃。
	nowCast := connection.ColumnDefinition{Name: "c", Type: "timestamp", Nullable: "YES", Default: stringPtr("now()::timestamp")}
	nowNormalized, nowWarning := normalizeCrossDialectDefault(nowCast)
	if nowNormalized == nil || *nowNormalized != "CURRENT_TIMESTAMP" || nowWarning != "" {
		t.Fatalf("now()::timestamp 归一结果 = %v (warning=%q), want CURRENT_TIMESTAMP/无告警", nowNormalized, nowWarning)
	}

	// 裸标量转型（0::int）转型只改类型不改值，保留标量本身。
	bareCast := connection.ColumnDefinition{Name: "c", Type: "integer", Nullable: "YES", Default: stringPtr("0::integer")}
	bareNormalized, bareWarning := normalizeCrossDialectDefault(bareCast)
	if bareNormalized == nil || *bareNormalized != "0" || bareWarning != "" {
		t.Fatalf("0::integer 归一结果 = %v (warning=%q), want \"0\"/无告警", bareNormalized, bareWarning)
	}

	// 未知函数带转型（无法安全翻译）必须丢弃并告警，不得静默。
	fnCast := connection.ColumnDefinition{Name: "c", Type: "text", Nullable: "YES", Default: stringPtr("unknown_fn()::text")}
	fnNormalized, fnWarning := normalizeCrossDialectDefault(fnCast)
	if fnNormalized != nil || fnWarning == "" {
		t.Fatalf("unknown_fn()::text 归一结果 = %v (warning=%q), want nil + 告警", fnNormalized, fnWarning)
	}

	// 未知源类型不得原样进入 MySQL 目标 DDL，且必须带降级告警。
	for _, unknown := range []string{"hierarchyid", "bfile", "sql_variant"} {
		col := connection.ColumnDefinition{Name: "c", Type: unknown, Nullable: "YES"}
		intermediate, warnings := buildCrossDialectIntermediateColumn("oracle", "mysql", col)
		if intermediate.Type != "text" {
			t.Fatalf("源类型 %s 归一为 %q, want text", unknown, intermediate.Type)
		}
		if len(warnings) == 0 {
			t.Fatalf("源类型 %s 降级为 text 后未产生告警", unknown)
		}
		def, _ := buildColumnDefinitionForTargetType("mysql", intermediate)
		if strings.Contains(strings.ToLower(def), unknown) {
			t.Fatalf("源类型 %s 仍被拼进 MySQL DDL: %q", unknown, def)
		}
	}
}

func mustIntermediate(t *testing.T, sourceType string, targetType string, col connection.ColumnDefinition) connection.ColumnDefinition {
	t.Helper()
	intermediate, _ := buildCrossDialectIntermediateColumn(sourceType, targetType, col)
	return intermediate
}

// TestKeyColumnNeverDegradesToLOB 锁住"降级不得破坏建表"这条底线。
// 主键/索引列一旦落成 MySQL TEXT / Oracle 系 CLOB / SQL Server NVARCHAR(MAX)，
// 建表或建索引阶段会直接失败，降级反而让整张表建不出来。
func TestKeyColumnNeverDegradesToLOB(t *testing.T) {
	t.Parallel()

	lobProducingTypes := []string{
		"hierarchyid", "sql_variant", "bfile", // 无映射类型
		"text", "clob", "json", "bytea", "nvarchar(max)", // 本身就是 LOB
		"varchar", "character varying", "bit varying", // 无长度声明
	}
	// 键列收紧是目标相关的：MySQL/Oracle 系/SQL Server 拒绝 LOB 进索引，
	// PG 系与 SQLite 允许 text 主键。所以断言分两组，且都必须经过
	// applyKeyColumnTypeSafety —— 归一层只保证类型合法，不做键列收口。
	strictTargets := []string{"mysql", "mariadb", "dameng", "oracle", "iris", "sqlserver"}
	lenientTargets := []string{"postgres", "kingbase", "duckdb", "sqlite"}

	for _, sourceType := range lobProducingTypes {
		for _, key := range []string{"PRI", "PK", "UNI", "MUL"} {
			col := connection.ColumnDefinition{Name: "id", Type: sourceType, Nullable: "NO", Key: key}

			for _, target := range strictTargets {
				// 归一层现在按目标决定负 scale 是否折算，所以必须在目标循环内归一。
				intermediate, _ := buildCrossDialectIntermediateColumn("oracle", target, col)
				safe, keyWarnings := applyKeyColumnTypeSafety(target, intermediate)
				// 降级必须保持类型族：二进制列退成字符列会让原始字节
				// 按目标字符集重新解释，数据静默损坏。
				wantType := keyColumnFallbackType(target, intermediate)
				if safe.Type != wantType {
					t.Fatalf("源类型 %s（Key=%s，目标 %s）收紧为 %q, want %q",
						sourceType, key, target, safe.Type, wantType)
				}
				if len(keyWarnings) == 0 {
					t.Fatalf("源类型 %s（Key=%s，目标 %s）收紧后未告警", sourceType, key, target)
				}
				def, _ := buildColumnDefinitionForTargetType(target, safe)
				upper := strings.ToUpper(def)
				for _, lob := range []string{"CLOB", "TEXT", "NVARCHAR(MAX)", "BLOB"} {
					if strings.Contains(upper, lob) {
						t.Fatalf("源类型 %s（Key=%s）在目标 %s 仍生成不可索引类型: %q",
							sourceType, key, target, def)
					}
				}
			}

			// 宽松目标不得被无谓截断：PG 的 text/jsonb 主键本来就能建。
			for _, target := range lenientTargets {
				intermediate, _ := buildCrossDialectIntermediateColumn("oracle", target, col)
				safe, keyWarnings := applyKeyColumnTypeSafety(target, intermediate)
				if safe.Type != intermediate.Type {
					t.Fatalf("源类型 %s（Key=%s，目标 %s）被无谓改写为 %q, want 保持 %q",
						sourceType, key, target, safe.Type, intermediate.Type)
				}
				if len(keyWarnings) != 0 {
					t.Fatalf("源类型 %s（Key=%s，目标 %s）无需收紧却告警: %v",
						sourceType, key, target, keyWarnings)
				}
			}
		}
	}
}

// TestDedicatedMySQLSourcePathsApplyKeyColumnSafety 锁住三条 MySQL 源专用建表路径
// 也过键列收口。它们不走 buildCrossDialectIntermediateColumn，早期实现漏接过一次：
// text 主键在达梦上生成 CLOB 后还会拼 PRIMARY KEY，建表直接失败。
func TestDedicatedMySQLSourcePathsApplyKeyColumnSafety(t *testing.T) {
	t.Parallel()

	for _, sourceType := range []string{"text", "json", "longtext", "mediumtext", "blob"} {
		col := connection.ColumnDefinition{Name: "id", Type: sourceType, Nullable: "NO", Key: "PRI"}

		// 断言不变量而非具体长度：长度策略会随各目标上限调整，写死数值会让
		// 测试在无害改动下假失败。真正的底线是类型族不能变 —— 二进制列退成
		// 字符列会让原始字节被按目标字符集重新解释，属于静默数据损坏。
		wantPrefix := "varchar"
		if sourceType == "blob" {
			wantPrefix = "varbinary"
		}

		for _, target := range []string{"dameng", "oracle", "iris", "sqlserver"} {
			safe, warnings := applyKeyColumnTypeSafety(target, col)
			if !strings.HasPrefix(safe.Type, wantPrefix) {
				t.Fatalf("MySQL 源 %s 主键在目标 %s 收紧为 %q, want %s 族",
					sourceType, target, safe.Type, wantPrefix)
			}
			if len(warnings) == 0 {
				t.Fatalf("MySQL 源 %s 主键在目标 %s 收紧后未告警", sourceType, target)
			}

			var def string
			if isOracleLikeTargetType(target) {
				def, _ = buildMySQLToOracleLikeColumnDefinition(target, safe)
			} else {
				def, _ = buildMySQLToSQLServerColumnDefinition(safe)
			}
			upper := strings.ToUpper(def)
			for _, lob := range []string{"CLOB", "NVARCHAR(MAX)", "BLOB"} {
				if strings.Contains(upper, lob) {
					t.Fatalf("MySQL 源 %s 主键在目标 %s 仍生成不可索引类型: %q", sourceType, target, def)
				}
			}
		}

		// 非键列不受影响，LOB 语义必须保留。
		plain := connection.ColumnDefinition{Name: "body", Type: sourceType, Nullable: "YES"}
		if safe, warnings := applyKeyColumnTypeSafety("dameng", plain); safe.Type != sourceType || len(warnings) != 0 {
			t.Fatalf("非键列 %s 被改写为 %q (warnings=%v)", sourceType, safe.Type, warnings)
		}
	}
}

// TestStandardTypeAliasesKeepPrecision 防止类型白名单把标准别名误判为无映射类型。
// dec / bpchar / int1 这些是同一类型的另一种写法，降级为 text 会丢掉本来能
// 精确迁移的精度与长度。
func TestStandardTypeAliasesKeepPrecision(t *testing.T) {
	t.Parallel()

	cases := map[string]string{
		"dec(10,2)":        "decimal(10,2)",
		"fixed(10,2)":      "decimal(10,2)",
		"bpchar(10)":       "char(10)",
		"bpchar":           "char(1)",
		"native character": "char(1)",
		"int1":             "tinyint",
		"int3":             "mediumint",
		"middleint":        "mediumint",
		"unsigned big int": "bigint",
		"binary_integer":   "int",
		"pls_integer":      "int",
		"smallmoney":       "decimal(10,4)",
		"varbit(8)":        "varchar(8)",
		"bit varying(8)":   "varchar(8)",
	}

	for sourceType, want := range cases {
		col := connection.ColumnDefinition{Name: "c", Type: sourceType, Nullable: "YES"}
		intermediate, _ := buildCrossDialectIntermediateColumn("oracle", "mysql", col)
		if intermediate.Type != want {
			t.Fatalf("源类型 %s 归一为 %q, want %q", sourceType, intermediate.Type, want)
		}
	}
}

// TestUnboundedDecimalIsPinnedAndWarned 无精度定点数会被钉成上界精度，
// 这是有损假设（超出精度的数据写入会失败），必须显式告警而非静默处理。
func TestUnboundedDecimalIsPinnedAndWarned(t *testing.T) {
	t.Parallel()

	for _, sourceType := range []string{"numeric", "decimal", "number", "dec"} {
		col := connection.ColumnDefinition{Name: "amount", Type: sourceType, Nullable: "YES"}
		intermediate, warnings := buildCrossDialectIntermediateColumn("oracle", "mysql", col)
		if intermediate.Type != unboundedDecimalIntermediateType {
			t.Fatalf("裸 %s 归一为 %q, want %q",
				sourceType, intermediate.Type, unboundedDecimalIntermediateType)
		}
		if len(warnings) == 0 {
			t.Fatalf("裸 %s 钉成 %s 属有损假设，必须告警", sourceType, unboundedDecimalIntermediateType)
		}
		// MySQL 隐式补 decimal(10,0) 会截断小数位，必须带显式精度。
		mysqlDef, _ := buildColumnDefinitionForTargetType("mysql", intermediate)
		if !strings.Contains(mysqlDef, unboundedDecimalIntermediateType) {
			t.Fatalf("裸 %s 在 MySQL 目标生成 %q, 未带显式精度", sourceType, mysqlDef)
		}
	}

	// 声明了精度的定点数必须原样保留，不得被上界覆盖，也不该告警。
	col := connection.ColumnDefinition{Name: "amount", Type: "numeric(10,2)", Nullable: "YES"}
	intermediate, warnings := buildCrossDialectIntermediateColumn("oracle", "mysql", col)
	if intermediate.Type != "decimal(10,2)" {
		t.Fatalf("numeric(10,2) 归一为 %q, want decimal(10,2)", intermediate.Type)
	}
	if len(warnings) != 0 {
		t.Fatalf("numeric(10,2) 精度完整，不应告警: %v", warnings)
	}
}

// TestBoundedBinaryKeyColumnStaysIndexable 锁住有界二进制列不得落成 LOB。
//
// BINARY(16) 是 UUID / 哈希主键的常见写法。早期实现把所有 binary/varbinary 一律
// 映射为 BLOB / VARBINARY(MAX)，于是 Oracle 系生成 "BLOB ... PRIMARY KEY"、
// SQL Server 生成 "VARBINARY(MAX) ... PRIMARY KEY"，两者都在建表阶段直接失败。
// 键列收口只看中间类型基础名时拦不住这种情况：binary 不在 LOB 集合里。
func TestBoundedBinaryKeyColumnStaysIndexable(t *testing.T) {
	t.Parallel()

	// 目标 -> 该目标下 BINARY(16) 期望落成的类型片段。
	wantByTarget := map[string]string{
		"dameng":    "RAW(16)",
		"oracle":    "RAW(16)",
		"iris":      "VARBINARY(16)",
		"sqlserver": "BINARY(16)",
	}

	for target, want := range wantByTarget {
		col := connection.ColumnDefinition{Name: "id", Type: "binary(16)", Nullable: "NO", Key: "PRI"}
		safe, _ := applyKeyColumnTypeSafety(target, col)
		def, _ := buildColumnDefinitionForTargetType(target, safe)
		if !strings.Contains(strings.ToUpper(def), want) {
			t.Fatalf("目标 %s：binary(16) 主键生成 %q, want 含 %s", target, def, want)
		}
		if isUnindexableTargetColumnType(def) {
			t.Fatalf("目标 %s：binary(16) 主键仍落成不可索引类型 %q", target, def)
		}
	}

	// 超过 RAW / BINARY 上限时只能降级，但必须保持二进制族：
	// 退成字符类型会让原始字节按目标字符集重新解释，数据静默损坏。
	for _, target := range []string{"dameng", "oracle", "sqlserver"} {
		col := connection.ColumnDefinition{Name: "id", Type: "binary(8000)", Nullable: "NO", Key: "PRI"}
		safe, warnings := applyKeyColumnTypeSafety(target, col)
		// 断言不变量而非具体长度：具体长度取决于"索引键上限"与"类型自身可声明
		// 上限"两个独立约束的交集（达梦索引键 3200 但 RAW 只到 2000），写死数字
		// 会在实现调整策略时假失败，却挡不住真正的破坏。
		//
		// 底线一：必须仍是二进制族。退成字符列会让原始字节按目标字符集重新
		// 解释，属于静默数据损坏。
		if !strings.HasPrefix(safe.Type, "varbinary") {
			t.Fatalf("目标 %s：binary(8000) 主键降级为 %q, 已脱离二进制族", target, safe.Type)
		}
		if len(warnings) == 0 {
			t.Fatalf("目标 %s：binary(8000) 主键降级后未告警", target)
		}
		// 底线二：降级结果必须真的能做键列，不能绕回不可索引的原点。
		def, _ := buildColumnDefinitionForTargetType(target, safe)
		if reason, rejected := keyColumnRejectionReason(target, def); rejected {
			t.Fatalf("目标 %s：binary(8000) 主键降级为 %q 后仍不可做键列（%s）: %q",
				target, safe.Type, reason, def)
		}
		// 底线三：不得无谓砍到兜底长度。主键被过度截短会在导入阶段写入失败，
		// 或截断后产生主键冲突 —— 能保住多少就要保住多少。
		gotLength, ok := parseTypeLength(safe.Type)
		if !ok {
			t.Fatalf("目标 %s：binary(8000) 主键降级为 %q, 未保留长度", target, safe.Type)
		}
		if fallbackLength, _ := parseTypeLength(binaryKeyColumnFallbackType); gotLength <= fallbackLength {
			t.Fatalf("目标 %s：binary(8000) 主键降级为 %q, 长度被无谓砍到兜底值 %d 以下",
				target, safe.Type, fallbackLength)
		}
	}

	// 超长字符串主键同理：varchar(8000) 在 Oracle 系落 CLOB、
	// 在 SQL Server 落 NVARCHAR(MAX)，基础名都不在 LOB 集合里。
	for _, target := range []string{"dameng", "oracle", "sqlserver"} {
		col := connection.ColumnDefinition{Name: "id", Type: "varchar(8000)", Nullable: "NO", Key: "PRI"}
		safe, warnings := applyKeyColumnTypeSafety(target, col)
		// 同样断言不变量：必须仍是有界字符类型，且不得被无谓砍到兜底长度 ——
		// 主键被截短会在导入阶段写入失败，或截断后产生主键冲突。
		if !strings.HasPrefix(safe.Type, "varchar(") {
			t.Fatalf("目标 %s：varchar(8000) 主键降级为 %q, want 有界 varchar", target, safe.Type)
		}
		length, ok := parseTypeLength(safe.Type)
		if !ok || length < 255 {
			t.Fatalf("目标 %s：varchar(8000) 主键降级为 %q, 长度未保住", target, safe.Type)
		}
		if len(warnings) == 0 {
			t.Fatalf("目标 %s：varchar(8000) 主键降级后未告警", target)
		}
		def, _ := buildColumnDefinitionForTargetType(target, safe)
		if isUnindexableTargetColumnType(def) {
			t.Fatalf("目标 %s：varchar(8000) 主键降级后仍不可索引 %q", target, def)
		}
	}
}

// TestNegativeDecimalScaleFoldedOnlyWhenTargetNeedsIt 锁住负 scale 的折算是目标相关的。
//
// Oracle 的 NUMBER(10,-2) 语义是向左舍入到百位。Oracle / 达梦 本身支持负 scale，
// 对它们折成 DECIMAL(12,0) 会丢掉舍入语义；而 MySQL / PG / SQL Server / IRIS 的
// scale 必须非负，不折则建表直接失败。两侧都要断言，否则修一边会破另一边。
func TestNegativeDecimalScaleFoldedOnlyWhenTargetNeedsIt(t *testing.T) {
	t.Parallel()

	col := connection.ColumnDefinition{Name: "amount", Type: "NUMBER(10,-2)", Nullable: "YES"}

	for _, target := range []string{"oracle", "dameng"} {
		intermediate, warnings := buildCrossDialectIntermediateColumn("oracle", target, col)
		if intermediate.Type != "decimal(10,-2)" {
			t.Fatalf("目标 %s：NUMBER(10,-2) 归一为 %q, want decimal(10,-2)（原生支持不该折算）",
				target, intermediate.Type)
		}
		if len(warnings) != 0 {
			t.Fatalf("目标 %s 原生支持负 scale，不应告警: %v", target, warnings)
		}
	}

	// IRIS 属 Oracle 语法族，但 DECIMAL 不接受负 scale，必须与 MySQL 侧一致折算。
	for _, target := range []string{"mysql", "postgres", "sqlserver", "sqlite", "iris"} {
		intermediate, warnings := buildCrossDialectIntermediateColumn("oracle", target, col)
		if intermediate.Type != "decimal(12,0)" {
			t.Fatalf("目标 %s：NUMBER(10,-2) 归一为 %q, want decimal(12,0)（p+|s| 保住可存范围）",
				target, intermediate.Type)
		}
		if len(warnings) == 0 {
			t.Fatalf("目标 %s：折算丢掉了向左舍入语义，必须告警", target)
		}
		// 折算后的类型必须能真正建出来，不能残留负号。
		def, _ := buildColumnDefinitionForTargetType(target, intermediate)
		if strings.Contains(def, "-") {
			t.Fatalf("目标 %s：折算后仍残留负 scale: %q", target, def)
		}
	}

	// 非负 scale 不得被这条路径改写。
	plain := connection.ColumnDefinition{Name: "amount", Type: "NUMBER(10,2)", Nullable: "YES"}
	for _, target := range []string{"oracle", "dameng", "mysql", "postgres", "sqlserver", "iris"} {
		intermediate, warnings := buildCrossDialectIntermediateColumn("oracle", target, plain)
		if intermediate.Type != "decimal(10,2)" {
			t.Fatalf("目标 %s：NUMBER(10,2) 被改写为 %q, want decimal(10,2)", target, intermediate.Type)
		}
		if len(warnings) != 0 {
			t.Fatalf("目标 %s：NUMBER(10,2) 无需折算却告警: %v", target, warnings)
		}
	}
}

// TestKeyColumnLengthLimitIsPerDialect 锁住键列长度上限必须分方言。
//
// 早期实现取跨库最小值 900 一刀切，把 MySQL 上完全合法的 varchar(1000) 主键
// 砍成 varchar(255)：主键被截短会在数据导入阶段才暴露 —— 超长值写入失败，
// 或截断后产生主键冲突，属于静默数据损坏。
func TestKeyColumnLengthLimitIsPerDialect(t *testing.T) {
	t.Parallel()

	// varchar(1000) 在 MySQL(3072) / Oracle 系(3200) 的索引键上限内，必须原样保留；
	// 只有 SQL Server 的 900 字节聚集索引上限装不下。
	for _, target := range []string{"mysql", "mariadb", "dameng", "oracle", "iris"} {
		col := connection.ColumnDefinition{Name: "id", Type: "varchar(1000)", Nullable: "NO", Key: "PRI"}
		safe, warnings := applyKeyColumnTypeSafety(target, col)
		if safe.Type != "varchar(1000)" {
			t.Fatalf("目标 %s：varchar(1000) 主键在索引键上限内却被改写为 %q", target, safe.Type)
		}
		if len(warnings) != 0 {
			t.Fatalf("目标 %s：varchar(1000) 主键无需收紧却告警: %v", target, warnings)
		}
	}

	// 超上限时必须收到该目标的上限，而不是兜底的 255 —— 能保住多少就保住多少。
	wantByTarget := map[string]string{
		"mysql":     "varchar(3072)",
		"dameng":    "varchar(3200)",
		"oracle":    "varchar(3200)",
		"sqlserver": "varchar(900)",
	}
	for target, want := range wantByTarget {
		col := connection.ColumnDefinition{Name: "id", Type: "varchar(4000)", Nullable: "NO", Key: "PRI"}
		safe, warnings := applyKeyColumnTypeSafety(target, col)
		if safe.Type != want {
			t.Fatalf("目标 %s：varchar(4000) 主键收紧为 %q, want %q", target, safe.Type, want)
		}
		if len(warnings) == 0 {
			t.Fatalf("目标 %s：varchar(4000) 主键收紧后未告警", target)
		}
		// 收紧后必须真的能做键列，否则等于没修。
		def, _ := buildColumnDefinitionForTargetType(target, safe)
		if reason, rejected := keyColumnRejectionReason(target, def); rejected {
			t.Fatalf("目标 %s：varchar(4000) 收紧为 %q 后仍不可做键列（%s）", target, def, reason)
		}
	}

	// 二进制键列超上限时同样按目标上限收，且不得退成字符类型。
	binSafe, binWarnings := applyKeyColumnTypeSafety("sqlserver",
		connection.ColumnDefinition{Name: "id", Type: "varbinary(2000)", Nullable: "NO", Key: "PRI"})
	if binSafe.Type != "varbinary(900)" {
		t.Fatalf("sqlserver：varbinary(2000) 主键收紧为 %q, want varbinary(900)", binSafe.Type)
	}
	if len(binWarnings) == 0 {
		t.Fatalf("sqlserver：varbinary(2000) 主键收紧后未告警")
	}
}

// TestOracleRawStaysBinaryAcrossTargets 锁住 Oracle/达梦 的 RAW(n) 必须保持二进制族。
//
// RAW(n) 早期没有归一分支，落到 default 后被 knownIntermediateMySQLTypeBases
// 当成无映射类型降级为 text：二进制字节按目标字符集重新解释，非键列也会静默
// 损坏数据；做主键时还会被键列收口再降级成 varchar，掩盖了根因。
func TestOracleRawStaysBinaryAcrossTargets(t *testing.T) {
	t.Parallel()

	binaryTargets := []string{"mysql", "mariadb", "dameng", "oracle", "iris", "sqlserver", "postgres", "sqlite"}

	for _, sourceType := range []string{"raw(100)", "raw(500)", "raw(2000)"} {
		for _, target := range binaryTargets {
			// 普通列：归一结果必须是二进制族。
			plain := connection.ColumnDefinition{Name: "payload", Type: sourceType, Nullable: "YES"}
			intermediate, _ := buildCrossDialectIntermediateColumn("oracle", target, plain)
			if base := intermediateMySQLTypeBase(intermediate.Type); base != "varbinary" {
				t.Fatalf("目标 %s：%s 归一为 %q（族 %s）, want varbinary 族",
					target, sourceType, intermediate.Type, base)
			}

			// 键列：收紧后仍须是二进制族，长度在上限内时不该被改写。
			key := connection.ColumnDefinition{Name: "id", Type: sourceType, Nullable: "NO", Key: "PRI"}
			keyIntermediate, _ := buildCrossDialectIntermediateColumn("oracle", target, key)
			safe, _ := applyKeyColumnTypeSafety(target, keyIntermediate)
			switch intermediateMySQLTypeBase(safe.Type) {
			case "binary", "varbinary", "blob", "longblob", "mediumblob", "tinyblob":
			default:
				t.Fatalf("目标 %s：%s 主键收紧为 %q, 已脱离二进制族",
					target, sourceType, safe.Type)
			}
		}
	}

	// RAW(16) 是 UUID 惯例，仍按可读的 varchar(36) 迁移，不受上面的规则影响。
	uuidCol := connection.ColumnDefinition{Name: "id", Type: "raw(16)", Nullable: "NO", Key: "PRI"}
	uuidIntermediate, _ := buildCrossDialectIntermediateColumn("oracle", "mysql", uuidCol)
	if uuidIntermediate.Type != "varchar(36)" {
		t.Fatalf("raw(16) 归一为 %q, want varchar(36)", uuidIntermediate.Type)
	}
}

// TestSQLiteNeverEmitsTwoPrimaryKeys 锁住 SQLite 目标不得生成两个 PRIMARY KEY。
//
// SQLite 的 "INTEGER PRIMARY KEY AUTOINCREMENT" 自带主键约束，且只对单列整数
// 主键合法。若照抄源端自增标记，两种情况会生成非法 DDL（报 "table has more
// than one primary key"，建表 100% 失败）：
//   - 复合主键含自增列：内联子句 + 末尾 PRIMARY KEY(...)，且复合主键被拆散；
//   - 自增列不是主键：非主键列被变成主键，真正的主键另起一个子句。
//
// 两条建表路径都要覆盖。通用互转层曾漏掉这道关卡，根因是判定顺序：各方言表达
// 自增的方式不同（Oracle 的 Extra="IDENTITY"、PG 的类型 serial），必须在归一层
// 统一成 auto_increment 之后再判定，否则一个都认不出来。
func TestSQLiteNeverEmitsTwoPrimaryKeys(t *testing.T) {
	t.Parallel()

	assertSinglePrimaryKey := func(t *testing.T, label, sql string, warnings []string, wantWarning bool) {
		t.Helper()
		if n := strings.Count(strings.ToUpper(sql), "PRIMARY KEY"); n != 1 {
			t.Fatalf("%s：生成 %d 个 PRIMARY KEY 子句，want 1\n%s", label, n, sql)
		}
		// 丢弃自增语义是有损的（目标端插入不再自动生成 ID），必须告知用户。
		if wantWarning && len(warnings) == 0 {
			t.Fatalf("%s：丢弃自增语义后未告警", label)
		}
	}

	// MySQL 源专用路径。
	mysqlCases := []struct {
		label       string
		cols        []connection.ColumnDefinition
		wantWarning bool
	}{
		{"复合主键含自增", []connection.ColumnDefinition{
			{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI", Extra: "auto_increment"},
			{Name: "tenant", Type: "int", Nullable: "NO", Key: "PRI"},
		}, true},
		{"自增列非主键", []connection.ColumnDefinition{
			{Name: "pk", Type: "varchar(10)", Nullable: "NO", Key: "PRI"},
			{Name: "seq", Type: "int", Nullable: "NO", Key: "UNI", Extra: "auto_increment"},
		}, true},
		{"单列自增主键", []connection.ColumnDefinition{
			{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI", Extra: "auto_increment"},
		}, false},
	}
	for _, tc := range mysqlCases {
		sql, _, warnings, _, _, _, _, err := buildMySQLToSQLiteCreateTablePlan(
			"sqlite", SyncConfig{}, "t", tc.cols, &fakeMigrationDB{}, "", "t")
		if err != nil {
			t.Fatalf("%s: %v", tc.label, err)
		}
		assertSinglePrimaryKey(t, "MySQL 源/"+tc.label, sql, warnings, tc.wantWarning)
	}

	// 通用互转层：源端自增语义不在 Extra="auto_increment" 里，只有归一后才认得出。
	crossCases := []struct {
		label  string
		source string
		cols   []connection.ColumnDefinition
	}{
		{"Oracle identity 参与复合主键", "oracle", []connection.ColumnDefinition{
			{Name: "id", Type: "NUMBER(19)", Nullable: "NO", Key: "PRI", Extra: "IDENTITY"},
			{Name: "tenant", Type: "NUMBER(10)", Nullable: "NO", Key: "PRI"},
		}},
		{"PG serial 非主键", "postgres", []connection.ColumnDefinition{
			{Name: "pk", Type: "varchar(10)", Nullable: "NO", Key: "PRI"},
			{Name: "seq", Type: "serial", Nullable: "NO", Key: "UNI"},
		}},
	}
	for _, tc := range crossCases {
		sql, _, warnings, _, _, _, _, err := buildCrossDialectAutoCreatePlan(
			tc.source, "sqlite", SyncConfig{}, "t", tc.cols, &fakeMigrationDB{}, "", "t")
		if err != nil {
			t.Fatalf("%s: %v", tc.label, err)
		}
		assertSinglePrimaryKey(t, "通用互转/"+tc.label, sql, warnings, true)
	}
}

// TestDorisTargetNeverAutoCreates 锁住 Doris/StarRocks 目标不得自动建表。
//
// 这两个目标的 CREATE TABLE 必须带 key model（DUPLICATE/UNIQUE/AGGREGATE KEY）
// 与 DISTRIBUTED BY 分桶定义，普通 MySQL DDL 下发即失败。但 isMySQLCoreType 把
// 它们视为 MySQL 系可写目标，pglike-mysql-planner / clickhouse-mysql-planner /
// mongo-mysql-planner / tdengine-mysql-planner 会以 Full 级接管，而 Full 级在
// capability 里本来无条件给出 SupportsAutoCreate=true。
//
// capability 与 plan 两层都要断言：只收口 capability 会让 UI 显示"不能自动创建"
// 但 plan 仍带着 AutoCreate=true 与 CreateTableSQL 进入执行期，仍然会建表失败。
func TestDorisTargetNeverAutoCreates(t *testing.T) {
	t.Parallel()

	sourceTypes := []string{"mysql", "postgres", "kingbase", "oracle", "dameng",
		"sqlserver", "sqlite", "clickhouse", "mongodb", "tdengine"}

	for _, target := range []string{"diros", "starrocks"} {
		for _, source := range sourceTypes {
			sourceConfig := connection.ConnectionConfig{Type: source}
			targetConfig := connection.ConnectionConfig{Type: target}

			capability := ResolveMigrationCapability(sourceConfig, targetConfig)
			if capability.SupportsAutoCreate {
				t.Fatalf("%s -> %s：capability 声明支持自动建表（planner=%s），"+
					"但该目标必须带分桶定义，普通 DDL 建表必失败",
					source, target, capability.Planner)
			}
			if !capability.RequiresExistingTarget {
				t.Fatalf("%s -> %s：未标记为要求目标表已存在", source, target)
			}

			// plan 层必须一致，否则执行期仍会下发缺分桶定义的 DDL。
			config := SyncConfig{
				SourceConfig:        sourceConfig,
				TargetConfig:        targetConfig,
				TargetTableStrategy: "auto_create_if_missing",
			}
			plan, _, _, err := buildSchemaMigrationPlan(config, "t",
				&fakeMigrationDB{columns: map[string][]connection.ColumnDefinition{
					"t": {{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI"}},
				}},
				&fakeMigrationDB{})
			if err != nil {
				// 源方言缺元数据支持时构建失败属正常，跳过 plan 断言。
				continue
			}
			if plan.AutoCreate {
				t.Fatalf("%s -> %s：plan 仍标记自动建表", source, target)
			}
			if strings.TrimSpace(plan.CreateTableSQL) != "" {
				t.Fatalf("%s -> %s：plan 仍带建表语句:\n%s", source, target, plan.CreateTableSQL)
			}
			if len(plan.Warnings) == 0 {
				t.Fatalf("%s -> %s：拒绝自动建表却未告警", source, target)
			}
		}
	}
}

// TestOracleDateSourceKeepsTimeOfDay 锁住 Oracle/达梦 源 DATE 的时分秒。
//
// Oracle 的 DATE 固定存到秒（达梦兼容 Oracle），归一层若按字面量落成 date，
// MySQL 等目标会静默丢掉时间分量；必须转成 datetime 承载。PG/MySQL 系源的
// DATE 是纯日期，不得被改写。
func TestOracleDateSourceKeepsTimeOfDay(t *testing.T) {
	t.Parallel()

	col := connection.ColumnDefinition{Name: "d", Type: "date", Nullable: "YES"}

	for _, source := range []string{"oracle", "dameng"} {
		for _, target := range []string{"mysql", "postgres", "dameng"} {
			intermediate, _ := buildCrossDialectIntermediateColumn(source, target, col)
			if intermediate.Type != "datetime" {
				t.Fatalf("源 %s 的 DATE 归一为 %q（目标 %s）, want datetime", source, intermediate.Type, target)
			}
		}
	}

	for _, source := range []string{"postgres", "mysql", "sqlite"} {
		intermediate, _ := buildCrossDialectIntermediateColumn(source, "mysql", col)
		if intermediate.Type != "date" {
			t.Fatalf("源 %s 的 DATE 归一为 %q, want date（纯日期语义不变）", source, intermediate.Type)
		}
	}

	// 端到端：Oracle DATE 到 MySQL 目标应生成 DATETIME 列。
	intermediate, _ := buildCrossDialectIntermediateColumn("oracle", "mysql", col)
	def, _ := buildColumnDefinitionForTargetType("mysql", intermediate)
	if !strings.Contains(strings.ToUpper(def), "DATETIME") {
		t.Fatalf("oracle date 在 MySQL 目标生成 %q, want 含 DATETIME", def)
	}
}

// TestSQLServerAutoIncrementColumnNeverBecomesBIT 锁住 SQL Server 自增列的
// 类型与 identity 处理。
//
// 自增的 tinyint(1) 不能映射 BIT（BIT 无法承载整数主键），必须落整数分支；
// 同时 SQL Server 的 IDENTITY 列拒绝显式插入，映射器不产出 identity 并告警，
// 由建表与补列路径消费该约定。
func TestSQLServerAutoIncrementColumnNeverBecomesBIT(t *testing.T) {
	t.Parallel()

	autoCol := connection.ColumnDefinition{Name: "id", Type: "tinyint(4)", Nullable: "NO", Extra: "auto_increment"}
	gotType, useIdentity, gotWarnings := mapMySQLColumnToSQLServer(autoCol)
	if gotType != "SMALLINT" || useIdentity {
		t.Fatalf("tinyint(4) auto_increment -> %q identity=%v, want SMALLINT identity=false", gotType, useIdentity)
	}
	if len(gotWarnings) == 0 {
		t.Fatalf("丢弃自增语义后未告警")
	}

	// tinyint(1) + 自增同样落 SMALLINT（BIT 分支只在无自增时命中）。
	flagAuto := connection.ColumnDefinition{Name: "id", Type: "tinyint(1)", Nullable: "NO", Extra: "auto_increment"}
	flagType, flagIdentity, flagWarnings := mapMySQLColumnToSQLServer(flagAuto)
	if flagType != "SMALLINT" || flagIdentity {
		t.Fatalf("tinyint(1) auto_increment -> %q identity=%v, want SMALLINT identity=false", flagType, flagIdentity)
	}
	if len(flagWarnings) == 0 {
		t.Fatalf("丢弃自增语义后未告警")
	}

	// 布尔用途的 tinyint(1)（无自增）仍应映射 BIT 且无告警。
	flag := connection.ColumnDefinition{Name: "flag", Type: "tinyint(1)", Nullable: "YES"}
	flagGot, flagIdentity, flagWarnings := mapMySQLColumnToSQLServer(flag)
	if flagGot != "BIT" || flagIdentity || len(flagWarnings) != 0 {
		t.Fatalf("tinyint(1)（无自增）-> %q identity=%v warnings=%v, want BIT/无告警", flagGot, flagIdentity, flagWarnings)
	}
}

func TestSQLServerTinyintIdentitySurvivesCrossDialectNormalization(t *testing.T) {
	t.Parallel()

	intermediate, warnings := buildCrossDialectIntermediateColumn("sqlserver", "postgres", connection.ColumnDefinition{
		Name: "id", Type: "tinyint", Nullable: "NO", Key: "PRI", Extra: "auto_increment",
	})
	if intermediate.Type != "tinyint" || intermediate.Extra != "auto_increment" {
		t.Fatalf("sqlserver tinyint identity normalization = %+v, want tinyint auto_increment (warnings=%v)", intermediate, warnings)
	}
}

// TestBareBinaryTypeBecomesBlob 裸 binary/varbinary（无长度声明）不得落成 CLOB。
//
// CLOB 存二进制会被按目标字符集重新解释而静默损坏数据，必须落 BLOB；
// 带长度时仍走有界二进制路径（RAW(n)）。
func TestBareBinaryTypeBecomesBlob(t *testing.T) {
	t.Parallel()

	for _, raw := range []string{"binary", "varbinary"} {
		col := connection.ColumnDefinition{Name: "v", Type: raw, Nullable: "YES"}
		got, _, _ := mapMySQLColumnToOracleLike("dameng", col)
		if got != "BLOB" {
			t.Fatalf("裸 %s 在达梦目标映射为 %q, want BLOB", raw, got)
		}
	}

	bounded := connection.ColumnDefinition{Name: "v", Type: "binary(16)", Nullable: "YES"}
	if got, _, _ := mapMySQLColumnToOracleLike("dameng", bounded); got != "RAW(16)" {
		t.Fatalf("binary(16) 映射为 %q, want RAW(16)", got)
	}
}

// TestAddColumnSurfacesWarnings 补列路径必须回传归一与映射告警。
//
// 类型降级、自增语义丢弃都发生在 buildAddColumnSQLForPair 内部，静默发生
// 会让补列结果无从排查。
func TestAddColumnSurfacesWarnings(t *testing.T) {
	t.Parallel()

	// 无映射类型（bfile）降级为 text 必须告警。
	unknownCol := connection.ColumnDefinition{Name: "c", Type: "bfile", Nullable: "YES"}
	_, unknownWarnings, err := buildAddColumnSQLForPair("oracle", "dameng", "target_table", unknownCol)
	if err != nil {
		t.Fatalf("oracle->dameng 补列报错: %v", err)
	}
	if len(unknownWarnings) == 0 {
		t.Fatalf("bfile 补列降级为 text 必须告警")
	}

	// 自增列补齐时 identity 不补建，必须告警。
	autoCol := connection.ColumnDefinition{Name: "id", Type: "int", Nullable: "NO", Extra: "auto_increment"}
	_, autoWarnings, err := buildAddColumnSQLForPair("oracle", "dameng", "target_table", autoCol)
	if err != nil {
		t.Fatalf("自增列补列报错: %v", err)
	}
	if !strings.Contains(strings.Join(autoWarnings, " "), "自增") {
		t.Fatalf("自增列补齐未提示自增不补建: %v", autoWarnings)
	}

	// MySQL 系目标补列同样丢弃自增语义，统一告警不得遗漏。
	mysqlAuto := connection.ColumnDefinition{Name: "id", Type: "int", Nullable: "NO", Extra: "auto_increment"}
	_, mysqlWarnings, err := buildAddColumnSQLForPair("mysql", "mariadb", "target_table", mysqlAuto)
	if err != nil {
		t.Fatalf("mysql->mariadb 自增列补列报错: %v", err)
	}
	if !strings.Contains(strings.Join(mysqlWarnings, " "), "自增") {
		t.Fatalf("MySQL 系目标自增列补齐未提示: %v", mysqlWarnings)
	}

	// 原生路径（mysql -> kingbase）无告警时不得凭空产生。
	plainCol := connection.ColumnDefinition{Name: "v", Type: "int", Nullable: "YES"}
	_, plainWarnings, err := buildAddColumnSQLForPair("mysql", "kingbase", "target_table", plainCol)
	if err != nil {
		t.Fatalf("mysql->kingbase 补列报错: %v", err)
	}
	if len(plainWarnings) != 0 {
		t.Fatalf("int 补列不应产生告警: %v", plainWarnings)
	}
}

// TestPGIntervalDowngradesToTextWithWarning 锁住 interval 的降级路径。
//
// interval 表达时长（可为 '1 year 2 mons' 这类年月量），TIME 只能表示一日内
// 时刻，按 time 映射会让导入失败或截断；必须降级为 text 并告警。
func TestPGIntervalDowngradesToTextWithWarning(t *testing.T) {
	t.Parallel()

	for _, raw := range []string{"interval", "interval(6)"} {
		col := connection.ColumnDefinition{Name: "span", Type: raw, Nullable: "YES"}
		intermediate, warnings := buildCrossDialectIntermediateColumn("postgres", "mysql", col)
		if intermediate.Type != "text" {
			t.Fatalf("源类型 %s 归一为 %q, want text", raw, intermediate.Type)
		}
		if len(warnings) == 0 {
			t.Fatalf("源类型 %s 降级为 text 后未告警", raw)
		}
		def, _ := buildColumnDefinitionForTargetType("mysql", intermediate)
		if strings.Contains(strings.ToUpper(def), "TIME") {
			t.Fatalf("源类型 %s 在 MySQL 目标生成 %q, 不得残留时刻语义", raw, def)
		}
	}
}

// TestIndexTypeDialectAliasesAreMigratable 锁住索引类型的方言别名等价。
//
// 各方言对普通 B 树索引的叫法不同（Oracle/达梦 NORMAL、SQL Server
// CLUSTERED/NONCLUSTERED），只认 MySQL 的 BTREE 会把新接入源的全部普通
// 索引误判为"不支持类型"。特化类型（BITMAP/GIN 等）仍走不支持分支。
func TestIndexTypeDialectAliasesAreMigratable(t *testing.T) {
	t.Parallel()

	for _, alias := range []string{"", "BTREE", "NORMAL", "CLUSTERED", "NONCLUSTERED"} {
		if !isBTreeEquivalentIndexType(alias) {
			t.Fatalf("普通索引别名 %q 应视为可迁移", alias)
		}
	}
	for _, special := range []string{"BITMAP", "GIN", "FULLTEXT", "HASH", "FUNCTION-BASED NORMAL"} {
		if isBTreeEquivalentIndexType(special) {
			t.Fatalf("特化索引类型 %q 不应视为可自动迁移", special)
		}
	}

	// 端到端：SQL Server 源的 NONCLUSTERED 索引要在目标端生成 CREATE INDEX。
	indexes := []connection.IndexDefinition{
		{Name: "idx_orders_status", ColumnName: "status", NonUnique: 1, SeqInIndex: 1, IndexType: "NONCLUSTERED"},
	}
	postSQL, unsupported, _, created, skipped := buildMySQLSourceIndexPlan(
		"dameng", "target_table", indexes, nil)
	if created != 1 || skipped != 0 || len(unsupported) != 0 {
		t.Fatalf("NONCLUSTERED 索引未自动迁移: created=%d skipped=%d unsupported=%v", created, skipped, unsupported)
	}
	if len(postSQL) != 1 || !strings.Contains(postSQL[0], "CREATE INDEX") {
		t.Fatalf("未生成建索引语句: %v", postSQL)
	}
}

// TestPrimaryKeyImplicitIndexesStripped 锁住主键隐含索引的剥离。
//
// Oracle/达梦/SQL Server 的主键约束在数据字典里是唯一索引，建表语句已含
// PRIMARY KEY，照建会得到与主键同列的冗余唯一索引；非主键唯一索引不受影响。
func TestPrimaryKeyImplicitIndexesStripped(t *testing.T) {
	t.Parallel()

	sourceCols := []connection.ColumnDefinition{
		{Name: "id", Type: "NUMBER(19)", Key: "PRI"},
		{Name: "email", Type: "VARCHAR2(100)"},
	}
	indexes := []connection.IndexDefinition{
		// Oracle 主键约束隐含索引：与主键列集一致且唯一。
		{Name: "PK_ORDERS", ColumnName: "id", NonUnique: 0, SeqInIndex: 1, IndexType: "NORMAL"},
		// 显式唯一索引：必须保留（建表不迁移 UNIQUE 约束）。
		{Name: "UK_ORDERS_EMAIL", ColumnName: "email", NonUnique: 0, SeqInIndex: 1, IndexType: "NORMAL"},
		// 普通二级索引：保留。
		{Name: "IDX_ORDERS_EMAIL", ColumnName: "email", NonUnique: 1, SeqInIndex: 1, IndexType: "NORMAL"},
	}

	kept := stripPrimaryKeyImplicitIndexes(indexes, sourceCols)
	names := make(map[string]int)
	for _, idx := range kept {
		names[strings.TrimSpace(idx.Name)]++
	}
	if names["PK_ORDERS"] != 0 {
		t.Fatalf("主键隐含索引未被剥离: %v", names)
	}
	if names["UK_ORDERS_EMAIL"] == 0 || names["IDX_ORDERS_EMAIL"] == 0 {
		t.Fatalf("非主键索引被误剥离: %v", names)
	}

	// 复合主键同列集的唯一索引同样剥离。
	compositeCols := []connection.ColumnDefinition{
		{Name: "a", Key: "PRI"}, {Name: "b", Key: "PRI"}, {Name: "c"},
	}
	compositeIdx := []connection.IndexDefinition{
		{Name: "PK_T", ColumnName: "a", NonUnique: 0, SeqInIndex: 1, IndexType: "NORMAL"},
		{Name: "PK_T", ColumnName: "b", NonUnique: 0, SeqInIndex: 2, IndexType: "NORMAL"},
		{Name: "UK_T_C", ColumnName: "c", NonUnique: 0, SeqInIndex: 1, IndexType: "NORMAL"},
	}
	compositeKept := stripPrimaryKeyImplicitIndexes(compositeIdx, compositeCols)
	for _, idx := range compositeKept {
		if strings.TrimSpace(idx.Name) == "PK_T" {
			t.Fatalf("复合主键隐含索引未被剥离")
		}
	}

	// 同一列集合但顺序相反的唯一索引不是主键隐含索引，必须保留。
	reversedIdx := []connection.IndexDefinition{
		{Name: "UK_T_REVERSED", ColumnName: "b", NonUnique: 0, SeqInIndex: 1, IndexType: "NORMAL"},
		{Name: "UK_T_REVERSED", ColumnName: "a", NonUnique: 0, SeqInIndex: 2, IndexType: "NORMAL"},
	}
	if got := stripPrimaryKeyImplicitIndexes(reversedIdx, compositeCols); len(got) != len(reversedIdx) {
		t.Fatalf("反序复合唯一索引不应被剥离: %v", got)
	}

	// 无主键时不剥离任何索引。
	noPK := []connection.ColumnDefinition{{Name: "id", Key: ""}}
	if got := stripPrimaryKeyImplicitIndexes(indexes, noPK); len(got) != len(indexes) {
		t.Fatalf("无主键不应剥离索引: %d/%d", len(got), len(indexes))
	}
}

// TestColumnCommentsMigratedPerDialect 锁住列注释的方言处理。
//
// Oracle/达梦 用 COMMENT ON COLUMN 照建；SQL Server/SQLite 无注释语法必须
// 告警；注释含单引号时按 SQL 标准转义成两个，否则非法 DDL 会连累后续
// postSQL 一起中断。
func TestColumnCommentsMigratedPerDialect(t *testing.T) {
	t.Parallel()

	cols := []connection.ColumnDefinition{
		{Name: "name", Type: "varchar(64)", Comment: "用户'姓名"},
		{Name: "email", Type: "varchar(128)"},
	}

	// 达梦目标：生成 COMMENT ON COLUMN，含单引号转义。
	stmts, warnings := buildColumnCommentStatements("dameng", "db.users", cols)
	if len(stmts) != 1 || len(warnings) != 0 {
		t.Fatalf("dameng 注释结果: stmts=%v warnings=%v", stmts, warnings)
	}
	if !strings.Contains(stmts[0], `COMMENT ON COLUMN "db"."users"."name" IS '用户''姓名'`) {
		t.Fatalf("dameng 注释语句: %q", stmts[0])
	}

	// SQL Server 目标：无注释语法，只告警不建语句。
	ssStmts, ssWarnings := buildColumnCommentStatements("sqlserver", "dbo.users", cols)
	if len(ssStmts) != 0 || len(ssWarnings) == 0 {
		t.Fatalf("sqlserver 注释结果: stmts=%v warnings=%v", ssStmts, ssWarnings)
	}

	// 端到端：CreateIndexes=false 时注释语句仍要生成（注释不属于索引）。
	config := SyncConfig{CreateIndexes: false}
	sql, postSQL, _, _, _, _, _, err := buildCrossDialectAutoCreatePlan(
		"oracle", "dameng", config, "db.users", cols, &fakeMigrationDB{}, "", "users")
	if err != nil {
		t.Fatalf("plan error: %v", err)
	}
	if !strings.Contains(sql, "CREATE TABLE") {
		t.Fatalf("建表语句缺失: %q", sql)
	}
	found := false
	for _, stmt := range postSQL {
		if strings.Contains(stmt, "COMMENT ON COLUMN") {
			found = true
		}
	}
	if !found {
		t.Fatalf("CreateIndexes=false 时注释语句缺失: %v", postSQL)
	}
}

// TestCapabilityPromisesAreExecutablePerPair 穷举校验 capability 与执行层的自洽。
//
// 判定函数（supportsAutoCreateMigration / supportsAutoAddColumnsForPair）返回
// true 的每一个组合，执行层必须真的能产出 SQL 而不是落到 default 报错分支；
// 否则 UI 会承诺"将自动建表/补列"而执行期才失败。这是对"判支持"与"能执行"
// 两条路径的全组合一致性断言，任何一条判定或分派新增组合时由本测试兜住。
func TestCapabilityPromisesAreExecutablePerPair(t *testing.T) {
	t.Parallel()

	sources := []string{"mysql", "mariadb", "oceanbase", "diros", "starrocks",
		"postgres", "kingbase", "highgo", "vastbase", "opengauss", "gaussdb", "duckdb",
		"oracle", "dameng", "iris", "sqlserver", "sqlite"}
	targets := []string{"mysql", "mariadb", "oceanbase",
		"postgres", "kingbase", "highgo", "vastbase", "opengauss", "gaussdb", "duckdb",
		"oracle", "dameng", "iris", "sqlserver", "sqlite"}

	// 覆盖所有类型族与易错形态的列集合，让每条分派分支都有机会被踩到。
	cols := []connection.ColumnDefinition{
		{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI", Extra: "auto_increment"},
		{Name: "name", Type: "varchar(64)", Nullable: "YES"},
		{Name: "amount", Type: "numeric(10,2)", Nullable: "YES"},
		{Name: "ts", Type: "datetime", Nullable: "YES"},
		{Name: "payload", Type: "blob", Nullable: "YES"},
	}
	indexes := []connection.IndexDefinition{
		{Name: "IDX_NAME", ColumnName: "name", NonUnique: 1, SeqInIndex: 1, IndexType: "NORMAL"},
	}

	checkedCreate := 0
	checkedAdd := 0
	for _, source := range sources {
		for _, target := range targets {
			if !supportsAutoCreateMigration(source, target) {
				continue
			}
			checkedCreate++
			config := SyncConfig{
				SourceConfig: connection.ConnectionConfig{Type: source},
				TargetConfig: connection.ConnectionConfig{Type: target},
			}
			_, _, _, _, _, _, _, err := buildLegacyAutoCreateTablePlan(target, config, "t",
				cols, &fakeMigrationDB{indexes: map[string][]connection.IndexDefinition{".t": indexes}},
				"", "t")
			if err != nil {
				t.Fatalf("自动建表判定与执行不一致：source=%s target=%s 判定支持但构建失败: %v",
					source, target, err)
			}

			if !supportsAutoAddColumnsForPair(source, target) {
				continue
			}
			checkedAdd++
			for _, col := range cols {
				if _, _, err := buildAddColumnSQLForPair(source, target, "t", col); err != nil {
					t.Fatalf("自动补列判定与执行不一致：source=%s target=%s 字段 %s 判定支持但生成失败: %v",
						source, target, col.Name, err)
				}
			}
		}
	}
	// 防空转：本测试的前提是确有组合被判支持，若判定层退化为全 false，
	// 循环体一次都不执行，测试会静默通过而失去意义。
	if checkedCreate < 100 {
		t.Fatalf("自动建表组合数异常偏少: %d（判定层可能退化）", checkedCreate)
	}
	if checkedAdd < 100 {
		t.Fatalf("自动补列组合数异常偏少: %d（判定层可能退化）", checkedAdd)
	}
}

// TestPrefixUniqueIndexNotStrippedAsPrimaryKey 锁住前缀唯一索引的保留。
//
// PRIMARY KEY(code) 配合 UNIQUE KEY uk_code_prefix(code(10)) 时，后者与主键
// 列集相同但带前缀长度：它约束的是前 10 字符唯一性，与主键整列唯一语义不同，
// 不得被主键隐含索引剥离逻辑误删。
func TestPrefixUniqueIndexNotStrippedAsPrimaryKey(t *testing.T) {
	t.Parallel()

	sourceCols := []connection.ColumnDefinition{
		{Name: "code", Type: "varchar(64)", Key: "PRI"},
	}
	indexes := []connection.IndexDefinition{
		{Name: "uk_code_prefix", ColumnName: "code", NonUnique: 0, SubPart: 10, SeqInIndex: 1, IndexType: "BTREE"},
	}
	kept := stripPrimaryKeyImplicitIndexes(indexes, sourceCols)
	if len(kept) != 1 {
		t.Fatalf("前缀唯一索引被误剥离: %v", kept)
	}

	// 对照组：无前缀的同列唯一索引（主键隐含）仍要剥离。
	full := []connection.IndexDefinition{
		{Name: "uk_code_full", ColumnName: "code", NonUnique: 0, SubPart: 0, SeqInIndex: 1, IndexType: "BTREE"},
	}
	if keptFull := stripPrimaryKeyImplicitIndexes(full, sourceCols); len(keptFull) != 0 {
		t.Fatalf("主键隐含索引未被剥离: %v", keptFull)
	}
}
