package sync

import (
	"strings"
	"testing"

	"GoNavi-Wails/internal/connection"
)

// 一次性迁移目标表不存在时：legacy 路径必须按目标方言生成可执行的
// CREATE TABLE，且 capability/preflight 判定与 planner 实际行为一致
// （此前 mysql->dameng 等目标 preflight 直接 blocker，UI 却提示会创建）。
func TestLegacyAutoCreateDamengPlan(t *testing.T) {
	t.Parallel()

	config := SyncConfig{
		SourceConfig:        connection.ConnectionConfig{Type: "mysql"},
		TargetConfig:        connection.ConnectionConfig{Type: "dameng"},
		TargetTableStrategy: "smart",
		SourceDatabase:      "db",
		TargetDatabase:      "db",
	}
	sourceDB := &fakeMigrationDB{columns: map[string][]connection.ColumnDefinition{
		"db.orders": {
			{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI", Extra: "auto_increment"},
			{Name: "name", Type: "varchar(64)", Nullable: "YES"},
			{Name: "created_at", Type: "datetime", Nullable: "NO", Default: stringPtr("CURRENT_TIMESTAMP")},
		},
	}}
	targetDB := &fakeMigrationDB{}

	plan, _, _, err := buildSchemaMigrationPlan(config, "orders", sourceDB, targetDB)
	if err != nil {
		t.Fatalf("plan error: %v", err)
	}
	if !plan.AutoCreate || plan.CreateTableSQL == "" {
		t.Fatalf("expected auto-create plan, got autoCreate=%v sql=%q action=%q warnings=%v",
			plan.AutoCreate, plan.CreateTableSQL, plan.PlannedAction, plan.Warnings)
	}
	for _, fragment := range []string{
		`CREATE TABLE "db"."orders"`,
		// 达梦原生模式使用 IDENTITY(seed, increment)，不接受 Oracle 的
		// GENERATED BY DEFAULT AS IDENTITY。
		// 达梦的 IDENTITY 只接受整数类型，NUMBER(19) IDENTITY 会被真实
		// 实例以 Error -2713 拒绝。
		`"id" BIGINT IDENTITY(1,1) NOT NULL`,
		`"name" VARCHAR(64)`,
		// MySQL datetime 含时分秒，Oracle 系 DATE 只有日分量，必须映射 TIMESTAMP。
		`"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL`,
		`PRIMARY KEY ("id")`,
	} {
		if !strings.Contains(plan.CreateTableSQL, fragment) {
			t.Fatalf("dameng DDL missing %q:\n%s", fragment, plan.CreateTableSQL)
		}
	}
}

func TestIdentityObjectRenameAutoCreatesRequestedDamengTable(t *testing.T) {
	t.Parallel()

	config := SyncConfig{
		SourceConfig:        connection.ConnectionConfig{Type: "mysql"},
		TargetConfig:        connection.ConnectionConfig{Type: "dameng"},
		SourceDatabase:      "source_db",
		TargetDatabase:      "target_db",
		TargetTableStrategy: "smart",
		AutoAddColumns:      true,
		Tables:              []string{"test"},
		Content:             "both",
		Mappings: []SyncObjectMapping{{
			Source:     SyncObjectRef{Name: "test"},
			Target:     SyncObjectRef{Name: "test1"},
			KeyColumns: []string{"id"},
		}},
	}
	if err := validateSyncMappings(config); err != nil {
		t.Fatalf("identity object rename should be valid for schema migration: %v", err)
	}
	sourceDB := &fakeMigrationDB{columns: map[string][]connection.ColumnDefinition{
		"source_db.test": {{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI"}},
	}}
	plan, _, _, err := buildSchemaMigrationPlan(config, "test", sourceDB, &fakeMigrationDB{})
	if err != nil {
		t.Fatalf("buildSchemaMigrationPlan returned error: %v", err)
	}
	if !plan.AutoCreate || plan.TargetTable != "test1" || !strings.Contains(plan.CreateTableSQL, `CREATE TABLE "target_db"."test1"`) {
		t.Fatalf("identity rename must create target test1, got %+v", plan)
	}
}

func TestIdentityObjectMappingUsesTargetSchemaForQualifiedSourceTable(t *testing.T) {
	t.Parallel()

	config := SyncConfig{
		SourceConfig:        connection.ConnectionConfig{Type: "mysql"},
		TargetConfig:        connection.ConnectionConfig{Type: "kingbase"},
		SourceDatabase:      "source_db",
		TargetDatabase:      "target_db",
		TargetSchema:        "sysmac",
		TargetTableStrategy: "smart",
		AutoAddColumns:      true,
		Tables:              []string{"WLJY_WJDP.test1"},
		Content:             "both",
		Mappings: []SyncObjectMapping{{
			Source:     SyncObjectRef{Schema: "WLJY_WJDP", Name: "test1"},
			Target:     SyncObjectRef{Schema: "sysmac", Name: "test"},
			KeyColumns: []string{"id"},
		}},
	}
	sourceDB := &fakeMigrationDB{columns: map[string][]connection.ColumnDefinition{
		"WLJY_WJDP.test1": {{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI"}},
	}}

	plan, _, _, err := buildSchemaMigrationPlan(config, "WLJY_WJDP.test1", sourceDB, &fakeMigrationDB{})
	if err != nil {
		t.Fatalf("buildSchemaMigrationPlan returned error: %v", err)
	}
	if plan.TargetSchema != "sysmac" || plan.TargetTable != "test" {
		t.Fatalf("target object = %q.%q, want sysmac.test", plan.TargetSchema, plan.TargetTable)
	}
	if plan.TargetQueryTable != "sysmac.test" {
		t.Fatalf("target query table = %q, want sysmac.test", plan.TargetQueryTable)
	}
	if !strings.Contains(plan.CreateTableSQL, "CREATE TABLE sysmac.test") {
		t.Fatalf("create table SQL must use target object, got:\n%s", plan.CreateTableSQL)
	}
}

func TestLegacyAutoCreateCapabilityMatchesPlanner(t *testing.T) {
	t.Parallel()

	// capability 与真实 planner 必须一致：任何一个支持自动建表，另一个也要支持。
	for _, target := range []string{"dameng", "oracle", "iris", "sqlserver", "sqlite", "kingbase", "postgres", "mysql", "clickhouse"} {
		capability := ResolveMigrationCapability(
			connection.ConnectionConfig{Type: "mysql"},
			connection.ConnectionConfig{Type: target},
		)
		config := SyncConfig{
			SourceConfig:        connection.ConnectionConfig{Type: "mysql"},
			TargetConfig:        connection.ConnectionConfig{Type: target},
			TargetTableStrategy: "smart",
			SourceDatabase:      "db",
			TargetDatabase:      "db",
		}
		sourceDB := &fakeMigrationDB{columns: map[string][]connection.ColumnDefinition{
			"db.orders": {{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI"}},
		}}
		plan, _, _, err := buildSchemaMigrationPlan(config, "orders", sourceDB, &fakeMigrationDB{})
		if err != nil {
			t.Fatalf("target=%s plan error: %v", target, err)
		}
		if capability.SupportsAutoCreate != plan.AutoCreate {
			t.Fatalf("target=%s capability.supportsAutoCreate=%v but plan.AutoCreate=%v",
				target, capability.SupportsAutoCreate, plan.AutoCreate)
		}
		if capability.SupportsAutoCreate && plan.CreateTableSQL == "" {
			t.Fatalf("target=%s supportsAutoCreate but generated no CREATE TABLE", target)
		}
	}
}

func TestLegacyAutoCreateSQLServerPlan(t *testing.T) {
	t.Parallel()

	config := SyncConfig{
		SourceConfig:        connection.ConnectionConfig{Type: "mysql"},
		TargetConfig:        connection.ConnectionConfig{Type: "sqlserver"},
		TargetTableStrategy: "smart",
		SourceDatabase:      "db",
		TargetDatabase:      "db",
	}
	sourceDB := &fakeMigrationDB{columns: map[string][]connection.ColumnDefinition{
		"db.orders": {
			{Name: "id", Type: "int", Nullable: "NO", Key: "PRI", Extra: "auto_increment"},
			{Name: "title", Type: "varchar(5000)", Nullable: "YES"},
			{Name: "enabled", Type: "tinyint(1)", Nullable: "YES", Default: stringPtr("1")},
			{Name: "created_at", Type: "datetime", Nullable: "NO"},
		},
	}}
	plan, _, _, err := buildSchemaMigrationPlan(config, "orders", sourceDB, &fakeMigrationDB{})
	if err != nil {
		t.Fatalf("plan error: %v", err)
	}
	for _, fragment := range []string{
		// SQL Server 的 IDENTITY 列拒绝显式插入，自动建表建普通数字列保数据导入。
		`[id] INT NOT NULL`,
		// varchar(5000) 超 4000 上限降级 NVARCHAR(MAX)，并有 warning。
		`[title] NVARCHAR(MAX)`,
		`[enabled] BIT DEFAULT 1`,
		// datetime 不得被 date 前缀分支吞掉变成 DATE。
		`[created_at] DATETIME2 NOT NULL`,
	} {
		if !strings.Contains(plan.CreateTableSQL, fragment) {
			t.Fatalf("sqlserver DDL missing %q:\n%s", fragment, plan.CreateTableSQL)
		}
	}
	if strings.Contains(strings.ToUpper(plan.CreateTableSQL), "IDENTITY") {
		t.Fatalf("sqlserver DDL must not emit IDENTITY (explicit inserts would fail):\n%s", plan.CreateTableSQL)
	}
	joined := strings.Join(plan.Warnings, "\n")
	if !strings.Contains(joined, "IDENTITY 列不允许显式插入") {
		t.Fatalf("丢弃自增语义后未告警: %v", plan.Warnings)
	}
	if len(plan.Warnings) == 0 {
		t.Fatalf("expected varchar-overflow warning, got none")
	}
}

func TestLegacyAutoCreateSQLitePlan(t *testing.T) {
	t.Parallel()

	config := SyncConfig{
		SourceConfig:        connection.ConnectionConfig{Type: "mysql"},
		TargetConfig:        connection.ConnectionConfig{Type: "sqlite"},
		TargetTableStrategy: "smart",
		SourceDatabase:      "db",
		TargetDatabase:      "db",
	}
	sourceDB := &fakeMigrationDB{columns: map[string][]connection.ColumnDefinition{
		"db.orders": {
			{Name: "id", Type: "int", Nullable: "NO", Key: "PRI", Extra: "auto_increment"},
			{Name: "name", Type: "varchar(64)", Nullable: "NO"},
		},
	}}
	plan, _, _, err := buildSchemaMigrationPlan(config, "orders", sourceDB, &fakeMigrationDB{})
	if err != nil {
		t.Fatalf("plan error: %v", err)
	}
	// AUTOINCREMENT 已含 PRIMARY KEY，不得再追加重复约束。
	if !strings.Contains(plan.CreateTableSQL, `"id" INTEGER PRIMARY KEY AUTOINCREMENT`) {
		t.Fatalf("sqlite DDL missing autoincrement pk:\n%s", plan.CreateTableSQL)
	}
	if strings.Count(plan.CreateTableSQL, "PRIMARY KEY") != 1 {
		t.Fatalf("sqlite DDL declares PRIMARY KEY more than once:\n%s", plan.CreateTableSQL)
	}
	if !strings.Contains(plan.CreateTableSQL, `"name" TEXT NOT NULL`) {
		t.Fatalf("sqlite DDL missing NOT NULL:\n%s", plan.CreateTableSQL)
	}
}

func TestLegacyAutoCreateRespectsExistingOnly(t *testing.T) {
	t.Parallel()

	config := SyncConfig{
		SourceConfig:        connection.ConnectionConfig{Type: "mysql"},
		TargetConfig:        connection.ConnectionConfig{Type: "dameng"},
		TargetTableStrategy: "existing_only",
		SourceDatabase:      "db",
		TargetDatabase:      "db",
	}
	sourceDB := &fakeMigrationDB{columns: map[string][]connection.ColumnDefinition{
		"db.orders": {{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI"}},
	}}
	plan, _, _, err := buildSchemaMigrationPlan(config, "orders", sourceDB, &fakeMigrationDB{})
	if err != nil {
		t.Fatalf("plan error: %v", err)
	}
	if plan.AutoCreate || plan.CreateTableSQL != "" {
		t.Fatalf("existing_only must not auto-create, got autoCreate=%v sql=%q", plan.AutoCreate, plan.CreateTableSQL)
	}
}

func TestMapMySQLColumnToOracleLikeTypes(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name      string
		col       connection.ColumnDefinition
		wantType  string
		wantIdent bool
	}{
		{"tinyint auto_increment", connection.ColumnDefinition{Name: "id", Type: "tinyint", Extra: "auto_increment"}, "SMALLINT", true},
		{"smallint auto_increment", connection.ColumnDefinition{Name: "id", Type: "smallint", Extra: "auto_increment"}, "SMALLINT", true},
		{"smallint unsigned auto_increment", connection.ColumnDefinition{Name: "id", Type: "smallint unsigned", Extra: "auto_increment"}, "INTEGER", true},
		{"int auto_increment", connection.ColumnDefinition{Name: "id", Type: "int", Extra: "auto_increment"}, "INTEGER", true},
		{"int unsigned auto_increment", connection.ColumnDefinition{Name: "id", Type: "int unsigned", Extra: "auto_increment"}, "BIGINT", true},
		{"bigint auto_increment", connection.ColumnDefinition{Name: "id", Type: "bigint", Extra: "auto_increment"}, "BIGINT", true},
		{"int unsigned", connection.ColumnDefinition{Name: "v", Type: "int unsigned"}, "NUMBER(10)", false},
		{"tinyint(1)", connection.ColumnDefinition{Name: "v", Type: "tinyint(1)"}, "NUMBER(1)", false},
		{"decimal", connection.ColumnDefinition{Name: "v", Type: "decimal(10,2)"}, "NUMBER(10,2)", false},
		{"text", connection.ColumnDefinition{Name: "v", Type: "text"}, "CLOB", false},
		{"json", connection.ColumnDefinition{Name: "v", Type: "json"}, "CLOB", false},
		{"blob", connection.ColumnDefinition{Name: "v", Type: "blob"}, "BLOB", false},
		{"enum", connection.ColumnDefinition{Name: "v", Type: "enum('a','b')"}, "VARCHAR(255)", false},
		{"date", connection.ColumnDefinition{Name: "v", Type: "date"}, "DATE", false},
		{"time", connection.ColumnDefinition{Name: "v", Type: "time"}, "TIMESTAMP", false},
	}
	for _, tc := range cases {
		gotType, gotIdent, warnings := mapMySQLColumnToOracleLike("dameng", tc.col)
		if gotType != tc.wantType {
			t.Errorf("%s: type = %q, want %q (warnings=%v)", tc.name, gotType, tc.wantType, warnings)
		}
		if gotIdent != tc.wantIdent {
			t.Errorf("%s: identity = %v, want %v", tc.name, gotIdent, tc.wantIdent)
		}
	}

	unsignedBigint := connection.ColumnDefinition{Name: "id", Type: "bigint unsigned", Extra: "auto_increment"}
	gotType, gotIdent, warnings := mapMySQLColumnToOracleLike("dameng", unsignedBigint)
	if gotType != "NUMBER(20)" || gotIdent {
		t.Fatalf("bigint unsigned auto_increment = (%q, identity=%v), want NUMBER(20) without identity", gotType, gotIdent)
	}
	if !strings.Contains(strings.Join(warnings, "\n"), "不迁移自增语义") {
		t.Fatalf("bigint unsigned auto_increment must warn before dropping identity: %v", warnings)
	}

	sqliteType, sqliteIdentity, sqliteWarnings := mapMySQLColumnToSQLite(unsignedBigint)
	if sqliteType != "NUMERIC" || sqliteIdentity {
		t.Fatalf("bigint unsigned auto_increment -> sqlite = (%q, identity=%v), want NUMERIC without autoincrement", sqliteType, sqliteIdentity)
	}
	if !strings.Contains(strings.Join(sqliteWarnings, "\n"), "无法覆盖其完整值域") {
		t.Fatalf("sqlite bigint unsigned auto_increment must warn about range loss: %v", sqliteWarnings)
	}

	// varchar 超 4000 上限降级 CLOB。
	overflowCol := connection.ColumnDefinition{Name: "big", Type: "varchar(8000)"}
	gotType, _, warnings = mapMySQLColumnToOracleLike("dameng", overflowCol)
	if gotType != "CLOB" {
		t.Fatalf("varchar(8000) should map to CLOB, got %q", gotType)
	}
	if len(warnings) == 0 {
		t.Fatalf("varchar(8000) should produce a warning")
	}
}

// 自增 tinyint(1) 的 (1) 是 MySQL 显示宽度，不是布尔约束。只有普通
// tinyint(1) 才能按 boolean 映射；自增列必须保留整数值域和生成语义。
func TestMySQLAutoIncrementColumnsDoNotUseBooleanFallback(t *testing.T) {
	t.Parallel()

	tinyAuto := connection.ColumnDefinition{Name: "id", Type: "tinyint(1)", Extra: "auto_increment"}
	pgType, pgIdentity, _ := mapMySQLColumnToKingbase(tinyAuto)
	if pgType != "smallint" || !pgIdentity {
		t.Fatalf("mysql tinyint(1) auto_increment -> pglike = (%q, identity=%v), want smallint identity", pgType, pgIdentity)
	}

	sqliteType, sqliteIdentity, _ := mapMySQLColumnToSQLite(tinyAuto)
	if sqliteType != "INTEGER" || !sqliteIdentity {
		t.Fatalf("mysql tinyint(1) auto_increment -> sqlite = (%q, identity=%v), want INTEGER autoincrement", sqliteType, sqliteIdentity)
	}

	oracleType, oracleIdentity, _ := mapMySQLColumnToOracleLike("oracle", tinyAuto)
	if oracleType != "NUMBER(5)" || !oracleIdentity {
		t.Fatalf("mysql tinyint(1) auto_increment -> oracle = (%q, identity=%v), want NUMBER(5) identity", oracleType, oracleIdentity)
	}

	for _, sourceType := range []string{"tinyint unsigned", "smallint unsigned", "int unsigned", "bigint unsigned"} {
		mappedType, useIdentity, warnings := mapMySQLColumnToOracleLike("oracle", connection.ColumnDefinition{
			Name: "id", Type: sourceType, Extra: "auto_increment",
		})
		if !useIdentity {
			t.Fatalf("mysql %s auto_increment -> oracle = %q without identity, warnings=%v", sourceType, mappedType, warnings)
		}
	}
}
