package sync

import (
	"context"
	"reflect"
	"strings"
	"testing"

	"GoNavi-Wails/internal/connection"
)

type fakeMigrationDB struct {
	columns       map[string][]connection.ColumnDefinition
	indexes       map[string][]connection.IndexDefinition
	triggers      map[string][]connection.TriggerDefinition
	tableComments map[string]string
	tables        map[string][]string
	queryData     map[string][]map[string]interface{}
	queryCols     map[string][]string
	queryLog      []string
}

func (f *fakeMigrationDB) Connect(config connection.ConnectionConfig) error { return nil }
func (f *fakeMigrationDB) Close() error                                     { return nil }
func (f *fakeMigrationDB) Ping() error                                      { return nil }
func (f *fakeMigrationDB) Query(query string) ([]map[string]interface{}, []string, error) {
	f.queryLog = append(f.queryLog, query)
	if rows, ok := f.queryData[query]; ok {
		return rows, f.queryCols[query], nil
	}
	return nil, nil, nil
}
func (f *fakeMigrationDB) Exec(query string) (int64, error) { return 0, nil }
func (f *fakeMigrationDB) GetDatabases() ([]string, error)  { return nil, nil }
func (f *fakeMigrationDB) GetTables(dbName string) ([]string, error) {
	if rows, ok := f.tables[dbName]; ok {
		return rows, nil
	}
	return nil, nil
}
func (f *fakeMigrationDB) GetCreateStatement(dbName, tableName string) (string, error) {
	return "", nil
}
func (f *fakeMigrationDB) GetColumns(dbName, tableName string) ([]connection.ColumnDefinition, error) {
	key := dbName + "." + tableName
	if rows, ok := f.columns[key]; ok {
		return rows, nil
	}
	return []connection.ColumnDefinition{}, nil
}
func (f *fakeMigrationDB) GetAllColumns(dbName string) ([]connection.ColumnDefinitionWithTable, error) {
	return nil, nil
}
func (f *fakeMigrationDB) GetIndexes(dbName, tableName string) ([]connection.IndexDefinition, error) {
	key := dbName + "." + tableName
	if rows, ok := f.indexes[key]; ok {
		return rows, nil
	}
	return nil, nil
}
func (f *fakeMigrationDB) GetForeignKeys(dbName, tableName string) ([]connection.ForeignKeyDefinition, error) {
	return nil, nil
}
func (f *fakeMigrationDB) GetTriggers(dbName, tableName string) ([]connection.TriggerDefinition, error) {
	key := dbName + "." + tableName
	if rows, ok := f.triggers[key]; ok {
		return rows, nil
	}
	return nil, nil
}
func (f *fakeMigrationDB) GetTableComment(dbName, tableName string) (string, error) {
	return f.tableComments[dbName+"."+tableName], nil
}
func (f *fakeMigrationDB) QueryContext(ctx context.Context, query string) ([]map[string]interface{}, []string, error) {
	return f.Query(query)
}
func (f *fakeMigrationDB) ExecContext(ctx context.Context, query string) (int64, error) {
	return 0, nil
}

func TestBuildMySQLToKingbaseColumnDefinition_AutoIncrementAndBoolean(t *testing.T) {
	t.Parallel()

	def, warnings := buildMySQLToKingbaseColumnDefinition(connection.ColumnDefinition{
		Name:     "id",
		Type:     "int unsigned",
		Nullable: "NO",
		Extra:    "auto_increment",
	})
	if !strings.Contains(def, "bigint") || !strings.Contains(def, "GENERATED BY DEFAULT AS IDENTITY") || !strings.Contains(def, "NOT NULL") {
		t.Fatalf("unexpected definition: %s", def)
	}
	if len(warnings) != 0 {
		t.Fatalf("unexpected warnings: %v", warnings)
	}

	def, warnings = buildMySQLToKingbaseColumnDefinition(connection.ColumnDefinition{
		Name:     "enabled",
		Type:     "tinyint(1)",
		Nullable: "YES",
		Default:  stringPtr("1"),
	})
	if !strings.Contains(def, "boolean") || !strings.Contains(def, "DEFAULT TRUE") {
		t.Fatalf("unexpected boolean definition: %s", def)
	}
	if len(warnings) != 0 {
		t.Fatalf("unexpected warnings for boolean: %v", warnings)
	}
}

func TestBuildMySQLToKingbaseCreateTablePlan_GeneratesAndSkipsIndexes(t *testing.T) {
	t.Parallel()

	sourceDB := &fakeMigrationDB{
		indexes: map[string][]connection.IndexDefinition{
			"shop.orders": {
				{Name: "PRIMARY", ColumnName: "id", NonUnique: 0, SeqInIndex: 1, IndexType: "BTREE"},
				{Name: "idx_user_status", ColumnName: "user_id", NonUnique: 1, SeqInIndex: 1, IndexType: "BTREE"},
				{Name: "idx_user_status", ColumnName: "status", NonUnique: 1, SeqInIndex: 2, IndexType: "BTREE"},
				{Name: "idx_name_prefix", ColumnName: "name", NonUnique: 1, SeqInIndex: 1, IndexType: "BTREE", SubPart: 12},
				{Name: "idx_fulltext_note", ColumnName: "note", NonUnique: 1, SeqInIndex: 1, IndexType: "FULLTEXT"},
			},
		},
	}
	cols := []connection.ColumnDefinition{
		{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI", Extra: "auto_increment"},
		{Name: "user_id", Type: "bigint", Nullable: "NO"},
		{Name: "status", Type: "varchar(32)", Nullable: "YES"},
		{Name: "name", Type: "varchar(128)", Nullable: "YES"},
		{Name: "note", Type: "text", Nullable: "YES"},
	}
	cfg := SyncConfig{CreateIndexes: true}
	createSQL, postSQL, warnings, unsupported, unmigrated, idxCreate, idxSkip, err := buildMySQLToKingbaseCreateTablePlan(cfg, "public.orders", cols, sourceDB, "shop", "orders")
	if err != nil {
		t.Fatalf("buildMySQLToKingbaseCreateTablePlan returned error: %v", err)
	}
	if !strings.Contains(createSQL, `CREATE TABLE public.orders`) {
		t.Fatalf("unexpected create SQL: %s", createSQL)
	}
	if !strings.Contains(createSQL, `PRIMARY KEY (id)`) {
		t.Fatalf("create SQL missing primary key: %s", createSQL)
	}
	if idxCreate != 1 || idxSkip != 2 {
		t.Fatalf("unexpected index summary: create=%d skip=%d", idxCreate, idxSkip)
	}
	if len(postSQL) != 1 || !strings.Contains(postSQL[0], `CREATE INDEX idx_user_status`) {
		t.Fatalf("unexpected post SQL: %v", postSQL)
	}
	if len(warnings) != 0 {
		t.Fatalf("unexpected warnings: %v", warnings)
	}
	wantUnsupported := []string{
		"索引 idx_name_prefix 使用前缀长度，当前目标方言暂不支持等价自动迁移",
		"索引 idx_fulltext_note 类型=FULLTEXT，当前暂不支持等价自动迁移",
	}
	if !reflect.DeepEqual(unsupported, wantUnsupported) {
		t.Fatalf("unexpected unsupported objects: got=%v want=%v", unsupported, wantUnsupported)
	}
	wantUnmigrated := []UnmigratedIndex{
		{
			Name:       "idx_name_prefix",
			Columns:    []IndexMigrationColumn{{Name: "name", PrefixLength: 12}},
			Unique:     false,
			IndexType:  "BTREE",
			ReasonCode: "prefix_index_requires_review",
			Reason:     wantUnsupported[0],
			RemediationStatements: []string{
				"CREATE INDEX idx_name_prefix ON public.orders (left(CAST(name AS text), 12))",
			},
		},
		{
			Name:       "idx_fulltext_note",
			Columns:    []IndexMigrationColumn{{Name: "note"}},
			Unique:     false,
			IndexType:  "FULLTEXT",
			ReasonCode: "fulltext_requires_review",
			Reason:     wantUnsupported[1],
			RemediationStatements: []string{
				"CREATE INDEX idx_fulltext_note ON public.orders USING GIN (to_tsvector('simple', coalesce(CAST(note AS text), '')))",
			},
		},
	}
	if !reflect.DeepEqual(unmigrated, wantUnmigrated) {
		t.Fatalf("unexpected unmigrated indexes: got=%+v want=%+v", unmigrated, wantUnmigrated)
	}
}

func TestBuildSchemaMigrationPlan_AutoCreateWhenTargetMissing(t *testing.T) {
	t.Parallel()

	sourceDB := &fakeMigrationDB{
		columns: map[string][]connection.ColumnDefinition{
			"shop.orders": {
				{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI", Extra: "auto_increment"},
				{Name: "name", Type: "varchar(128)", Nullable: "YES"},
			},
		},
		indexes: map[string][]connection.IndexDefinition{},
	}
	targetDB := &fakeMigrationDB{columns: map[string][]connection.ColumnDefinition{}}
	cfg := SyncConfig{
		SourceConfig:        connection.ConnectionConfig{Type: "mysql", Database: "shop"},
		TargetConfig:        connection.ConnectionConfig{Type: "kingbase", Database: "demo"},
		TargetTableStrategy: "smart",
		CreateIndexes:       true,
	}
	plan, sourceCols, targetCols, err := buildSchemaMigrationPlan(cfg, "orders", sourceDB, targetDB)
	if err != nil {
		t.Fatalf("buildSchemaMigrationPlan returned error: %v", err)
	}
	if len(sourceCols) != 2 || len(targetCols) != 0 {
		t.Fatalf("unexpected columns lengths: source=%d target=%d", len(sourceCols), len(targetCols))
	}
	if plan.TargetTableExists {
		t.Fatalf("expected target table missing")
	}
	if !plan.AutoCreate {
		t.Fatalf("expected auto create enabled")
	}
	if !strings.Contains(plan.PlannedAction, "自动建表") {
		t.Fatalf("unexpected planned action: %s", plan.PlannedAction)
	}
	if !strings.Contains(plan.CreateTableSQL, `CREATE TABLE public.orders`) {
		t.Fatalf("unexpected create table SQL: %s", plan.CreateTableSQL)
	}
}

func stringPtr(v string) *string { return &v }

func TestBuildPGLikeToMySQLCreateTablePlan_GeneratesMySQLDDL(t *testing.T) {
	t.Parallel()

	sourceDB := &fakeMigrationDB{
		indexes: map[string][]connection.IndexDefinition{
			"public.users": {
				{Name: "users_email_key", ColumnName: "email", NonUnique: 0, SeqInIndex: 1, IndexType: "BTREE"},
				{Name: "idx_users_name", ColumnName: "name", NonUnique: 1, SeqInIndex: 1, IndexType: "BTREE"},
			},
		},
	}
	cols := []connection.ColumnDefinition{
		{Name: "id", Type: "integer", Nullable: "NO", Key: "PRI", Extra: "auto_increment"},
		{Name: "email", Type: "character varying(120)", Nullable: "NO"},
		{Name: "name", Type: "text", Nullable: "YES"},
		{Name: "profile", Type: "jsonb", Nullable: "YES"},
	}
	cfg := SyncConfig{CreateIndexes: true}
	createSQL, postSQL, warnings, unsupported, idxCreate, idxSkip, err := buildPGLikeToMySQLCreateTablePlan(cfg, "app.users", cols, sourceDB, "public", "users")
	if err != nil {
		t.Fatalf("buildPGLikeToMySQLCreateTablePlan returned error: %v", err)
	}
	if !strings.Contains(createSQL, "CREATE TABLE `app`.`users`") {
		t.Fatalf("unexpected create SQL: %s", createSQL)
	}
	if !strings.Contains(createSQL, "`id` int AUTO_INCREMENT NOT NULL") {
		t.Fatalf("unexpected id definition: %s", createSQL)
	}
	if !strings.Contains(createSQL, "`profile` json") {
		t.Fatalf("unexpected json definition: %s", createSQL)
	}
	if idxCreate != 2 || idxSkip != 0 {
		t.Fatalf("unexpected index summary: create=%d skip=%d", idxCreate, idxSkip)
	}
	if len(postSQL) != 2 {
		t.Fatalf("unexpected post sql length: %v", postSQL)
	}
	if len(warnings) != 0 {
		t.Fatalf("unexpected warnings: %v", warnings)
	}
	if len(unsupported) != 0 {
		t.Fatalf("unexpected unsupported: %v", unsupported)
	}
}

func TestBuildPGLikeToMySQLPlan_AutoCreateWhenTargetMissing(t *testing.T) {
	t.Parallel()

	sourceDB := &fakeMigrationDB{
		columns: map[string][]connection.ColumnDefinition{
			"public.orders": {
				{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI", Extra: "auto_increment"},
				{Name: "amount", Type: "numeric(10,2)", Nullable: "NO"},
			},
		},
		indexes: map[string][]connection.IndexDefinition{},
	}
	targetDB := &fakeMigrationDB{columns: map[string][]connection.ColumnDefinition{}}
	cfg := SyncConfig{
		SourceConfig:        connection.ConnectionConfig{Type: "kingbase", Database: "public"},
		TargetConfig:        connection.ConnectionConfig{Type: "mysql", Database: "app"},
		TargetTableStrategy: "smart",
		CreateIndexes:       true,
	}
	plan, sourceCols, targetCols, err := buildPGLikeToMySQLPlan(cfg, "orders", sourceDB, targetDB)
	if err != nil {
		t.Fatalf("buildPGLikeToMySQLPlan returned error: %v", err)
	}
	if len(sourceCols) != 2 || len(targetCols) != 0 {
		t.Fatalf("unexpected columns lengths: source=%d target=%d", len(sourceCols), len(targetCols))
	}
	if plan.TargetTableExists {
		t.Fatalf("expected target table missing")
	}
	if !plan.AutoCreate {
		t.Fatalf("expected auto create enabled")
	}
	if !strings.Contains(plan.CreateTableSQL, "CREATE TABLE `app`.`orders`") {
		t.Fatalf("unexpected create table SQL: %s", plan.CreateTableSQL)
	}
}

func TestBuildSchemaMigrationPlan_MySQLToMySQLAddsMissingColumnsForExistingTarget(t *testing.T) {
	t.Parallel()

	sourceDB := &fakeMigrationDB{
		columns: map[string][]connection.ColumnDefinition{
			"shop.users": {
				{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI"},
				{Name: "name", Type: "varchar(128)", Nullable: "YES"},
				{Name: "aaaa", Type: "varchar(255)", Nullable: "YES"},
			},
		},
	}
	targetDB := &fakeMigrationDB{
		columns: map[string][]connection.ColumnDefinition{
			"app.users": {
				{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI"},
				{Name: "name", Type: "varchar(128)", Nullable: "YES"},
			},
		},
	}
	cfg := SyncConfig{
		SourceConfig:        connection.ConnectionConfig{Type: "mysql", Database: "shop"},
		TargetConfig:        connection.ConnectionConfig{Type: "mysql", Database: "app"},
		TargetTableStrategy: "existing_only",
		AutoAddColumns:      true,
	}

	plan, sourceCols, targetCols, err := buildSchemaMigrationPlan(cfg, "users", sourceDB, targetDB)
	if err != nil {
		t.Fatalf("buildSchemaMigrationPlan returned error: %v", err)
	}
	if len(sourceCols) != 3 || len(targetCols) != 2 {
		t.Fatalf("unexpected source/target columns: %d / %d", len(sourceCols), len(targetCols))
	}
	if !plan.TargetTableExists {
		t.Fatalf("expected target table to exist")
	}
	if len(plan.PreDataSQL) != 1 {
		t.Fatalf("expected one pre-data SQL statement, got=%v", plan.PreDataSQL)
	}
	if !strings.Contains(plan.PreDataSQL[0], "ALTER TABLE `app`.`users` ADD COLUMN `aaaa` varchar(255) NULL") {
		t.Fatalf("unexpected add-column SQL: %v", plan.PreDataSQL)
	}
	if !strings.Contains(plan.PlannedAction, "补齐缺失字段(1)") {
		t.Fatalf("unexpected planned action: %s", plan.PlannedAction)
	}
}

func TestBuildSchemaMigrationPlan_MySQLToMySQLAutoCreatesMissingTarget(t *testing.T) {
	t.Parallel()

	sourceDB := &fakeMigrationDB{
		columns: map[string][]connection.ColumnDefinition{
			"shop.users": {
				{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI", Extra: "auto_increment"},
				{Name: "name", Type: "varchar(128)", Nullable: "YES", Default: stringPtr("")},
			},
		},
		indexes: map[string][]connection.IndexDefinition{
			"shop.users": {
				{Name: "idx_users_name", ColumnName: "name", NonUnique: 1, SeqInIndex: 1, IndexType: "BTREE"},
			},
		},
	}
	targetDB := &fakeMigrationDB{columns: map[string][]connection.ColumnDefinition{}}
	cfg := SyncConfig{
		SourceConfig:        connection.ConnectionConfig{Type: "mysql", Database: "shop"},
		TargetConfig:        connection.ConnectionConfig{Type: "mysql", Database: "app"},
		TargetTableStrategy: "smart",
		CreateIndexes:       true,
	}

	plan, sourceCols, targetCols, err := buildSchemaMigrationPlan(cfg, "users", sourceDB, targetDB)
	if err != nil {
		t.Fatalf("buildSchemaMigrationPlan returned error: %v", err)
	}
	if len(sourceCols) != 2 || len(targetCols) != 0 {
		t.Fatalf("unexpected columns lengths: source=%d target=%d", len(sourceCols), len(targetCols))
	}
	if plan.TargetTableExists {
		t.Fatalf("expected target table missing")
	}
	if !plan.AutoCreate {
		t.Fatalf("expected mysql->mysql auto create enabled, plan=%+v", plan)
	}
	if strings.Contains(strings.Join(plan.Warnings, " "), "MySQL -> Kingbase") {
		t.Fatalf("mysql->mysql should not warn with old mysql->kingbase-only message: %v", plan.Warnings)
	}
	if !strings.Contains(plan.PlannedAction, "自动建表") {
		t.Fatalf("unexpected planned action: %s", plan.PlannedAction)
	}
	if !strings.Contains(plan.CreateTableSQL, "CREATE TABLE `app`.`users`") {
		t.Fatalf("unexpected create table SQL: %s", plan.CreateTableSQL)
	}
	if !strings.Contains(plan.CreateTableSQL, "`id` bigint NOT NULL AUTO_INCREMENT") {
		t.Fatalf("unexpected id definition: %s", plan.CreateTableSQL)
	}
	if !strings.Contains(plan.CreateTableSQL, "PRIMARY KEY (`id`)") {
		t.Fatalf("missing primary key: %s", plan.CreateTableSQL)
	}
	if len(plan.PostDataSQL) != 1 || !strings.Contains(plan.PostDataSQL[0], "CREATE INDEX `idx_users_name`") {
		t.Fatalf("unexpected index SQL: %v", plan.PostDataSQL)
	}
}

func TestBuildMySQLToMySQLCreateTablePlan_ListsCompositePrefixRemediation(t *testing.T) {
	t.Parallel()

	sourceDB := &fakeMigrationDB{
		indexes: map[string][]connection.IndexDefinition{
			"shop.users": {
				{Name: "idx_users_lookup", ColumnName: "email", NonUnique: 1, SeqInIndex: 2, IndexType: "BTREE"},
				{Name: "idx_users_lookup", ColumnName: "name", NonUnique: 1, SeqInIndex: 1, IndexType: "BTREE", SubPart: 12},
				{Name: "idx_users_lookup", ColumnName: "bio", NonUnique: 1, SeqInIndex: 3, IndexType: "BTREE", SubPart: 24},
			},
		},
	}
	cols := []connection.ColumnDefinition{
		{Name: "name", Type: "varchar(128)", Nullable: "NO"},
		{Name: "email", Type: "varchar(255)", Nullable: "NO"},
		{Name: "bio", Type: "text", Nullable: "YES"},
	}

	_, postSQL, warnings, unsupported, unmigrated, idxCreate, idxSkip, err := buildMySQLToMySQLCreateTablePlan(
		"mysql",
		SyncConfig{CreateIndexes: true},
		"app.users",
		cols,
		sourceDB,
		"shop",
		"users",
	)
	if err != nil {
		t.Fatalf("buildMySQLToMySQLCreateTablePlan returned error: %v", err)
	}
	want := "CREATE INDEX `idx_users_lookup` ON `app`.`users` (`name`(12), `email`, `bio`(24))"
	if len(postSQL) != 0 || idxCreate != 0 || idxSkip != 1 {
		t.Fatalf("prefix index must require review: sql=%v create=%d skip=%d", postSQL, idxCreate, idxSkip)
	}
	if len(warnings) != 0 || len(unsupported) != 1 || len(unmigrated) != 1 {
		t.Fatalf("unexpected warnings/unsupported: warnings=%v unsupported=%v unmigrated=%v", warnings, unsupported, unmigrated)
	}
	if !reflect.DeepEqual(unmigrated[0].RemediationStatements, []string{want}) {
		t.Fatalf("unexpected prefix remediation: got=%v want=%v", unmigrated[0].RemediationStatements, []string{want})
	}
}

func TestBuildMySQLToMySQLCreateTablePlan_ListsFulltextRemediation(t *testing.T) {
	t.Parallel()

	sourceDB := &fakeMigrationDB{
		indexes: map[string][]connection.IndexDefinition{
			"shop.articles": {
				{Name: "idx_fulltext_body", ColumnName: "title", NonUnique: 1, SeqInIndex: 1, IndexType: "FULLTEXT"},
				{Name: "idx_fulltext_body", ColumnName: "body", NonUnique: 1, SeqInIndex: 2, IndexType: "FULLTEXT"},
			},
		},
	}
	cols := []connection.ColumnDefinition{
		{Name: "title", Type: "varchar(255)", Nullable: "NO"},
		{Name: "body", Type: "text", Nullable: "NO"},
	}

	_, postSQL, warnings, unsupported, unmigrated, idxCreate, idxSkip, err := buildMySQLToMySQLCreateTablePlan(
		"mysql",
		SyncConfig{CreateIndexes: true},
		"archive.articles",
		cols,
		sourceDB,
		"shop",
		"articles",
	)
	if err != nil {
		t.Fatalf("buildMySQLToMySQLCreateTablePlan returned error: %v", err)
	}
	if len(postSQL) != 0 || idxCreate != 0 || idxSkip != 1 {
		t.Fatalf("fulltext index must require review: sql=%v create=%d skip=%d", postSQL, idxCreate, idxSkip)
	}
	if len(warnings) != 0 || len(unsupported) != 1 || len(unmigrated) != 1 {
		t.Fatalf("unexpected fulltext summary: warnings=%v unsupported=%v unmigrated=%+v", warnings, unsupported, unmigrated)
	}
	wantSQL := "CREATE FULLTEXT INDEX `idx_fulltext_body` ON `archive`.`articles` (`title`, `body`)"
	if !reflect.DeepEqual(unmigrated[0].RemediationStatements, []string{wantSQL}) {
		t.Fatalf("unexpected fulltext remediation: got=%v want=%v", unmigrated[0].RemediationStatements, []string{wantSQL})
	}
}

func TestBuildMongoIndexCommands_ListsUnmigratedIndexes(t *testing.T) {
	t.Parallel()

	sourceDB := &fakeMigrationDB{
		indexes: map[string][]connection.IndexDefinition{
			"shop.articles": {
				{Name: "idx_lookup", ColumnName: "category", NonUnique: 1, SeqInIndex: 2, IndexType: "BTREE"},
				{Name: "idx_lookup", ColumnName: "author", NonUnique: 1, SeqInIndex: 1, IndexType: "BTREE"},
				{Name: "idx_title_prefix", ColumnName: "title", NonUnique: 1, SeqInIndex: 1, IndexType: "BTREE", SubPart: 12},
				{Name: "idx_fulltext_body", ColumnName: "title", NonUnique: 1, SeqInIndex: 1, IndexType: "FULLTEXT"},
				{Name: "idx_fulltext_body", ColumnName: "body", NonUnique: 1, SeqInIndex: 2, IndexType: "FULLTEXT"},
			},
		},
	}

	commands, warnings, unsupported, unmigrated, created, skipped, err := buildMongoIndexCommands(sourceDB, "shop", "articles", "articles")
	if err != nil {
		t.Fatalf("buildMongoIndexCommands returned error: %v", err)
	}
	if created != 1 || skipped != 2 || len(commands) != 1 {
		t.Fatalf("unexpected Mongo index summary: commands=%v create=%d skip=%d", commands, created, skipped)
	}
	if !strings.Contains(commands[0], `"key":{"author":1,"category":1}`) {
		t.Fatalf("Mongo compound index order was not preserved: %s", commands[0])
	}
	if len(warnings) != 0 || len(unsupported) != 2 || len(unmigrated) != 2 {
		t.Fatalf("unexpected Mongo index warnings: warnings=%v unsupported=%v unmigrated=%+v", warnings, unsupported, unmigrated)
	}
	if unmigrated[0].ReasonCode != "prefix_index_requires_review" || !strings.Contains(strings.Join(unmigrated[0].RemediationStatements, "\n"), `"key":{"title":1}`) {
		t.Fatalf("unexpected prefix remediation: %+v", unmigrated[0])
	}
	if unmigrated[1].ReasonCode != "fulltext_requires_review" || !strings.Contains(strings.Join(unmigrated[1].RemediationStatements, "\n"), `"key":{"title":"text","body":"text"}`) {
		t.Fatalf("unexpected fulltext remediation: %+v", unmigrated[1])
	}
}

func TestBuildSchemaMigrationPlan_PGLikeToPGLikeAutoCreatesMissingTarget(t *testing.T) {
	t.Parallel()

	sourceDB := &fakeMigrationDB{
		columns: map[string][]connection.ColumnDefinition{
			"public.accounts": {
				{Name: "id", Type: "integer", Nullable: "NO", Key: "PRI", Extra: "auto_increment"},
				{Name: "email", Type: "character varying(128)", Nullable: "NO"},
				{Name: "status", Type: "text", Nullable: "NO", Default: stringPtr("'active'::text")},
			},
		},
		indexes: map[string][]connection.IndexDefinition{
			"public.accounts": {
				{Name: "accounts_pkey", ColumnName: "id", NonUnique: 0, SeqInIndex: 1, IndexType: "btree"},
				{Name: "accounts_email_key", ColumnName: "email", NonUnique: 0, SeqInIndex: 1, IndexType: "btree"},
			},
		},
	}
	targetDB := &fakeMigrationDB{columns: map[string][]connection.ColumnDefinition{}}
	cfg := SyncConfig{
		SourceConfig:        connection.ConnectionConfig{Type: "postgres", Database: "public"},
		TargetConfig:        connection.ConnectionConfig{Type: "kingbase", Database: "app"},
		TargetTableStrategy: "smart",
		CreateIndexes:       true,
	}

	plan, sourceCols, targetCols, err := buildSchemaMigrationPlan(cfg, "accounts", sourceDB, targetDB)
	if err != nil {
		t.Fatalf("buildSchemaMigrationPlan returned error: %v", err)
	}
	if len(sourceCols) != 3 || len(targetCols) != 0 {
		t.Fatalf("unexpected columns lengths: source=%d target=%d", len(sourceCols), len(targetCols))
	}
	if !plan.AutoCreate {
		t.Fatalf("expected pglike->pglike auto create enabled, plan=%+v", plan)
	}
	if strings.Contains(strings.Join(plan.Warnings, " "), "MySQL -> Kingbase") {
		t.Fatalf("pglike->pglike should not warn with old mysql->kingbase-only message: %v", plan.Warnings)
	}
	if !strings.Contains(plan.CreateTableSQL, "CREATE TABLE public.accounts") {
		t.Fatalf("unexpected create table SQL: %s", plan.CreateTableSQL)
	}
	if !strings.Contains(plan.CreateTableSQL, "id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL") {
		t.Fatalf("unexpected id definition: %s", plan.CreateTableSQL)
	}
	if !strings.Contains(plan.CreateTableSQL, "status text DEFAULT 'active'::text NOT NULL") {
		t.Fatalf("unexpected default definition: %s", plan.CreateTableSQL)
	}
	if strings.Contains(plan.CreateTableSQL, "'''active''::text'") {
		t.Fatalf("default expression should not be quoted as a string literal: %s", plan.CreateTableSQL)
	}
	if len(plan.PostDataSQL) != 1 || !strings.Contains(plan.PostDataSQL[0], "CREATE UNIQUE INDEX accounts_email_key") {
		t.Fatalf("unexpected index SQL: %v", plan.PostDataSQL)
	}
	if strings.Contains(strings.Join(plan.PostDataSQL, "\n"), "accounts_pkey") {
		t.Fatalf("primary key index should not be recreated: %v", plan.PostDataSQL)
	}
}

func TestBuildSchemaMigrationPlan_ClickHouseToClickHouseAutoCreatesMissingTarget(t *testing.T) {
	t.Parallel()

	sourceDB := &fakeMigrationDB{
		columns: map[string][]connection.ColumnDefinition{
			"analytics.events": {
				{Name: "ts", Type: "DateTime", Nullable: "NO", Key: "PRI"},
				{Name: "user_id", Type: "UInt64", Nullable: "NO"},
				{Name: "payload", Type: "String", Nullable: "YES"},
			},
		},
	}
	targetDB := &fakeMigrationDB{columns: map[string][]connection.ColumnDefinition{}}
	cfg := SyncConfig{
		SourceConfig:        connection.ConnectionConfig{Type: "clickhouse", Database: "analytics"},
		TargetConfig:        connection.ConnectionConfig{Type: "clickhouse", Database: "archive"},
		TargetTableStrategy: "smart",
	}

	plan, sourceCols, targetCols, err := buildSchemaMigrationPlan(cfg, "events", sourceDB, targetDB)
	if err != nil {
		t.Fatalf("buildSchemaMigrationPlan returned error: %v", err)
	}
	if len(sourceCols) != 3 || len(targetCols) != 0 {
		t.Fatalf("unexpected columns lengths: source=%d target=%d", len(sourceCols), len(targetCols))
	}
	if !plan.AutoCreate {
		t.Fatalf("expected clickhouse->clickhouse auto create enabled, plan=%+v", plan)
	}
	if !strings.Contains(plan.CreateTableSQL, "CREATE TABLE `archive`.`events`") {
		t.Fatalf("unexpected create table SQL: %s", plan.CreateTableSQL)
	}
	if !strings.Contains(plan.CreateTableSQL, "ENGINE = MergeTree() ORDER BY (`ts`)") {
		t.Fatalf("unexpected order by: %s", plan.CreateTableSQL)
	}
}

func TestBuildSchemaMigrationPlan_MongoToMongoAutoCreatesMissingTarget(t *testing.T) {
	t.Parallel()

	sourceQuery := `{"find":"users","filter":{},"limit":200}`
	sourceDB := &fakeMigrationDB{
		queryData: map[string][]map[string]interface{}{
			sourceQuery: {
				{"_id": "u1", "name": "Ada", "age": 37},
			},
		},
		indexes: map[string][]connection.IndexDefinition{
			"app.users": {
				{Name: "idx_users_name", ColumnName: "name", NonUnique: 1, SeqInIndex: 1, IndexType: "BTREE"},
			},
		},
	}
	targetDB := &fakeMigrationDB{tables: map[string][]string{"archive": []string{}}}
	cfg := SyncConfig{
		SourceConfig:        connection.ConnectionConfig{Type: "mongodb", Database: "app"},
		TargetConfig:        connection.ConnectionConfig{Type: "mongodb", Database: "archive"},
		TargetTableStrategy: "smart",
		CreateIndexes:       true,
	}

	plan, sourceCols, targetCols, err := buildSchemaMigrationPlan(cfg, "users", sourceDB, targetDB)
	if err != nil {
		t.Fatalf("buildSchemaMigrationPlan returned error: %v", err)
	}
	if len(sourceCols) == 0 || len(targetCols) != 0 {
		t.Fatalf("unexpected columns lengths: source=%d target=%d", len(sourceCols), len(targetCols))
	}
	if !plan.AutoCreate {
		t.Fatalf("expected mongo->mongo auto create enabled, plan=%+v", plan)
	}
	if strings.TrimSpace(plan.CreateTableSQL) != "" {
		t.Fatalf("mongo create should be pre-data command only: %s", plan.CreateTableSQL)
	}
	if len(plan.PreDataSQL) != 1 || !strings.Contains(plan.PreDataSQL[0], `"create":"users"`) {
		t.Fatalf("unexpected create collection command: %v", plan.PreDataSQL)
	}
	if len(plan.PostDataSQL) != 1 || !strings.Contains(plan.PostDataSQL[0], `"createIndexes":"users"`) {
		t.Fatalf("unexpected index command: %v", plan.PostDataSQL)
	}
}

func TestBuildMySQLToPGLikeCreateTablePlan_GeneratesPostgresDDL(t *testing.T) {
	t.Parallel()

	sourceDB := &fakeMigrationDB{
		indexes: map[string][]connection.IndexDefinition{
			"shop.orders": {
				{Name: "idx_orders_user", ColumnName: "user_id", NonUnique: 1, SeqInIndex: 1, IndexType: "BTREE"},
				{Name: "idx_orders_user", ColumnName: "status", NonUnique: 1, SeqInIndex: 2, IndexType: "BTREE"},
			},
		},
	}
	cols := []connection.ColumnDefinition{
		{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI", Extra: "auto_increment"},
		{Name: "user_id", Type: "bigint", Nullable: "NO"},
		{Name: "status", Type: "varchar(32)", Nullable: "YES"},
		{Name: "payload", Type: "json", Nullable: "YES"},
	}
	cfg := SyncConfig{CreateIndexes: true}
	createSQL, postSQL, warnings, unsupported, unmigrated, idxCreate, idxSkip, err := buildMySQLToPGLikeCreateTablePlan("postgres", cfg, "public.orders", cols, sourceDB, "shop", "orders")
	if err != nil {
		t.Fatalf("buildMySQLToPGLikeCreateTablePlan returned error: %v", err)
	}
	if !strings.Contains(createSQL, `CREATE TABLE "public"."orders"`) {
		t.Fatalf("unexpected create SQL: %s", createSQL)
	}
	if !strings.Contains(createSQL, `GENERATED BY DEFAULT AS IDENTITY`) {
		t.Fatalf("missing identity mapping: %s", createSQL)
	}
	if !strings.Contains(createSQL, `jsonb`) {
		t.Fatalf("missing jsonb mapping: %s", createSQL)
	}
	if idxCreate != 1 || idxSkip != 0 {
		t.Fatalf("unexpected index summary: create=%d skip=%d", idxCreate, idxSkip)
	}
	if len(postSQL) != 1 || !strings.Contains(postSQL[0], `CREATE INDEX "idx_orders_user"`) {
		t.Fatalf("unexpected post SQL: %v", postSQL)
	}
	if len(warnings) != 0 || len(unsupported) != 0 || len(unmigrated) != 0 {
		t.Fatalf("unexpected warnings/unsupported: warnings=%v unsupported=%v unmigrated=%v", warnings, unsupported, unmigrated)
	}
}

func TestBuildPGLikeToPGLikeCreateTablePlan_CopiesTableDependents(t *testing.T) {
	t.Parallel()

	nextval := "nextval('public.orders_id_seq'::regclass)"
	sourceDB := &fakeMigrationDB{
		indexes: map[string][]connection.IndexDefinition{
			"public.orders": {
				{Name: "idx_orders_status", ColumnName: "status", NonUnique: 1, SeqInIndex: 1, IndexType: "BTREE"},
			},
		},
		triggers: map[string][]connection.TriggerDefinition{
			"public.orders": {
				{Name: "orders_bi", Timing: "BEFORE", Event: "INSERT", Statement: "EXECUTE FUNCTION orders_bi()", Orientation: "ROW"},
			},
		},
		tableComments: map[string]string{"public.orders": "order header"},
	}
	cols := []connection.ColumnDefinition{
		{Name: "id", Type: "bigint", Nullable: "NO", Key: "PRI", Default: &nextval, Comment: "primary key"},
		{Name: "status", Type: "text", Nullable: "YES"},
	}
	cfg := SyncConfig{CreateIndexes: true}
	createSQL, postSQL, warnings, unsupported, idxCreate, idxSkip, err := buildPGLikeToPGLikeCreateTablePlan(
		"postgres", cfg, "ods.orders", cols, sourceDB, "public", "orders",
	)
	if err != nil {
		t.Fatalf("buildPGLikeToPGLikeCreateTablePlan returned error: %v", err)
	}
	joined := strings.Join(postSQL, "\n")
	if !strings.Contains(createSQL, `CREATE TABLE "ods"."orders"`) {
		t.Fatalf("unexpected create SQL: %s", createSQL)
	}
	if !strings.Contains(joined, `CREATE SEQUENCE IF NOT EXISTS "ods"."orders_id_seq"`) {
		t.Fatalf("missing owned sequence: %s", joined)
	}
	if !strings.Contains(joined, `COMMENT ON COLUMN "ods"."orders"."id" IS 'primary key'`) {
		t.Fatalf("missing column comment: %s", joined)
	}
	if !strings.Contains(joined, `COMMENT ON TABLE "ods"."orders" IS 'order header'`) {
		t.Fatalf("missing table comment: %s", joined)
	}
	if !strings.Contains(joined, `CREATE TRIGGER "orders_bi" BEFORE INSERT ON "ods"."orders" FOR EACH ROW EXECUTE FUNCTION orders_bi()`) {
		t.Fatalf("missing trigger: %s", joined)
	}
	if !strings.Contains(joined, `CREATE INDEX "idx_orders_status"`) {
		t.Fatalf("missing index: %s", joined)
	}
	if idxCreate != 1 || idxSkip != 0 {
		t.Fatalf("unexpected index summary: create=%d skip=%d", idxCreate, idxSkip)
	}
	if len(warnings) != 0 || len(unsupported) != 0 {
		t.Fatalf("unexpected warnings/unsupported: warnings=%v unsupported=%v", warnings, unsupported)
	}
}
