package sync

import (
	"fmt"
	"regexp"
	"strings"

	"GoNavi-Wails/internal/connection"
	"GoNavi-Wails/internal/db"
)

func buildMySQLToKingbaseAddColumnSQL(targetQueryTable string, sourceCols, targetCols []connection.ColumnDefinition) ([]string, []string) {
	targetSet := make(map[string]struct{}, len(targetCols))
	for _, col := range targetCols {
		key := strings.ToLower(strings.TrimSpace(col.Name))
		if key == "" {
			continue
		}
		targetSet[key] = struct{}{}
	}

	var sqlList []string
	var warnings []string
	for _, col := range sourceCols {
		key := strings.ToLower(strings.TrimSpace(col.Name))
		if key == "" {
			continue
		}
		if _, ok := targetSet[key]; ok {
			continue
		}
		colType, _, mapWarnings := mapMySQLColumnToKingbase(col)
		warnings = append(warnings, mapWarnings...)
		if warning := relaxedNotNullAddColumnWarning(col); warning != "" {
			warnings = append(warnings, warning)
		}
		if col.Extra != "" && strings.Contains(strings.ToLower(col.Extra), "auto_increment") {
			warnings = append(warnings, fmt.Sprintf("字段 %s 为自增列，补齐到已有目标表时不会自动补建 identity/sequence", col.Name))
		}
		sqlList = append(sqlList, fmt.Sprintf("ALTER TABLE %s ADD COLUMN %s %s NULL",
			quoteQualifiedIdentByType("kingbase", targetQueryTable),
			quoteIdentByType("kingbase", col.Name),
			colType,
		))
	}
	return sqlList, dedupeStrings(warnings)
}

func buildMySQLToKingbaseCreateTablePlan(config SyncConfig, targetQueryTable string, sourceCols []connection.ColumnDefinition, sourceDB db.Database, sourceSchema, sourceTable string) (string, []string, []string, []string, []UnmigratedIndex, int, int, error) {
	columnDefs := make([]string, 0, len(sourceCols)+1)
	warnings := make([]string, 0)
	unsupported := make([]string, 0)
	pkCols := make([]string, 0, 2)

	for _, col := range sourceCols {
		def, colWarnings := buildMySQLToKingbaseColumnDefinition(col)
		warnings = append(warnings, colWarnings...)
		columnDefs = append(columnDefs, fmt.Sprintf("%s %s", quoteIdentByType("kingbase", col.Name), def))
		if col.Key == "PRI" || col.Key == "PK" {
			pkCols = append(pkCols, quoteIdentByType("kingbase", col.Name))
		}
	}
	if len(pkCols) > 0 {
		columnDefs = append(columnDefs, fmt.Sprintf("PRIMARY KEY (%s)", strings.Join(pkCols, ", ")))
	}
	createSQL := fmt.Sprintf("CREATE TABLE %s (\n  %s\n)", quoteQualifiedIdentByType("kingbase", targetQueryTable), strings.Join(columnDefs, ",\n  "))

	if !config.CreateIndexes {
		return createSQL, nil, dedupeStrings(warnings), dedupeStrings(unsupported), nil, 0, 0, nil
	}

	indexes, err := sourceDB.GetIndexes(sourceSchema, sourceTable)
	if err != nil {
		warnings = append(warnings, fmt.Sprintf("读取源表索引失败，已跳过索引迁移：%v", err))
		return createSQL, nil, dedupeStrings(warnings), dedupeStrings(unsupported), nil, 0, 0, nil
	}
	postSQL, unsupported, unmigrated, created, skipped := buildMySQLSourceIndexPlan("kingbase", targetQueryTable,
		stripPrimaryKeyImplicitIndexes(indexes, sourceCols))
	return createSQL, postSQL, dedupeStrings(warnings), unsupported, unmigrated, created, skipped, nil
}

func buildMySQLToKingbaseColumnDefinition(col connection.ColumnDefinition) (string, []string) {
	targetType, useIdentity, warnings := mapMySQLColumnToKingbase(col)
	parts := []string{targetType}
	if useIdentity {
		parts = append(parts, "GENERATED BY DEFAULT AS IDENTITY")
	}
	if !useIdentity {
		if defaultSQL, ok, warningText := mapMySQLDefaultToKingbase(col, targetType); warningText != "" {
			warnings = append(warnings, warningText)
		} else if ok {
			parts = append(parts, "DEFAULT "+defaultSQL)
		}
	}
	if strings.EqualFold(strings.TrimSpace(col.Nullable), "NO") {
		parts = append(parts, "NOT NULL")
	}
	return strings.Join(parts, " "), dedupeStrings(warnings)
}

func mapMySQLColumnToKingbase(col connection.ColumnDefinition) (string, bool, []string) {
	raw := strings.ToLower(strings.TrimSpace(col.Type))
	warnings := make([]string, 0)
	if raw == "" {
		return "text", false, []string{fmt.Sprintf("字段 %s 类型为空，已降级为 text", col.Name)}
	}
	unsigned := strings.Contains(raw, "unsigned")
	clean := strings.ReplaceAll(raw, " unsigned", "")
	clean = strings.ReplaceAll(clean, " zerofill", "")
	isAutoIncrement := strings.Contains(strings.ToLower(strings.TrimSpace(col.Extra)), "auto_increment")

	switch {
	case strings.HasPrefix(clean, "tinyint(1)") && !unsigned && !isAutoIncrement:
		return "boolean", false, warnings
	case strings.HasPrefix(clean, "tinyint"):
		return ternaryString(unsigned, "smallint", "smallint"), isAutoIncrement, warnings
	case strings.HasPrefix(clean, "smallint"):
		return ternaryString(unsigned, "integer", "smallint"), isAutoIncrement, warnings
	case strings.HasPrefix(clean, "mediumint"):
		return ternaryString(unsigned, "bigint", "integer"), isAutoIncrement, warnings
	case strings.HasPrefix(clean, "int") || strings.HasPrefix(clean, "integer"):
		return ternaryString(unsigned, "bigint", "integer"), isAutoIncrement, warnings
	case strings.HasPrefix(clean, "bigint"):
		if unsigned {
			if isAutoIncrement {
				warnings = append(warnings, fmt.Sprintf("字段 %s 为 unsigned bigint auto_increment，已降级为 numeric(20,0) 且不保留自增语义", col.Name))
			}
			return "numeric(20,0)", false, warnings
		}
		return "bigint", isAutoIncrement, warnings
	case strings.HasPrefix(clean, "decimal"), strings.HasPrefix(clean, "numeric"):
		return replaceTypeBase(clean, []string{"decimal", "numeric"}, "numeric"), false, warnings
	case strings.HasPrefix(clean, "float"):
		return "real", false, warnings
	case strings.HasPrefix(clean, "double"):
		return "double precision", false, warnings
	case strings.HasPrefix(clean, "bit("):
		if clean == "bit(1)" {
			return "boolean", false, warnings
		}
		return clean, false, warnings
	case strings.HasPrefix(clean, "bool"), strings.HasPrefix(clean, "boolean"):
		return "boolean", false, warnings
	case strings.HasPrefix(clean, "char("), strings.HasPrefix(clean, "varchar("):
		return clean, false, warnings
	case strings.HasPrefix(clean, "tinytext"), strings.HasPrefix(clean, "text"), strings.HasPrefix(clean, "mediumtext"), strings.HasPrefix(clean, "longtext"):
		return "text", false, warnings
	case strings.HasPrefix(clean, "json"):
		return "jsonb", false, warnings
	case strings.HasPrefix(clean, "datetime"), strings.HasPrefix(clean, "timestamp"):
		// 必须放在 "date"/"time" 之前：datetime/timestamp 同时以二者为前缀。
		return "timestamp", false, warnings
	case strings.HasPrefix(clean, "date"):
		return "date", false, warnings
	case strings.HasPrefix(clean, "time"):
		return "time", false, warnings
	case strings.HasPrefix(clean, "year"):
		warnings = append(warnings, fmt.Sprintf("字段 %s 类型 year 已映射为 integer", col.Name))
		return "integer", false, warnings
	case strings.HasPrefix(clean, "binary"), strings.HasPrefix(clean, "varbinary"), strings.HasPrefix(clean, "tinyblob"), strings.HasPrefix(clean, "blob"), strings.HasPrefix(clean, "mediumblob"), strings.HasPrefix(clean, "longblob"):
		return "bytea", false, warnings
	case strings.HasPrefix(clean, "enum"), strings.HasPrefix(clean, "set"):
		warnings = append(warnings, fmt.Sprintf("字段 %s 类型 %s 已降级为 text", col.Name, col.Type))
		return "text", false, warnings
	default:
		warnings = append(warnings, fmt.Sprintf("字段 %s 类型 %s 暂无专门映射，已降级为 text", col.Name, col.Type))
		return "text", false, warnings
	}
}

func replaceTypeBase(raw string, bases []string, target string) string {
	for _, base := range bases {
		if strings.HasPrefix(raw, base) {
			return target + strings.TrimPrefix(raw, base)
		}
	}
	return target
}

var numericPattern = regexp.MustCompile(`^[+-]?\d+(\.\d+)?$`)

func mapMySQLDefaultToKingbase(col connection.ColumnDefinition, targetType string) (string, bool, string) {
	if col.Default == nil {
		return "", false, ""
	}
	raw := strings.TrimSpace(*col.Default)
	if raw == "" {
		if isStringLikeTargetType(targetType) {
			return "''", true, ""
		}
		return "", false, fmt.Sprintf("字段 %s 的空字符串默认值未保留", col.Name)
	}
	lower := strings.ToLower(raw)
	if lower == "null" {
		return "", false, ""
	}
	if strings.HasPrefix(lower, "current_timestamp") {
		return "CURRENT_TIMESTAMP", true, ""
	}
	// CURRENT_DATE/CURRENT_TIME 不在 isStringLikeTargetType 覆盖内，
	// 不加分支会走到末尾按字符串加引号，生成 DEFAULT 'CURRENT_DATE'。
	if strings.HasPrefix(lower, "current_date") {
		return "CURRENT_DATE", true, ""
	}
	if strings.HasPrefix(lower, "current_time") {
		return "CURRENT_TIME", true, ""
	}
	if targetType == "boolean" {
		switch lower {
		case "1", "true":
			return "TRUE", true, ""
		case "0", "false":
			return "FALSE", true, ""
		}
	}
	if numericPattern.MatchString(raw) && !isStringLikeTargetType(targetType) {
		return raw, true, ""
	}
	if strings.ContainsAny(raw, "()") && !strings.HasPrefix(lower, "current_timestamp") {
		return "", false, fmt.Sprintf("字段 %s 的默认值 %s 包含表达式，当前未自动迁移", col.Name, raw)
	}
	return "'" + strings.ReplaceAll(raw, "'", "''") + "'", true, ""
}

func isStringLikeTargetType(targetType string) bool {
	text := strings.ToLower(strings.TrimSpace(targetType))
	return strings.Contains(text, "char") || strings.Contains(text, "text") || strings.Contains(text, "json") || strings.Contains(text, "bytea")
}

func ternaryString(ok bool, a, b string) string {
	if ok {
		return a
	}
	return b
}
