// 大文件拆分后，源码扫描类测试需要按原顺序聚合的模块清单（相对 src/components 或 src）。

// DataGrid.tsx 已拆出 dataGrid/ 下的常量模块与 hook，源码扫描按原顺序聚合。
export const DATA_GRID_COMPONENT_MODULES = [
  "DataGrid.tsx",
  "dataGrid/dataGridPagingOptions.ts",
  "dataGrid/dataGridScrollTiming.ts",
  "dataGrid/hooks/useDataGridCoreState.ts",
  "dataGrid/hooks/useDataGridCellEditorState.ts",
  "dataGrid/hooks/useDataGridTableMetrics.ts",
  "dataGrid/hooks/useDataGridColumnTitles.tsx",
  "dataGrid/hooks/useDataGridCellEditing.ts",
  "dataGrid/hooks/useDataGridInlineEditor.ts",
  "dataGrid/hooks/useDataGridRowEditors.ts",
  "dataGrid/hooks/useDataGridColumns.tsx",
  "dataGrid/hooks/useDataGridRowActions.tsx",
  "dataGrid/hooks/useDataGridCommit.ts",
  "dataGrid/hooks/useDataGridHorizontalVirtualScroll.tsx",
  "dataGrid/hooks/useDataGridPageFind.ts",
  "dataGrid/hooks/useDataGridExternalScroll.ts",
  "dataGrid/hooks/useDataGridLayoutEffects.ts",
];

// QueryEditor.tsx 已拆成 hook / 子组件 / 辅助模块，源码扫描按原顺序聚合。
export const QUERY_EDITOR_COMPONENT_MODULES = [
  "QueryEditor.tsx",
  "queryEditor/queryEditorRunHelpers.ts",
  "queryEditor/queryEditorObjectEditSql.ts",
  "queryEditor/queryEditorObjectDefinitionQueries.ts",
  "queryEditor/queryEditorCompletionState.ts",
  "queryEditor/queryEditorCompletionColumns.ts",
  "queryEditor/queryEditorLazyTablesCache.ts",
  "queryEditor/queryEditorHoverDdl.ts",
  "queryEditor/queryEditorCompletionTables.ts",
  "queryEditor/queryEditorResultSort.ts",
  "queryEditor/hooks/useQueryEditorCoreState.ts",
  "queryEditor/hooks/useQueryEditorConnectionContext.ts",
  "queryEditor/hooks/useQueryEditorShortcutsAndSnippets.ts",
  "queryEditor/hooks/useQueryEditorAiCompletionTriggers.ts",
  "queryEditor/hooks/useQueryEditorExecutionStatus.ts",
  "queryEditor/hooks/useQueryEditorQueryContext.ts",
  "queryEditor/hooks/useQueryEditorDraftSync.ts",
  "queryEditor/hooks/useQueryEditorAiContext.ts",
  "queryEditor/hooks/useQueryEditorObjectDecorations.ts",
  "queryEditor/hooks/useQueryEditorDropAndLineEdits.ts",
  "queryEditor/hooks/useQueryEditorAiAssistActions.ts",
  "queryEditor/hooks/useQueryEditorMetadataLoading.ts",
  "queryEditor/metadata/queryEditorMetadataRowCollectors.ts",
  "queryEditor/hooks/useQueryEditorEditorSplit.ts",
  "queryEditor/hooks/useQueryEditorObjectEditTabs.ts",
  "queryEditor/hooks/useQueryEditorMonacoMount.ts",
  "queryEditor/monaco/queryEditorAiInlineGhostState.ts",
  "queryEditor/monaco/queryEditorAiInlineGhostActions.ts",
  "queryEditor/monaco/queryEditorNavigationHover.ts",
  "queryEditor/monaco/queryEditorImeAndDropHandlers.ts",
  "queryEditor/monaco/queryEditorEditorEventBindings.ts",
  "queryEditor/monaco/queryEditorMouseAndDisposeBindings.ts",
  "queryEditor/monaco/queryEditorKeyBindings.ts",
  "queryEditor/monaco/queryEditorSqlLanguageProviders.ts",
  "queryEditor/sqlCompletion/sqlCompletionDialectContext.ts",
  "queryEditor/sqlCompletion/sqlCompletionSuggestionBuilders.ts",
  "queryEditor/sqlCompletion/sqlCompletionMetadataLookups.ts",
  "queryEditor/sqlCompletion/sqlCompletionStatementContext.ts",
  "queryEditor/sqlCompletion/sqlCompletionQualifierSuggestions.ts",
  "queryEditor/sqlCompletion/sqlCompletionRankingContext.ts",
  "queryEditor/sqlCompletion/sqlCompletionGlobalSuggestions.ts",
  "queryEditor/monaco/queryEditorSlashCommandBinding.ts",
  "queryEditor/hooks/useQueryEditorFormatting.tsx",
  "queryEditor/hooks/useQueryEditorResultSetModel.ts",
  "queryEditor/hooks/useQueryEditorResultReload.ts",
  "queryEditor/hooks/useQueryEditorResultPaging.ts",
  "queryEditor/hooks/useQueryEditorElasticsearchRun.tsx",
  "queryEditor/hooks/useQueryEditorRun.ts",
  "queryEditor/run/queryEditorMongoRun.ts",
  "queryEditor/run/queryEditorSqlRun.ts",
  "queryEditor/run/queryEditorRunFailure.ts",
  "queryEditor/run/queryEditorRunResultSets.ts",
  "queryEditor/hooks/useQueryEditorEditorActions.ts",
  "queryEditor/hooks/useQueryEditorActiveTabShortcuts.ts",
  "queryEditor/hooks/useQueryEditorSaveActions.ts",
  "queryEditor/hooks/useQueryEditorToolbarMenus.tsx",
  "queryEditor/hooks/useQueryEditorKeyboardShortcuts.ts",
  "queryEditor/hooks/useQueryEditorResultTabs.tsx",
  "queryEditor/QueryEditorEditorPane.tsx",
  "queryEditor/QueryEditorResultsArea.tsx",
  "queryEditor/QueryEditorResultDiffViews.tsx",
  "queryEditor/QueryEditorDialogs.tsx",
  "queryEditor/monaco/queryEditorMouseCursor.ts",
];

// App.tsx 已拆成 hook / 子组件 / 辅助模块（src/appShell），源码扫描按原顺序聚合。
export const APP_SOURCE_MODULES = [
  "App.tsx",
  "appShell/appSettingsConstants.ts",
  "appShell/ThemeSettingsSlider.tsx",
  "appShell/appEnvironment.ts",
  "appShell/connectionPackageImport.ts",
  "appShell/settingsCenterPanes.ts",
  "appShell/globalProxySettings.ts",
  "appShell/aboutSettingsFormat.ts",
  "appShell/SidebarMetadataSortableRow.tsx",
  "appShell/appLayoutParts.ts",
  "appShell/settingsCenterNavigation.ts",
  "appShell/hooks/useAppCoreState.ts",
  "appShell/hooks/useAppShellState.ts",
  "appShell/hooks/useAppBootstrapEffects.ts",
  "appShell/hooks/useAppStartupEffects.tsx",
  "appShell/hooks/useAppWindowEffects.ts",
  "appShell/hooks/useAppSecurityUpdate.ts",
  "appShell/hooks/useAppUpdateAndDiagnostics.ts",
  "appShell/hooks/useAppQuitAndUpdate.tsx",
  "appShell/hooks/useAppConnectionImportExport.ts",
  "appShell/hooks/useAppProxySettings.ts",
  "appShell/hooks/useAppSettingsNavigation.ts",
  "appShell/hooks/useAppDirectorySettingsRender.tsx",
  "appShell/hooks/useAppWorkbenchActions.ts",
  "appShell/hooks/useAppLayoutEffects.ts",
  "appShell/hooks/useAppAntdTheme.tsx",
  "appShell/hooks/useAppSettingsPanesRender.tsx",
  "appShell/hooks/useAppAboutSettingsRender.tsx",
  "appShell/hooks/useAppThemeSettingsRender.tsx",
  "appShell/settings/ThemeModeSettingsSection.tsx",
  "appShell/settings/ThemeAppearanceSettingsSection.tsx",
  "appShell/settings/TabDisplaySettingsSection.tsx",
  "appShell/settings/DataTableSettingsFields.tsx",
  "appShell/hooks/useAppSettingsCenterRender.tsx",
  "appShell/layout/AppTitleBar.tsx",
  "appShell/layout/AppSider.tsx",
  "appShell/layout/AppContent.tsx",
  "appShell/settings/renderAppSettingsCenterModal.tsx",
  "appShell/settings/toolCenterGroups.tsx",
  "appShell/settings/toolCenterPaneRenderer.tsx",
  "appShell/layout/AppGlobalDialogs.tsx",
];

// QueryEditorHelpers.ts 已按主题拆成多个模块，源码扫描需按原顺序聚合。
export const QUERY_EDITOR_HELPER_MODULES = [
  "QueryEditorHelpers.ts",
  "queryEditorCompletionCandidates.ts",
  "queryEditorResultMessages.ts",
  "queryEditorSelectRewrite.ts",
  "queryEditorCompletionMetadata.ts",
  "queryEditorEditorState.ts",
  "queryEditorIdentifierPaths.ts",
  "queryEditorSqlScan.ts",
  "queryEditorReferenceIdentity.ts",
  "queryEditorTableReferences.ts",
  "queryEditorExecutionContext.ts",
  "queryEditorNavigationTarget.ts",
  "queryEditorHoverTarget.ts",
  "queryEditorNavigationDecorations.ts",
  "queryEditorLocatorPlan.ts",
];

// 主题设置面板已拆为 useAppThemeSettingsRender 与各分区组件（相对 src）。
export const APP_THEME_SETTINGS_MODULES = [
    "appShell/hooks/useAppThemeSettingsRender.tsx",
    "appShell/settings/ThemeModeSettingsSection.tsx",
    "appShell/settings/ThemeAppearanceSettingsSection.tsx",
    "appShell/settings/TabDisplaySettingsSection.tsx",
    "appShell/settings/DataTableSettingsFields.tsx",
];
