/**
 * 工作台标签页类型。从 types.ts 拆出，新增标签页类型只改这里。
 * 新增后还需在 WorkbenchTabContent 注册渲染分支（穷尽检查会提示）。
 */
export type WorkbenchTabType =
  | "user-management"
  | "query"
  | "table"
  | "design"
  | "data-sync"
  | "sql-file-execution"
  | "sql-analysis"
  | "sql-audit"
  | "dml-snapshot"
  | "driver-manager"
  | "settings-center"
  | "request-diagnostics"
  | "message-queue"
  | "redis-keys"
  | "redis-command"
  | "redis-monitor"
  | "nacos-config"
  | "nacos-services"
  | "trigger"
  | "view-def"
  | "event-def"
  | "routine-def"
  | "sequence-def"
  | "package-def"
  | "database-link-def"
  | "table-overview"
  | "table-export"
  | "data-import"
  | "jvm-overview"
  | "jvm-resource"
  | "jvm-audit"
  | "jvm-diagnostic"
  | "jvm-monitoring"
  | "session-workbench";
