import { backupTexts } from './textBackup';
import { dataSyncScheduleTextsZhCN, dataSyncRunEventTextsZhCN } from './textSchedules';
import { dataSyncValidationTextsZhCN } from './textValidation';

export const zhCN = {
  ...backupTexts('zh-CN'),
  'workbench.title': '数据迁移与同步',
  'workbench.title_short': '数据同步',
  'workbench.title_compare': '数据对比',
  'workbench.title_compare_short': '数据对比',
  'workbench.title_schema_compare': '表结构比对',
  'workbench.title_data_compare': '数据比对',
  'workbench.subtitle': '定义、验证并追踪跨数据源任务',
  'workbench.subtitle_compare': '只读比较两端结构或数据，不会写入目标',
  'workbench.subtitle_schema_compare': '只读比较两端表结构，不会写入目标',
  'workbench.subtitle_data_compare': '只读比较两端数据，不会写入目标',
  'workbench.start_compare': '开始比对',
  'workbench.service_unavailable': '数据同步服务暂未加载，请重新打开工作台或重试。',
  'workbench.definition_changed_retry': '任务配置已发生变化，请检查后重新执行此操作。',
  'workbench.close': '关闭工作台',
  'workbench.new_task': '新建任务',
  'workbench.save': '保存草稿',
  'workbench.saving': '正在保存',
  'workbench.saved': '已保存',
  'workbench.unsaved': '有未保存修改',
  'workbench.run_preflight': '运行预检',
  'workbench.preflighting': '正在预检',
  'workbench.start': '运行任务',
  'workbench.create_schema_sync': '创建结构同步任务',
  'workbench.enable': '启用任务',
  'workbench.blocked_action': '先解决预检阻断项',
  'workbench.delete': '删除任务',
  'workbench.deleting': '删除中…',
  'workbench.delete_confirm_title': '删除任务',
  'workbench.delete_confirm':
    '确定永久删除该任务吗？任务的运行记录、检查点和错误行将一并删除，且无法恢复。',
  'workbench.lifecycle_before_run': '任务尚未保存为就绪，请先保存草稿再运行',
  'workbench.save_before_run': '当前预检已通过，请先保存任务',
  'workbench.preflight_then_save_before_run': '请先运行预检，再保存任务',
  'workbench.preflight_before_run': '请先运行预检并确认任务版本有效',
  'workbench.capability_before_run': '正在解析数据源能力，请稍后重试',
  'workbench.approval_before_run': '请先完成生产写入审批',
  'workbench.previous_step': '上一步',
  'workbench.next_step': '下一步：{stage}',
  'workbench.return_to_stage': '返回修复：{stage}',
  'workbench.current_step': '第 {current} / {total} 步',
  'workbench.task_actions': '任务操作',
  'workbench.task_list_toggle': '任务列表',
  'workbench.stage_ready': '配置完整',
  'workbench.stage_pending': '待完成',
  'workbench.view_navigation': '工作台视图',
  'workbench.task_steps': '任务配置步骤',
  'nav.tasks': '任务',
  'nav.runs': '运行记录',
  'nav.schedules': '调度',
  'nav.cdc': '持续同步',
  'task_list.title': '任务',
  'task_list.search': '搜索任务',
  'task_list.empty': '没有匹配的任务',
  'task_list.revision': '版本 {revision}',
  'task_list.lifecycle.draft': '草稿',
  'task_list.lifecycle.ready': '就绪',
  'task_list.lifecycle.enabled': '已启用',
  'task_list.lifecycle.paused': '已暂停',
  'task_list.lifecycle.archived': '已归档',
  'lifecycle.enable_schedule': '启用调度',
  'lifecycle.pause': '暂停任务',
  'lifecycle.resume_schedule': '重新启用',
  'lifecycle.archive': '归档',
  'lifecycle.restore': '恢复',
  'task_kind.title': '选择任务类型',
  'task_kind.subtitle': '类型决定可用的增量和触发策略，创建后仍可复制为其他任务。',
  'task_kind.subtitle_compare': '选择要比对结构还是数据。比对任务不会写入目标。',
  'task_kind.migration': '一次性迁移',
  'task_kind.migration_desc': '迁移结构和数据，可创建目标对象。',
  'task_kind.schema_sync': '结构同步',
  'task_kind.reconcile': '批次/差异同步',
  'task_kind.reconcile_desc': '按主键执行快照比较或水位线增量。',
  'task_kind.querySink': 'SQL 结果写入',
  'task_kind.querySink_desc': '执行查询并把稳定结果写入目标表。',
  'task_kind.compare': '只读比较',
  'task_kind.compare_desc': '比较结构或数据，不修改目标端。',
  'task_kind.compare_schema': '表结构比对',
  'task_kind.compare_schema_desc': '只读比较两端表结构，不会写入目标。',
  'task_kind.compare_data': '数据比对',
  'task_kind.compare_data_desc': '只读比较两端数据，不会写入目标。',
  'task_kind.cdc': '持续增量同步',
  'task_kind.cdc_desc': '源库发生增删改时自动同步到目标，并记住已同步到哪。',
  'stage.endpoints': '选择源和目标',
  'stage.mappings': '选择同步数据',
  'stage.mappings_schema_compare': '选择比对对象',
  'stage.mappings_data_compare': '选择比对对象',
  'stage.delivery': '目标写入',
  'stage.trigger': '运行方式',
  'stage.preflight': '检查并运行',
  'stage.preflight_compare': '检查并比对',
  'stage_short.endpoints': '端点',
  'stage_short.mappings': '数据',
  'stage_short.delivery': '写入',
  'stage_short.trigger': '运行',
  'stage_short.preflight': '检查',
  'route.summary': '同步路径',
  'route.summary_compare': '比对路径',
  'route.source': '源端',
  'route.target': '目标端',
  'route.edit': '修改端点',
  'route.choose': '去选择',
  'route.missing_both': '尚未选择源端和目标端',
  'route.missing_source': '尚未选择源端',
  'route.missing_target': '尚未选择目标端',
  'route.pending_source': '选择源连接',
  'route.pending_target': '选择目标连接',
  'route.capability.full': '完整支持',
  'route.capability.partial': '兼容模式',
  'route.capability.unsupported': '不支持',
  'route.capability.unknown': '等待能力确认',
  'route.capability_short.full': '支持',
  'route.capability_short.partial': '兼容',
  'route.capability_short.unsupported': '不支持',
  'route.capability_short.unknown': '待确认',
  'route.database_fallback': '未选择库',
  'editor.task_name': '任务名称',
  'editor.task_name_placeholder': '例如：订单数据同步到分析库',
  'editor.source_endpoint': '源端点',
  'editor.target_endpoint': '目标端点',
  'editor.connection': '已保存连接',
  'editor.connection_id': '连接 ID',
  'editor.connection_name': '连接名称',
  'editor.database_type': '数据源类型',
  'editor.database': 'Database / Catalog',
  'editor.schema': 'Schema',
  'editor.source_query': '源 SQL 查询',
  'editor.source_query_placeholder': 'SELECT ...',
  'editor.endpoint_help': '从已保存连接中选择端点；任务只保存连接引用，不保存账号、密码或连接串。',
  'editor.guide.source_title': '第一步：选择源',
  'editor.guide.target_title': '第二步：选择目标',
  'editor.guide.target_locked': '先选好源连接，再配置目标。',
  'metadata.select_connection': '选择连接',
  'metadata.select_database': '选择 Database / Catalog',
  'metadata.not_selected': '未选择',
  'metadata.schema_optional': '可选；留空使用默认命名空间',
  'metadata.loading_connections': '正在加载连接',
  'metadata.loading_databases': '正在加载数据库',
  'metadata.loading_objects': '正在加载对象',
  'metadata.loading_fields': '正在加载字段',
  'metadata.loading_cdc_adapters': '正在识别源库的增量同步方式',
  'metadata.load_failed': '元数据加载失败',
  'metadata.retry': '重试',
  'metadata.no_eligible_connections': '没有符合当前读写方向的连接。',
  'metadata.no_databases': '该连接未返回数据库列表，草稿仍可保存。',
  'metadata.endpoint_required': '先选择端点',
  'metadata.object_required': '先选择对象',
  'metadata.objects_count': '{count} 个对象',
  'metadata.fields_count': '{count} 个字段',
  'mapping.title': '选择要同步的数据',
  'mapping.title_schema_compare': '选择要比对结构的表',
  'mapping.title_data_compare': '选择要比对数据的表',
  'mapping.help': '可选择一张、多张或筛选后的全部表。系统会自动匹配同名目标、识别主键并生成映射，你只需处理例外。',
  'mapping.help_schema_compare': '勾选要比对结构的表。系统按同名匹配目标，只比较结构，不会写入。',
  'mapping.help_data_compare': '勾选要比对数据的表。系统按同名匹配目标，只比较数据，不会写入。',
  'mapping.query_help': 'SQL 查询结果只写入一个目标对象；请选择已有目标表并配置写入键。',
  'mapping.add': '添加映射',
  'mapping.select_objects': '选择源对象',
  'mapping.add_source_objects': '添加源对象',
  'mapping.catalog_title': '可选表',
  'mapping.selected_source': '已选表',
  'mapping.write_to': '写入到',
  'mapping.write_to_compare': '比对对象',
  'mapping.none_selected_title': '还没有选择对象',
  'mapping.none_selected_desc': '在左侧勾选要同步的表，系统会自动匹配同名目标。',
  'mapping.none_selected_desc_compare': '在左侧勾选要比对的表，系统会自动匹配同名目标。',
  'mapping.add_target': '添加目标对象',
  'mapping.picker_title': '批量选择源对象',
  'mapping.search_objects': '搜索表、视图或集合',
  'mapping.include_views': '包含视图',
  'mapping.selected_count': '已选 {selected} / 共 {total}',
  'mapping.select_all': '全选（{count}）',
  'mapping.select_filtered': '全选当前筛选结果（{count}）',
  'mapping.selection_fixed_scope': '保存时固化本次清单，后续新增表不会自动加入',
  'mapping.object_kind.table': '表',
  'mapping.object_kind.view': '视图',
  'mapping.object_kind.collection': '集合',
  'mapping.already_added': '已添加',
  'mapping.rows_count': '{count} 行',
  'mapping.no_objects': '没有匹配的对象',
  'mapping.show_more': '再显示 {count} 个（剩余 {remaining}）',
  'mapping.add_selected': '添加 {count} 个对象',
  'mapping.detecting_keys': '正在识别主键…',
  'mapping.probe_running': '正在后台识别主键与字段',
  'mapping.probe_complete': '主键与字段识别完成',
  'mapping.probe_progress': '{completed} / {total}',
  'mapping.open_object_list': '展开对象列表',
  'mapping.will_create_named': '目标不存在，将创建“{name}”',
  'mapping.no_matching_objects': '没有匹配的已有对象',
  'mapping.remove': '删除',
  'mapping.enabled': '启用',
  'mapping.source': '源对象',
  'mapping.target': '目标对象',
  'mapping.target_mode': '目标不存在时',
  'mapping.key_columns': '用于识别同一行',
  'mapping.fields': '字段',
  'mapping.status': '状态',
  'mapping.create_or_reuse': '自动创建；已存在则校验后使用',
  'mapping.existing_only': '仅写入已有目标',
  'mapping.edit_exceptions': '编辑例外',
  'mapping.collapse_exceptions': '收起',
  'mapping.exceptions_caption': '{source} 的例外',
  'mapping.fields_count': '{count} 个字段',
  'mapping.fields_pending': '自动同名写入',
  'mapping.fields_automatic': '自动同名写入',
  'mapping.fields_automatic_help': '无需逐列配置；仅在字段改名或转换时编辑。',
  'mapping.fields_required': '需要确认同步字段',
  'mapping.fields_cdc_help': '持续同步必须明确目标字段，避免源端删字段后目标残留旧值。',
  'mapping.ready': '已配置',
  'mapping.needs_attention': '需处理',
  'mapping.target_hint.exists': '目标库里已经有这张表',
  'mapping.target_hint.create': '目标库里还没有这张表，同步时会自动建出来',
  'mapping.target_hint.missing': '目标库里没有这张表，而当前任务不允许新建',
  'mapping.target_hint.pending': '正在查看目标库里有没有这张表',
  'mapping.key_placeholder': '留空 = 自动按源表主键匹配',
  'mapping.key_detected': '已从源端元数据自动识别，可按需修改',
  'mapping.key_when_needed': '写入已有目标的新增或更新必须有源端物理主键；首次自动建表无需主键。持续增量同步仍需配置稳定键。',
  'mapping.source_placeholder': '搜索或选择源对象',
  'mapping.target_placeholder': '搜索已有目标或输入新名称',
  'mapping.query_result_source': '查询结果（唯一映射）',
  'mapping.target_state.exists': '目标库里已经有这张表',
  'mapping.target_state.create': '目标库里还没有这张表，同步时会自动建出来',
  'mapping.target_state.missing': '目标库里没有这张表，而当前任务不允许新建',
  'mapping.target_state.pending': '正在查看目标库里有没有这张表',
  'mapping.confirming': '系统确认中',
  'mapping.endpoints_required_title': '先完成源端和目标端',
  'mapping.endpoints_required_desc': '选择端点后，这里会加载源对象并准备目标匹配。',
  'mapping.loading_title': '正在加载可同步对象',
  'mapping.loading_desc': '正在读取源端和目标端元数据，请稍候。',
  'mapping.metadata_error_title': '暂时无法读取对象',
  'mapping.metadata_error_desc': '重新加载对象；若仍然失败，请返回检查端点和读取权限。',
  'mapping.no_source_objects_title': '源端没有可同步对象',
  'mapping.no_source_objects_desc': '检查所选数据库、模式和对象读取权限。',
  'mapping.retry_objects': '重新加载对象',
  'mapping.refresh_objects': '刷新对象列表',
  'mapping.empty_title': '尚未选择同步对象',
  'mapping.empty_desc': '先选择源对象。单表和多表使用同一个入口，也可以搜索后全选当前结果。',
  'field_mapping.title': '字段映射',
  'field_mapping.close': '收起',
  'field_mapping.auto_match': '同名自动匹配',
  'field_mapping.add': '添加字段',
  'field_mapping.empty_title': '尚未配置字段映射',
  'field_mapping.empty_desc': '加载两端字段后自动匹配，或手动添加并配置转换表达式。',
  'field_mapping.source': '源字段',
  'field_mapping.target': '目标字段',
  'field_mapping.transform': '转换表达式',
  'field_mapping.transform_placeholder': '留空表示直接写入',
  'field_mapping.transform_identity': '直接写入',
  'field_mapping.transform_argument': '参数 JSON（可选）',
  'field_mapping.type': '类型',
  'field_mapping.select_field': '选择字段',
  'field_mapping.remove': '删除',
  'delivery.title': '设置目标写入',
  'delivery.help': '选择目标端如何写入及处理失败行。多数任务保留默认值即可；高风险和专业参数只在适用时显示。',
  'delivery.write_mode': '写入模式',
  'delivery.write.none': '只读',
  'delivery.write.append': '追加',
  'delivery.write.append_desc': '每次运行都新增记录；重复运行可能产生重复数据，系统会自动关闭重试。',
  'delivery.write.upsert': '新增或更新',
  'delivery.write.upsert_unavailable': '新增或更新（当前目标不支持）',
  'delivery.write.upsert_desc': '按主键或唯一键识别同一行：不存在则新增，已存在则更新。',
  'delivery.write.overwrite': '覆盖',
  'delivery.write.overwrite_unavailable': '覆盖（当前任务系统暂不支持）',
  'delivery.write.overwrite_desc': '当前没有原子替换保障，预检会阻止覆盖任务运行；请改用新增或更新。',
  'delivery.read_only_title': '这是只读比较任务',
  'delivery.read_only_note': '任务只读取两端数据，不会写入或删除目标端数据，因此没有写入模式、失败行处理和调度设置。需要补齐结构差异时，请用比较结果里的“生成修复 SQL”，或在数据同步工作台新建结构同步任务。',
  'delivery.content_mode': '同步内容',
  'delivery.content.schema': '仅同步结构',
  'delivery.content.data': '仅同步数据',
  'delivery.content.both': '同步结构与数据',
  'delivery.schema_only_note': '此任务仅执行结构变更（例如补齐缺失字段），不会同步表内数据。',
  'delivery.error_policy': '失败行处理',
  'delivery.error.stop': '遇错停止',
  'delivery.error.stop_desc': '任一行写入失败时立即停止，适合优先保证数据完整性的任务。',
  'delivery.error.skip': '跳过错误行',
  'delivery.error.skip_desc': '记录失败原因并继续处理后续行，不保存完整失败行。',
  'delivery.error.quarantine': '隔离并允许重试',
  'delivery.error.quarantine_desc': '完整失败行会保存在本机任务数据库中，可能包含敏感数据，可在错误行列表中重试。',
  'delivery.batch_size': '批大小',
  'delivery.commit_every': '提交间隔（行）',
  'delivery.commit_every_note': '当前引擎按批大小提交，此值与批大小保持一致。',
  'delivery.retry_limit': '重试次数',
  'delivery.retry_backoff': '重试退避（毫秒）',
  'delivery.row_isolation_note': '当前配置必须遇错停止。逐行跳过只适用于写入已有关系表，且不能同时自动建表、修改结构、同步删除或覆盖写入。',
  'delivery.append_retry_note': '追加写入可能已部分落库，为避免重复写入，自动重试固定为 0。',
  'delivery.recovery_policy': '运行恢复',
  'delivery.recovery.never': '禁用恢复',
  'delivery.recovery.manual': '手动恢复',
  'delivery.recovery.auto': '自动恢复',
  'delivery.append_recovery_note': '追加写入可能已有批次提交，恢复固定禁用以避免重放已提交数据。',
  'delivery.append_only_target_note': '当前时序目标仅支持追加写入（INSERT）；更新和删除不会同步。',
  'delivery.propagate_deletes': '传播源端删除',
  'delivery.delete_policy_title': '目标端删除策略',
  'delivery.delete_risk_badge': '高风险',
  'delivery.delete.snapshot_label': '删除源端已不存在的目标行',
  'delivery.delete.snapshot_desc': '全量差异同步会按每张表的主键比对，并删除目标端中源端已不存在的行。',
  'delivery.delete.cdc_label': '同步源端删除事件',
  'delivery.delete.cdc_desc': '源端删除一行后，会按键删除目标端对应行。',
  'delivery.delete_risk_note': '目标端删除不可撤销。开启前请确认目标不是共享表，并在运行前核对预检范围。',
  'delivery.advanced': '高级设置',
  'delivery.advanced_help': '性能、重试与结构迁移',
  'delivery.performance_title': '性能与重试',
  'delivery.performance_help': '默认值适合多数任务；仅在明确了解目标端负载和幂等性时调整。',
  'delivery.structure_title': '目标结构',
  'delivery.structure_help': '一次性迁移、结构同步和差异同步（对账）任务可补齐目标端缺失字段；仅新增字段，不修改或删除已有字段，也不会自动建表。',
  'delivery.auto_add_columns': '自动新增缺失字段',
  'delivery.auto_add_columns_desc': '仅新增目标端缺少的字段，不修改或删除已有字段；执行 DDL 时可能短暂锁定目标表。',
  'delivery.create_indexes': '同步表附属对象',
  'delivery.create_indexes_desc': '自动建表时复制源表的二级索引、归属序列、触发器和字段注释。独立序列、函数、视图不会随表迁移。',
  'trigger.title': '设置运行方式',
  'trigger.help': '选择手动、定时或持续运行，并按需要配置快照、水位线或变更日志增量。',
  'trigger.mode': '触发方式',
  'trigger.manual': '手动',
  'trigger.once': '指定时间',
  'trigger.interval': '固定间隔',
  'trigger.interval_seconds': '间隔（秒）',
  'trigger.cron': 'Cron 调度',
  'trigger.continuous': '持续运行',
  'trigger.run_at': '执行时间',
  'trigger.timezone': '时区',
  'trigger.cron_expression': 'Cron 表达式',
  'trigger.cron_expression_hint': '5 段格式：分 时 日 月 周，例如 0 3 * * *（每天 03:00），不支持秒。',
  'trigger.overlap': '任务重叠时',
  'trigger.overlap.skip': '跳过本次',
  'trigger.overlap.queue': '排队等待',
  'incremental.mode': '增量策略',
  'incremental.snapshot': '全量快照',
  'incremental.watermark': '水位线',
  'incremental.cdc': '变更日志',
  'incremental.watermark_column': '水位列',
  'incremental.tie_breaker': '并列排序列',
  'incremental.overlap_window': '重叠窗口（毫秒）',
  'incremental.watermark_delivery_note': '水位线任务暂不支持追加语义；InitialValue、重叠窗口和独立提交间隔尚未接入引擎，因此不提供可编辑入口。',
  'incremental.watermark_mixed_note': '此任务包含按对象配置的不同水位字段。当前显示第一项；编辑任一水位字段会统一全部对象。',
  'incremental.initial_snapshot': '首次启动先执行全量快照',
  'incremental.cdc_adapter': '增量方式',
  'incremental.select_cdc_adapter': '由源库类型自动选择',
  'incremental.cdc_probe_ready': '已确认当前连接、权限和部署方式支持自动选择的增量同步。',
  'incremental.cdc_probe_unready': '自动选择的增量同步方式当前还不能用。',
  'incremental.start_position': '开始位置',
  'incremental.position.latest': '最新位置',
  'incremental.position.earliest': '最早位置',
  'incremental.position.checkpoint': '上次进度',
  'incremental.cdc_safety_title': '增量起点说明',
  'incremental.cdc_safety_note': '目前只能从“现在之后的新变更”开始，或从本任务上次记下的进度继续。同一条变更有可能被处理不止一次。',
  'incremental.cdc_snapshot_gap_warning': '如果先单独做一次全量，再从最新位置启动，中间这段时间的变更可能漏掉。',
  'incremental.cdc_checkpoint_unavailable': '当前任务还没有可继续的同步进度，因此不能从上次进度开始。',
  'preflight.title': '预检',
  'preflight.stale': '配置已变化，需要重新预检',
  'preflight.not_run': '尚未预检',
  'preflight.running': '正在检查端点、映射和执行策略',
  'preflight.blocked': '{count} 个阻断项',
  'preflight.warning': '{count} 个警告',
  'preflight.passed': '预检通过',
  'preflight.empty': '配置完整后运行预检；问题会定位到对应阶段。',
  'preflight.open_issue': '定位',
  'preflight.current_revision': '基于任务版本 {revision}',
  'preflight.approval_required': '生产写入需要审批',
  'preflight.approval_not_required': '无需生产写入审批',
  'preflight.approval_fail_closed': '尚未完成倒计时确认并取得一次性授权，保存到生产或运行操作保持禁用。',
  'preflight.approval_granted': '一次性生产授权已取得',
  'preflight.approval_begin_countdown': '开始服务端 10 秒确认',
  'preflight.approval_beginning': '正在创建服务端确认',
  'preflight.approval_countdown': '请等待 {seconds} 秒',
  'preflight.approval_confirm': '确认生产写入并获取授权',
  'preflight.approving': '正在获取授权',
  'preflight.approval_expires': '授权仅保存在内存中，将于 {expiresAt} 失效，保存或运行后立即作废。',
  'preflight.severity.blocker': '阻断',
  'preflight.severity.warning': '警告',
  'preflight.severity.info': '提示',
  'preflight.index_remediation.title': '未迁移索引（{count}）',
  'preflight.index_remediation.columns': '列：{columns}',
  'preflight.index_remediation.copy': '复制补救 DDL',
  'preflight.index_remediation.copy_failed': '复制失败，请从下方清单手动复制 DDL。',
  'runs.title': '运行记录',
  'runs.subtitle': '查看每次运行的状态和结果。进行中的阶段和事件会自动更新。',
  'runs.subtitle_compare': '查看每次比对的状态和结果。进行中的阶段和事件会自动更新。',
  'runs.empty_title': '还没有运行记录',
  'runs.empty_desc': '保存并运行任务后，这里会显示写入量、失败情况和同步进度。',
  'runs.empty_desc_compare': '保存并开始比对后，这里会显示比对结果。',
  'runs.id': '运行 ID',
  'runs.task': '任务',
  'runs.status': '状态',
  'runs.started_at': '开始时间',
  'runs.rows_written': '写入行数',
  'runs.rows_failed': '错误行',
  'runs.checkpoint': '同步进度',
  'runs.view_errors': '查看错误行',
  'runs.view_details': '查看运行详情',
  'runs.back_to_list': '返回运行记录',
  'runs.actions': '操作',
  'runs.cancel': '取消',
  'runs.resume': '继续',
  'runs.retry': '重试运行',
  'runs.delete': '删除记录',
  'runs.clear_terminal': '清除已结束记录',
  'runs.pagination': '运行记录分页',
  'runs.page': '第 {page} 页',
  'runs.page_size': '每页',
  'runs.total': '共 {total} 条',
  'runs.previous_page': '上一页',
  'runs.next_page': '下一页',
  'runs.delete_confirm': '删除此运行记录及其错误行、事件明细？此操作不会删除同步进度。',
  'runs.clear_terminal_confirm': '清除全部已结束运行记录及其错误行、事件明细？此操作不会删除同步进度。',
  'runs.delete_confirm_title': '删除运行记录',
  'runs.clear_terminal_confirm_title': '清除已结束记录',
  'events.title': '事件时间线',
  'events.title_secondary': '运行过程',
  'events.select_run': '选择运行记录以查看事件。',
  'events.empty': '该运行暂无持久化事件。',
  'errors.title': '错误行',
  'errors.empty_title': '没有隔离的错误行',
  'errors.empty_desc': '选择失败运行后，可在这里查看、重试或导出错误行。',
  'errors.task_failure_title': '本次运行在任务级失败',
  'errors.task_failure_desc': '该失败发生在处理单行之前，未生成可重试的错误行。请修正任务配置后重新运行。',
  'errors.source': '源对象',
  'errors.reason': '原因',
  'errors.payload': '数据预览',
  'errors.retryable': '可重试',
  'errors.retry': '重试行',
  'errors.retry_unavailable': '后端尚未提供错误行重试接口，此操作保持禁用。',
  'errors.discard': '丢弃',
  'errors.discarded': '已丢弃',
  'compare.title': '比较结果',
  'compare.empty': '所选运行没有可展示的比较结果。',
  'compare.table': '表',
  'compare.inserts': '新增',
  'compare.updates': '更新',
  'compare.deletes': '删除',
  'compare.same': '相同',
  'compare.same_rows': '共 {count} 行',
  'compare.schema_diff': '结构差异',
  'compare.status_same': '相同',
  'compare.status_diff': '有差异',
  'compare.status_blocked': '无法比较',
  'compare.source': '源',
  'compare.target': '目标',
  'compare.missing_columns': '目标缺失字段',
  'compare.schema_warning':
    '两端表结构存在 {count} 处差异；本次为仅数据对比，未展开结构明细。切换到「仅表结构」或「数据和表结构」可查看，同步执行前需先补齐目标表结构。',
  'compare.diff_kind.missing_in_target': '目标缺失',
  'compare.diff_kind.extra_in_target': '目标多出',
  'compare.diff_kind.type': '类型不同',
  'compare.diff_kind.nullable': '可空性不同',
  'compare.actions.repair_sql': '生成修复 SQL',
  'compare.actions.ai_sql': 'AI 分析差异',
  'compare.actions.sync_diff': '同步差异',
  'compare.repair_sql_tab': '比对修复 SQL',
  'compare.sync_task_name': '{name} · 差异同步',
  'checkpoint.title': '同步进度',
  'checkpoint.empty': '所选运行没有保存同步进度。',
  'checkpoint.kind': '类型',
  'checkpoint.phase': '阶段',
  'checkpoint.updated_at': '更新时间',
  'checkpoint.cursor': '进度位置',
  'checkpoint.reset': '重置同步进度',
  'checkpoint.reset_confirm_title': '重置同步进度',
  'checkpoint.reset_warning': '重置后不能从该位置继续；持续增量同步只能从重置之后的新变更开始。',
  'common.yes': '是',
  'common.no': '否',
  'common.refresh': '刷新',
  'common.dismiss': '关闭',
  'common.details': '查看详情',
  'common.retry': '重试',
  'common.cancel': '取消',
  ...dataSyncScheduleTextsZhCN, ...dataSyncRunEventTextsZhCN,
  ...dataSyncValidationTextsZhCN,
  'cdc.title': '持续同步状态',
  'cdc.subtitle': '这里显示源库是否已准备好持续同步，以及任务当前进度。后端没上报延迟时不会猜测。',
  'cdc.empty_title': '还没有可监控的持续同步源',
  'cdc.empty_desc': '创建持续增量同步任务并完成权限检查后，这里会显示健康状态。',
  'cdc.lag_unknown': '延迟未上报',
  'cdc.status.ready': '已就绪',
  'cdc.status.probing': '正在探测',
  'cdc.status.lagging': '延迟较高',
  'cdc.status.offline': '源端离线',
  'cdc.status.unsupported': '不支持',
  'cdc.status.unknown': '状态未知',
  'status.queued': '排队中',
  'status.running': '运行中',
  'status.cancelling': '正在取消',
  'status.preflighting': '预检中',
  'status.snapshotting': '快照中',
  'status.catching_up': '追赶中',
  'status.streaming': '持续同步',
  'status.paused': '已暂停',
  'status.succeeded': '成功',
  'status.partial': '部分完成',
  'status.failed': '失败',
  'status.canceled': '已取消',
  'status.cancelled': '已取消',
  'status.interrupted': '已中断',
} as const;

export type DataSyncWorkbenchTextKey = keyof typeof zhCN;
