/**
 * Validation-issue copy owned by the data sync workbench. Kept beside the
 * validation contract so the main catalog does not absorb these keys;
 * `text.ts` spreads both maps into its language catalogs.
 */
export const dataSyncValidationTextsZhCN = {
  'validation.definition_invalid': '任务定义无效，请检查必填项、对象映射和执行策略。',
  'validation.definition_hash_failed': '无法生成任务定义指纹，请检查任务配置。',
  'validation.task_name_required': '填写任务名称。',
  'validation.source_connection_required': '选择源连接。',
  'validation.target_connection_required': '选择目标连接。',
  'validation.source_connection_failed': '无法解析源连接，请确认已保存连接仍存在且配置完整。',
  'validation.target_connection_failed': '无法解析目标连接，请确认已保存连接仍存在且配置完整。',
  'validation.source_connect_failed': '无法初始化源数据库连接。',
  'validation.source_ping_failed': '源数据库连通性检查失败。',
  'validation.target_connect_failed': '无法初始化目标数据库连接。',
  'validation.target_ping_failed': '目标数据库连通性检查失败。',
  'validation.same_endpoint': '源端和目标端指向同一个位置，请确认不会覆盖源数据。',
  'validation.same_object': '源对象和目标对象指向同一个物理对象，不能执行同步。',
  'validation.route_unsupported': '当前源端与目标端组合不支持执行此同步任务。',
  'validation.source_query_required': '填写源 SQL 查询。',
  'validation.source_query_not_read_only': '源 SQL 必须是单条只读查询。',
  'validation.mapping_required': '至少启用一条对象映射。',
  'validation.source_object_required': '填写源对象名称。',
  'validation.target_object_required': '填写目标对象名称。',
  'validation.duplicate_source_object': '同一个源对象只能添加一次。',
  'validation.duplicate_target_object': '多个映射指向同一个目标对象。',
  'validation.mapping_compile_failed': '对象或字段映射无法编译，请检查映射与转换配置。',
  'validation.source_columns_failed': '读取源对象字段失败，请检查对象名和元数据权限。',
  'validation.target_columns_failed': '读取目标对象字段失败，请检查对象名和元数据权限。',
  'validation.source_column_missing': '配置的源字段不存在。',
  'validation.target_column_missing': '配置的目标字段不存在。',
  'validation.key_column_missing': '配置的源端主键或唯一键字段不存在。',
  'validation.watermark_column_missing': '配置的水位列在源对象中不存在。',
  'validation.target_table_check_failed': '检查目标表是否存在时失败。',
  'validation.target_table_missing': '目标表不存在，且当前任务不能自动创建该表。',
  'validation.target_table_will_be_created': '目标表不存在，运行时将由迁移规划器自动创建。',
  'validation.target_columns_missing_for_sync': '目标表缺少同步所需字段。请补齐字段、启用结构同步的自动补列，或改用明确的字段映射。',
  'validation.target_columns_will_be_added': '目标表缺少字段，运行时将按源字段自动补齐。',
  'validation.key_columns_required': '差异同步或持续增量同步必须配置主键或唯一键。',
  'validation.source_primary_key_required': '写入已有目标的新增或更新必须使用源端物理主键；自动建表的首次导入不受此限制。',
  'validation.source_primary_key_must_be_used': '写入已有目标时，配置的稳定键必须完整等于源端物理主键，不能使用业务字段替代。',
  'validation.structure_migration_primary_key_required': '当前结构迁移路径只能使用源端物理主键；配置的业务稳定键不会参与更新。',
  'validation.mapping_key_unmapped': '稳定键必须映射到目标字段。',
  'validation.mapping_key_target_missing': '稳定键映射到了不存在的目标字段。',
  'validation.batch_size_invalid': '批大小必须是 1 到 10000 的整数。',
  'validation.commit_every_invalid': '提交间隔必须不小于批大小。',
  'validation.target_protection_blocked': '目标连接的安全保护策略禁止此次写入。',
  'validation.row_error_isolation_unsupported': '当前任务不满足逐行跳过/隔离的安全条件。',
  'validation.append_retry_unsupported': '追加写入不允许自动重试，以免重复写入。',
  'validation.append_retry_unsafe': '追加写入不能自动重试，否则可能重复写入已提交的数据。',
  'validation.append_resume_unsafe': '追加写入任务必须禁用断点恢复，否则可能重放已提交批次。',
  'validation.full_overwrite_non_atomic': '持久任务暂不支持非原子全量覆盖，以免失败后留下空表或半表。',
  'validation.write_mode_required': '可执行同步任务必须选择明确的写入模式。',
  'validation.watermark_append_unsupported': '水位线任务暂不支持追加写入语义。',
  'validation.watermark_tie_breaker_required': '水位线任务必须配置稳定的并列排序列或主键。',
  'validation.watermark_initial_value_unsupported': '当前尚未实现水位初始值，请移除该配置。',
  'validation.watermark_runtime_unsupported': '当前源端、目标端或执行策略不满足水位线同步条件。',
  'validation.watermark_overwrite_unsupported': '水位线任务不支持全量覆盖。',
  'validation.watermark_delete_unsupported': '水位线任务无法推断源端删除；请改用持续增量同步或快照差异同步。',
  'validation.query_sink_single_mapping_required': 'SQL 结果写入必须且只能配置一条目标映射。',
  'validation.query_key_required': 'SQL 结果更新写入必须配置至少一个映射到目标字段的稳定键。',
  'validation.query_key_unmapped': 'SQL 结果的稳定键必须映射到目标字段。',
  'validation.query_key_target_missing': 'SQL 结果的稳定键映射到了不存在的目标字段。',
  'validation.query_key_target_non_unique': 'SQL 结果的稳定键必须映射到目标表的主键或唯一索引。',
  'validation.query_schema_probe_failed': '无法读取 SQL 查询的结果字段。请检查 SQL 语法、字段别名和源端查询权限。',
  'validation.schema_unsupported_difference': '目标表存在当前无法自动修复的字段类型或可空性差异。',
  'validation.query_source_column_missing': 'SQL 查询结果中不存在已配置的源字段。请为查询列设置正确别名，或修改字段映射。',
  'validation.watermark_column_required': '水位线模式必须配置水位列。',
  'validation.cron_expression_required': '填写 Cron 表达式。',
  'validation.cron_expression_field_count': 'Cron 表达式必须是 5 段：分 时 日 月 周，不要包含秒。',
  'validation.cron_expression_invalid': 'Cron 表达式格式或取值范围不正确，请按“分 时 日 月 周”检查。',
  'validation.timezone_required': '填写调度时区。',
  'validation.interval_invalid': '固定间隔必须不少于 60 秒。',
  'validation.cdc_incremental_required': '持续增量同步必须使用变更日志增量策略。',
  'validation.cdc_trigger_required': '持续增量同步必须持续运行。',
  'validation.cdc_adapter_unavailable': '当前源库类型还不支持持续增量同步。',
  'validation.cdc_initial_snapshot_unsupported': '当前持续增量同步不支持安全地先做全量再接上增量。',
  'validation.cdc_initial_snapshot_handoff_unsupported': '当前持续增量同步无法保证全量和后续增量无缝衔接，请关闭首次全量快照。',
  'validation.cdc_earliest_unsupported': '当前源库不支持从最早位置开始持续增量同步。',
  'validation.cdc_probe_failed': '持续增量同步的能力和权限检查失败。',
  'validation.cdc_adapter_not_ready': '当前选择的增量同步方式还不能用。',
  'validation.cdc_existing_target_required': '持续增量同步当前只能写入已存在的目标表。',
  'validation.cdc_upsert_required': '持续增量同步必须使用“新增或更新”写入模式，这样中断后才能安全继续。',
  'validation.cdc_target_non_atomic': '持续增量同步要求目标端支持原子关系型写入，才能按行隔离并按顺序记住进度。',
  'validation.cdc_authoritative_columns_required': '持续增量同步必须显式配置源字段到目标字段的映射。',
  'validation.cdc_checkpoint_unavailable': '无法读取持续增量同步进度。',
  'validation.cdc_checkpoint_required': '要从上次进度继续，必须先有兼容的已保存进度。',
  'validation.cdc_checkpoint_incompatible': '已保存的同步进度与当前任务定义不兼容，请先暂停任务再显式重置进度。',
  'validation.compare_route_unsupported': '当前源端与目标端组合不支持执行数据比对。',
  'validation.index_inspection_failed': '无法读取源端索引元数据，不能确认所有索引都已迁移。',
  'validation.unmigrated_index': '有索引无法自动迁移，请在执行前审核候选补救 DDL。',
  'validation.capability_unverified': '当前使用静态 gateway，运行前仍需后端确认数据源组合能力。',
  'validation.unknown': '预检发现未识别的配置问题。',
} as const;

export type DataSyncValidationTextKey = keyof typeof dataSyncValidationTextsZhCN;

export const dataSyncValidationTextsEnUS: Record<DataSyncValidationTextKey, string> = {
  'validation.definition_invalid': 'The task definition is invalid. Check required fields, object mappings, and execution policies.',
  'validation.definition_hash_failed': 'The task definition fingerprint could not be generated. Check the task configuration.',
  'validation.task_name_required': 'Enter a task name.',
  'validation.source_connection_required': 'Choose a source connection.',
  'validation.target_connection_required': 'Choose a target connection.',
  'validation.source_connection_failed': 'The source saved connection could not be resolved. Verify that it still exists and is complete.',
  'validation.target_connection_failed': 'The target saved connection could not be resolved. Verify that it still exists and is complete.',
  'validation.source_connect_failed': 'The source database connection could not be initialized.',
  'validation.source_ping_failed': 'The source database connectivity check failed.',
  'validation.target_connect_failed': 'The target database connection could not be initialized.',
  'validation.target_ping_failed': 'The target database connectivity check failed.',
  'validation.same_endpoint': 'Source and target point to the same location. Confirm that source data cannot be overwritten.',
  'validation.same_object': 'Source and target resolve to the same physical object, so this sync cannot run.',
  'validation.route_unsupported': 'The selected source-target route cannot execute this sync task.',
  'validation.source_query_required': 'Enter the source SQL query.',
  'validation.source_query_not_read_only': 'The source SQL must be one read-only query.',
  'validation.mapping_required': 'Enable at least one object mapping.',
  'validation.source_object_required': 'Enter a source object name.',
  'validation.target_object_required': 'Enter a target object name.',
  'validation.duplicate_source_object': 'Each source object can be added only once.',
  'validation.duplicate_target_object': 'Multiple mappings target the same object.',
  'validation.mapping_compile_failed': 'The object or field mapping could not be compiled. Check mappings and transforms.',
  'validation.source_columns_failed': 'Source fields could not be read. Check the object name and metadata permissions.',
  'validation.target_columns_failed': 'Target fields could not be read. Check the object name and metadata permissions.',
  'validation.source_column_missing': 'A configured source field does not exist.',
  'validation.target_column_missing': 'A configured target field does not exist.',
  'validation.key_column_missing': 'A configured source key field does not exist.',
  'validation.watermark_column_missing': 'The configured watermark field does not exist on the source object.',
  'validation.target_table_check_failed': 'The target table existence check failed.',
  'validation.target_table_missing': 'The target table does not exist and this task cannot create it automatically.',
  'validation.target_table_will_be_created': 'The target table does not exist and will be created by the migration planner.',
  'validation.target_columns_missing_for_sync': 'The target is missing fields required for this sync. Add them, enable schema-sync auto-add, or use an explicit field mapping.',
  'validation.target_columns_will_be_added': 'The target is missing fields that will be added from the source during execution.',
  'validation.key_columns_required': 'Difference sync and CDC require a primary or unique key.',
  'validation.source_primary_key_required': 'Upsert into an existing target requires a source physical primary key; an initial auto-create import is exempt.',
  'validation.source_primary_key_must_be_used': 'Upsert into an existing target must use the complete source physical primary key; a business key cannot replace it.',
  'validation.structure_migration_primary_key_required': 'This schema migration route only supports source physical primary keys; configured business keys are not used for updates.',
  'validation.mapping_key_unmapped': 'Each stable key must map to a target field.',
  'validation.mapping_key_target_missing': 'A stable key maps to a target field that does not exist.',
  'validation.batch_size_invalid': 'Batch size must be an integer from 1 to 10000.',
  'validation.commit_every_invalid': 'Commit interval must be at least the batch size.',
  'validation.target_protection_blocked': 'The target connection protection policy blocks this write.',
  'validation.row_error_isolation_unsupported': 'This task does not meet the safety requirements for row skip or quarantine.',
  'validation.append_retry_unsupported': 'Append writes cannot retry automatically because that could duplicate rows.',
  'validation.append_retry_unsafe': 'Append writes cannot retry automatically because committed rows could be duplicated.',
  'validation.append_resume_unsafe': 'Append jobs must disable resume because committed batches cannot be replayed safely.',
  'validation.full_overwrite_non_atomic': 'Persistent jobs cannot use non-atomic full overwrite because failure could leave an empty or partial table.',
  'validation.write_mode_required': 'Executable sync tasks require an explicit write mode.',
  'validation.watermark_append_unsupported': 'Watermark jobs do not yet support append delivery semantics.',
  'validation.watermark_tie_breaker_required': 'Watermark jobs require a stable tie-breaker field or key.',
  'validation.watermark_initial_value_unsupported': 'Watermark initial values are not implemented. Remove this setting.',
  'validation.watermark_runtime_unsupported': 'The selected source, target, or execution policy cannot run watermark sync.',
  'validation.watermark_overwrite_unsupported': 'Watermark jobs cannot use full overwrite.',
  'validation.watermark_delete_unsupported': 'Watermark jobs cannot infer source deletes. Use CDC or snapshot reconcile.',
  'validation.query_sink_single_mapping_required': 'A SQL result sink must have exactly one target mapping.',
  'validation.query_key_required': 'SQL result upsert requires at least one stable key mapped to a target field.',
  'validation.query_key_unmapped': 'Each SQL result stable key must map to a target field.',
  'validation.query_key_target_missing': 'A SQL result stable key maps to a target field that does not exist.',
  'validation.query_key_target_non_unique': 'A SQL result stable key must map to a primary or unique target index.',
  'validation.query_schema_probe_failed': 'The SQL query result fields could not be read. Check query syntax, column aliases, and source query permissions.',
  'validation.schema_unsupported_difference': 'The target has column type or nullability differences that cannot be repaired automatically.',
  'validation.query_source_column_missing': 'A configured source field is absent from the SQL query result. Add the correct column alias or update the field mapping.',
  'validation.watermark_column_required': 'Watermark mode requires a watermark column.',
  'validation.cron_expression_required': 'Enter a Cron expression.',
  'validation.cron_expression_field_count': 'A Cron expression needs exactly five fields — minute hour day month weekday — with no seconds field.',
  'validation.cron_expression_invalid': 'The Cron expression has an invalid format or out-of-range value. Check it as "minute hour day month weekday".',
  'validation.timezone_required': 'Enter a scheduling timezone.',
  'validation.interval_invalid': 'Fixed intervals must be at least 60 seconds.',
  'validation.cdc_incremental_required': 'CDC tasks must use the CDC incremental policy.',
  'validation.cdc_trigger_required': 'CDC tasks must run continuously.',
  'validation.cdc_adapter_unavailable': 'No implemented CDC adapter is available for the source type.',
  'validation.cdc_initial_snapshot_unsupported': 'The current CDC reader cannot safely hand off from an initial snapshot.',
  'validation.cdc_initial_snapshot_handoff_unsupported': 'The current CDC reader cannot guarantee a gap-free initial snapshot handoff. Disable initial snapshot.',
  'validation.cdc_earliest_unsupported': 'The current CDC adapter cannot start from the earliest position.',
  'validation.cdc_probe_failed': 'CDC capability and permission probing failed.',
  'validation.cdc_adapter_not_ready': 'The selected CDC adapter is not ready.',
  'validation.cdc_existing_target_required': 'CDC jobs currently require existing target tables.',
  'validation.cdc_upsert_required': 'CDC jobs must use upsert delivery so events can be replayed safely.',
  'validation.cdc_target_non_atomic': 'CDC row isolation and checkpoint ordering require an atomic relational target.',
  'validation.cdc_authoritative_columns_required': 'CDC jobs require explicit source-to-target field mappings.',
  'validation.cdc_checkpoint_unavailable': 'The CDC checkpoint could not be read.',
  'validation.cdc_checkpoint_required': 'Checkpoint start requires a compatible durable checkpoint for this task.',
  'validation.cdc_checkpoint_incompatible': 'The stored CDC checkpoint is incompatible with this task. Pause the task and reset it explicitly.',
  'validation.compare_route_unsupported': 'The selected source-target route cannot execute compare tasks.',
  'validation.index_inspection_failed': 'Source index metadata could not be read, so complete index migration cannot be verified.',
  'validation.unmigrated_index': 'An index could not be migrated automatically. Review the remediation DDL before execution.',
  'validation.capability_unverified': 'This task uses the static gateway. The backend must still verify the source-target capability before execution.',
  'validation.unknown': 'Preflight found an unrecognized configuration issue.',
};
