import { backupTexts } from './textBackup';
import { dataSyncScheduleTextsEnUS, dataSyncRunEventTextsEnUS } from './textSchedules';
import { dataSyncValidationTextsEnUS } from './textValidation';
import type { DataSyncWorkbenchTextKey } from './textZhCN';

export const enUS: Record<DataSyncWorkbenchTextKey, string> = {
  ...backupTexts('en-US'),
  'workbench.title': 'Data migration and sync',
  'workbench.title_short': 'Data sync',
  'workbench.title_compare': 'Data compare',
  'workbench.title_compare_short': 'Data compare',
  'workbench.title_schema_compare': 'Schema compare',
  'workbench.title_data_compare': 'Data compare',
  'workbench.subtitle': 'Define, validate, and track cross-source jobs',
  'workbench.subtitle_compare': 'Read-only comparison of schema or data; the target is never written',
  'workbench.subtitle_schema_compare': 'Read-only schema comparison; the target is never written',
  'workbench.subtitle_data_compare': 'Read-only data comparison; the target is never written',
  'workbench.start_compare': 'Start compare',
  'workbench.service_unavailable': 'The data sync service is not loaded. Reopen the workbench or retry.',
  'workbench.definition_changed_retry': 'The task changed during this operation. Review it and try again.',
  'workbench.close': 'Close workbench',
  'workbench.new_task': 'New task',
  'workbench.save': 'Save draft',
  'workbench.saving': 'Saving',
  'workbench.saved': 'Saved',
  'workbench.unsaved': 'Unsaved changes',
  'workbench.run_preflight': 'Run preflight',
  'workbench.preflighting': 'Running preflight',
  'workbench.start': 'Run task',
  'workbench.create_schema_sync': 'Create schema sync task',
  'workbench.enable': 'Enable task',
  'workbench.blocked_action': 'Resolve preflight blockers first',
  'workbench.delete': 'Delete task',
  'workbench.deleting': 'Deleting…',
  'workbench.delete_confirm_title': 'Delete task',
  'workbench.delete_confirm':
    'Permanently delete this task? Its runs, checkpoints, and error rows will be removed together, and this cannot be undone.',
  'workbench.lifecycle_before_run': 'Save the draft as ready before running it',
  'workbench.save_before_run': 'Current preflight passed; save the task first',
  'workbench.preflight_then_save_before_run': 'Run preflight before saving the task',
  'workbench.preflight_before_run': 'Run preflight and confirm the task revision before starting',
  'workbench.capability_before_run': 'Source capability is still resolving; try again shortly',
  'workbench.approval_before_run': 'Complete production write approval first',
  'workbench.previous_step': 'Previous',
  'workbench.next_step': 'Next: {stage}',
  'workbench.return_to_stage': 'Fix: {stage}',
  'workbench.current_step': 'Step {current} of {total}',
  'workbench.task_actions': 'Task actions',
  'workbench.task_list_toggle': 'Task list',
  'workbench.stage_ready': 'Configured',
  'workbench.stage_pending': 'Pending',
  'workbench.view_navigation': 'Workbench views',
  'workbench.task_steps': 'Task configuration steps',
  'nav.tasks': 'Tasks',
  'nav.runs': 'Runs',
  'nav.schedules': 'Schedules',
  'nav.cdc': 'CDC',
  'task_list.title': 'Tasks',
  'task_list.search': 'Search tasks',
  'task_list.empty': 'No matching tasks',
  'task_list.revision': 'Revision {revision}',
  'task_list.lifecycle.draft': 'Draft',
  'task_list.lifecycle.ready': 'Ready',
  'task_list.lifecycle.enabled': 'Enabled',
  'task_list.lifecycle.paused': 'Paused',
  'task_list.lifecycle.archived': 'Archived',
  'lifecycle.enable_schedule': 'Enable schedule',
  'lifecycle.pause': 'Pause task',
  'lifecycle.resume_schedule': 'Re-enable',
  'lifecycle.archive': 'Archive',
  'lifecycle.restore': 'Restore',
  'task_kind.title': 'Choose a task type',
  'task_kind.subtitle': 'The type determines incremental and trigger options. You can copy it into another task later.',
  'task_kind.subtitle_compare': 'Choose schema or data comparison. Compare tasks never write to the target.',
  'task_kind.migration': 'One-time migration',
  'task_kind.migration_desc': 'Move schema and data, with target object creation.',
  'task_kind.schema_sync': 'Schema sync',
  'task_kind.reconcile': 'Batch / difference sync',
  'task_kind.reconcile_desc': 'Compare snapshots or use a watermark by key.',
  'task_kind.querySink': 'SQL result sink',
  'task_kind.querySink_desc': 'Run a query and write its stable result to a target table.',
  'task_kind.compare': 'Read-only compare',
  'task_kind.compare_desc': 'Compare schema or data without changing the target.',
  'task_kind.compare_schema': 'Schema compare',
  'task_kind.compare_schema_desc': 'Read-only schema comparison; the target is never written.',
  'task_kind.compare_data': 'Data compare',
  'task_kind.compare_data_desc': 'Read-only data comparison; the target is never written.',
  'task_kind.cdc': 'Continuous CDC',
  'task_kind.cdc_desc': 'Consume change logs and persist checkpoints.',
  'stage.endpoints': 'Choose source and target',
  'stage.mappings': 'Choose data',
  'stage.mappings_schema_compare': 'Choose objects',
  'stage.mappings_data_compare': 'Choose objects',
  'stage.delivery': 'Target writes',
  'stage.trigger': 'Run settings',
  'stage.preflight': 'Check and run',
  'stage.preflight_compare': 'Check and compare',
  'stage_short.endpoints': 'Endpoints',
  'stage_short.mappings': 'Data',
  'stage_short.delivery': 'Writes',
  'stage_short.trigger': 'Run',
  'stage_short.preflight': 'Check',
  'route.summary': 'Sync route',
  'route.summary_compare': 'Compare path',
  'route.source': 'Source',
  'route.target': 'Target',
  'route.edit': 'Edit endpoints',
  'route.choose': 'Choose endpoints',
  'route.missing_both': 'Source and target are not selected',
  'route.missing_source': 'Source is not selected',
  'route.missing_target': 'Target is not selected',
  'route.pending_source': 'Choose source connection',
  'route.pending_target': 'Choose target connection',
  'route.capability.full': 'Full support',
  'route.capability.partial': 'Compatibility mode',
  'route.capability.unsupported': 'Unsupported',
  'route.capability.unknown': 'Awaiting capability check',
  'route.capability_short.full': 'Ready',
  'route.capability_short.partial': 'Compat',
  'route.capability_short.unsupported': 'Unsupported',
  'route.capability_short.unknown': 'Pending',
  'route.database_fallback': 'No database selected',
  'editor.task_name': 'Task name',
  'editor.task_name_placeholder': 'For example: Sync orders to analytics',
  'editor.source_endpoint': 'Source endpoint',
  'editor.target_endpoint': 'Target endpoint',
  'editor.connection': 'Saved connection',
  'editor.connection_id': 'Connection ID',
  'editor.connection_name': 'Connection name',
  'editor.database_type': 'Source type',
  'editor.database': 'Database / Catalog',
  'editor.schema': 'Schema',
  'editor.source_query': 'Source SQL query',
  'editor.source_query_placeholder': 'SELECT ...',
  'editor.endpoint_help': 'Choose from saved connections. Tasks store only connection references, never usernames, passwords, or connection strings.',
  'editor.guide.source_title': 'Step 1: Choose the source',
  'editor.guide.target_title': 'Step 2: Choose the target',
  'editor.guide.target_locked': 'Select a source connection before configuring the target.',
  'metadata.select_connection': 'Choose a connection',
  'metadata.select_database': 'Choose a database / catalog',
  'metadata.not_selected': 'Not selected',
  'metadata.schema_optional': 'Optional; blank uses the default namespace',
  'metadata.loading_connections': 'Loading connections',
  'metadata.loading_databases': 'Loading databases',
  'metadata.loading_objects': 'Loading objects',
  'metadata.loading_fields': 'Loading fields',
  'metadata.loading_cdc_adapters': 'Detecting the CDC adapter for the source type',
  'metadata.load_failed': 'Metadata failed to load',
  'metadata.retry': 'Retry',
  'metadata.no_eligible_connections': 'No connection supports this read/write direction.',
  'metadata.no_databases': 'This connection returned no databases. The draft can still be saved.',
  'metadata.endpoint_required': 'Choose an endpoint first',
  'metadata.object_required': 'Choose an object first',
  'metadata.objects_count': '{count} objects',
  'metadata.fields_count': '{count} fields',
  'mapping.title': 'Choose data to sync',
  'mapping.title_schema_compare': 'Choose tables to compare schema',
  'mapping.title_data_compare': 'Choose tables to compare data',
  'mapping.help': 'Choose one, many, or all filtered tables. The workbench matches same-name targets, detects keys, and generates mappings so you only handle exceptions.',
  'mapping.help_schema_compare': 'Check tables whose schema should be compared. Same-name targets are matched. Nothing is written.',
  'mapping.help_data_compare': 'Check tables whose data should be compared. Same-name targets are matched. Nothing is written.',
  'mapping.query_help': 'A SQL query writes to one target object. Choose an existing target table and configure the write key.',
  'mapping.add': 'Add mapping',
  'mapping.select_objects': 'Choose source objects',
  'mapping.add_source_objects': 'Add source objects',
  'mapping.catalog_title': 'Available tables',
  'mapping.selected_source': 'Selected table',
  'mapping.write_to': 'Write to',
  'mapping.write_to_compare': 'Compare with',
  'mapping.none_selected_title': 'No objects selected',
  'mapping.none_selected_desc': 'Check tables on the left. Matching targets are filled in automatically.',
  'mapping.none_selected_desc_compare': 'Check tables on the left to compare. Matching targets are filled in automatically.',
  'mapping.add_target': 'Add target object',
  'mapping.picker_title': 'Choose source objects in bulk',
  'mapping.search_objects': 'Search tables, views, or collections',
  'mapping.include_views': 'Include views',
  'mapping.selected_count': '{selected} selected / {total} total',
  'mapping.select_all': 'Select all ({count})',
  'mapping.select_filtered': 'Select all filtered results ({count})',
  'mapping.selection_fixed_scope': 'This list is fixed when saved; future tables are not added automatically',
  'mapping.object_kind.table': 'Table',
  'mapping.object_kind.view': 'View',
  'mapping.object_kind.collection': 'Collection',
  'mapping.already_added': 'Already added',
  'mapping.rows_count': '{count} rows',
  'mapping.no_objects': 'No matching objects',
  'mapping.show_more': 'Show {count} more ({remaining} remaining)',
  'mapping.add_selected': 'Add {count} objects',
  'mapping.detecting_keys': 'Detecting keys…',
  'mapping.probe_running': 'Detecting keys and fields in the background',
  'mapping.probe_complete': 'Key and field detection complete',
  'mapping.probe_progress': '{completed} / {total}',
  'mapping.open_object_list': 'Open object list',
  'mapping.will_create_named': 'Target does not exist; “{name}” will be created',
  'mapping.no_matching_objects': 'No matching existing objects',
  'mapping.remove': 'Remove',
  'mapping.enabled': 'Enabled',
  'mapping.source': 'Source object',
  'mapping.target': 'Target object',
  'mapping.target_mode': 'If the target is missing',
  'mapping.key_columns': 'Identify the same row by',
  'mapping.fields': 'Fields',
  'mapping.status': 'Status',
  'mapping.create_or_reuse': 'Create automatically; validate and reuse if present',
  'mapping.existing_only': 'Write only to an existing target',
  'mapping.edit_exceptions': 'Edit exception',
  'mapping.collapse_exceptions': 'Collapse',
  'mapping.exceptions_caption': 'Exceptions for {source}',
  'mapping.fields_count': '{count} fields',
  'mapping.fields_pending': 'Automatic same-name fields',
  'mapping.fields_automatic': 'Automatic same-name fields',
  'mapping.fields_automatic_help': 'No per-column setup is needed unless a field is renamed or transformed.',
  'mapping.fields_required': 'Confirm synchronized fields',
  'mapping.fields_cdc_help': 'Continuous sync needs explicit target fields so removed source fields do not leave stale target values.',
  'mapping.ready': 'Configured',
  'mapping.needs_attention': 'Needs attention',
  'mapping.target_hint.exists': 'This table already exists on the target',
  'mapping.target_hint.create': 'This table is not on the target yet; it will be created during sync',
  'mapping.target_hint.missing': 'This table is not on the target, and this task is not allowed to create it',
  'mapping.target_hint.pending': 'Checking whether this table already exists on the target',
  'mapping.key_placeholder': 'Leave empty to auto-match by source primary key',
  'mapping.key_detected': 'Detected from source metadata; edit if needed',
  'mapping.key_when_needed': 'Upsert into an existing target needs a source physical primary key; initial auto-create does not. CDC still needs a stable key.',
  'mapping.source_placeholder': 'Search or choose a source object',
  'mapping.target_placeholder': 'Search an existing target or enter a new name',
  'mapping.query_result_source': 'Query result (single mapping)',
  'mapping.target_state.exists': 'This table already exists on the target',
  'mapping.target_state.create': 'This table is not on the target yet; it will be created during sync',
  'mapping.target_state.missing': 'This table is not on the target, and this task is not allowed to create it',
  'mapping.target_state.pending': 'Checking whether this table already exists on the target',
  'mapping.confirming': 'Confirming',
  'mapping.endpoints_required_title': 'Choose source and target first',
  'mapping.endpoints_required_desc': 'After endpoints are selected, source objects and target matches load here.',
  'mapping.loading_title': 'Loading syncable objects',
  'mapping.loading_desc': 'Reading source and target metadata. This should only take a moment.',
  'mapping.metadata_error_title': 'Objects could not be loaded',
  'mapping.metadata_error_desc': 'Reload the objects. If it still fails, check the endpoints and read permissions.',
  'mapping.no_source_objects_title': 'No syncable source objects',
  'mapping.no_source_objects_desc': 'Check the selected database, schema, and object read permissions.',
  'mapping.retry_objects': 'Reload objects',
  'mapping.refresh_objects': 'Refresh object list',
  'mapping.empty_title': 'No sync objects selected',
  'mapping.empty_desc': 'Choose source objects first. The same picker handles one table, many tables, or all current search results.',
  'field_mapping.title': 'Field mappings',
  'field_mapping.close': 'Collapse',
  'field_mapping.auto_match': 'Match same names',
  'field_mapping.add': 'Add field',
  'field_mapping.empty_title': 'No field mappings yet',
  'field_mapping.empty_desc': 'Load both sides and match by name, or add a row and enter a transform.',
  'field_mapping.source': 'Source field',
  'field_mapping.target': 'Target field',
  'field_mapping.transform': 'Transform',
  'field_mapping.transform_placeholder': 'Blank writes the value directly',
  'field_mapping.transform_identity': 'Identity',
  'field_mapping.transform_argument': 'Argument JSON (optional)',
  'field_mapping.type': 'Type',
  'field_mapping.select_field': 'Choose a field',
  'field_mapping.remove': 'Remove',
  'delivery.title': 'Configure target writes',
  'delivery.help': 'Choose how the target is written and how failed rows are handled. Defaults fit most tasks; risky and specialist options appear only when applicable.',
  'delivery.write_mode': 'Write mode',
  'delivery.write.none': 'Read only',
  'delivery.write.append': 'Append',
  'delivery.write.append_desc': 'Each run inserts new rows. Re-running may create duplicates, so automatic retries are disabled.',
  'delivery.write.upsert': 'Insert or update',
  'delivery.write.upsert_unavailable': 'Insert or update (not supported by this target)',
  'delivery.write.upsert_desc': 'Use a primary or unique key to identify a row: insert when missing and update when present.',
  'delivery.write.overwrite': 'Overwrite',
  'delivery.write.overwrite_unavailable': 'Overwrite (not yet supported for jobs)',
  'delivery.write.overwrite_desc': 'Atomic replacement is not available, so preflight blocks overwrite jobs. Use insert or update instead.',
  'delivery.read_only_title': 'This is a read-only comparison',
  'delivery.read_only_note': 'The task only reads both sides; it never writes to or deletes target data, so there is no write mode, failed-row handling, or schedule. To close structure gaps, use “Generate repair SQL” in the compare result, or create a structure sync task in the data sync workbench.',
  'delivery.content_mode': 'Sync content',
  'delivery.content.schema': 'Schema only',
  'delivery.content.data': 'Data only',
  'delivery.content.both': 'Schema and data',
  'delivery.schema_only_note': 'This task applies schema changes only (for example, adding missing columns); it does not copy table rows.',
  'delivery.error_policy': 'Failed-row handling',
  'delivery.error.stop': 'Stop on error',
  'delivery.error.stop_desc': 'Stop as soon as any row fails to write. Use this when data completeness is the priority.',
  'delivery.error.skip': 'Skip bad rows',
  'delivery.error.skip_desc': 'Record the failure and continue with later rows without storing the complete failed row.',
  'delivery.error.quarantine': 'Quarantine and retry later',
  'delivery.error.quarantine_desc': 'Store the complete failed row in the local task database. It may contain sensitive data and can be retried from the error-row list.',
  'delivery.batch_size': 'Batch size',
  'delivery.commit_every': 'Commit interval (rows)',
  'delivery.commit_every_note': 'The current engine commits by batch size, so this value follows batch size.',
  'delivery.retry_limit': 'Retry limit',
  'delivery.retry_backoff': 'Retry backoff (ms)',
  'delivery.row_isolation_note': 'This configuration must stop on error. Row-level skip is available only for existing relational targets without auto-create, schema changes, delete propagation, or overwrite.',
  'delivery.append_retry_note': 'Append writes may be partially committed. Automatic retries stay at zero to prevent duplicates.',
  'delivery.recovery_policy': 'Run recovery',
  'delivery.recovery.never': 'Disable recovery',
  'delivery.recovery.manual': 'Recover manually',
  'delivery.recovery.auto': 'Recover automatically',
  'delivery.append_recovery_note': 'Append may already have committed batches, so recovery stays disabled to prevent replaying committed data.',
  'delivery.append_only_target_note': 'This time-series target supports append/INSERT-only delivery; updates and deletes are not synchronized.',
  'delivery.propagate_deletes': 'Propagate source deletes',
  'delivery.delete_policy_title': 'Target deletion policy',
  'delivery.delete_risk_badge': 'High risk',
  'delivery.delete.snapshot_label': 'Delete target rows missing from the source',
  'delivery.delete.snapshot_desc': 'A full reconcile compares each table by key and deletes target rows that no longer exist in the source.',
  'delivery.delete.cdc_label': 'Apply source delete events',
  'delivery.delete.cdc_desc': 'When CDC receives a delete event, it deletes the matching target row by key.',
  'delivery.delete_risk_note': 'Target deletes cannot be undone. Confirm the target is not shared and review the preflight scope before running.',
  'delivery.advanced': 'Advanced settings',
  'delivery.advanced_help': 'Performance, retries, and schema migration',
  'delivery.performance_title': 'Performance and retries',
  'delivery.performance_help': 'The defaults fit most tasks. Adjust only when you understand target load and retry idempotency.',
  'delivery.structure_title': 'Target schema',
  'delivery.structure_help': 'One-time migrations, schema-sync tasks and reconcile (diff sync) tasks can add missing target columns; existing columns are never modified or deleted, and no tables are created automatically.',
  'delivery.auto_add_columns': 'Add missing target columns',
  'delivery.auto_add_columns_desc': 'Only adds columns missing from the target; existing columns are not changed or removed. DDL may briefly lock the target table.',
  'delivery.create_indexes': 'Copy table dependents',
  'delivery.create_indexes_desc': 'When auto-creating the target table, copy secondary indexes, owned sequences, triggers, and column comments. Standalone sequences, functions, and views are not migrated with the table.',
  'trigger.title': 'Configure run settings',
  'trigger.help': 'Choose manual, scheduled, or continuous execution, then configure snapshot, watermark, or CDC incrementality when needed.',
  'trigger.mode': 'Trigger',
  'trigger.manual': 'Manual',
  'trigger.once': 'At a specified time',
  'trigger.interval': 'Fixed interval',
  'trigger.interval_seconds': 'Interval (seconds)',
  'trigger.cron': 'Cron schedule',
  'trigger.continuous': 'Continuous',
  'trigger.run_at': 'Run at',
  'trigger.timezone': 'Timezone',
  'trigger.cron_expression': 'Cron expression',
  'trigger.cron_expression_hint':
    'Five fields: minute hour day month weekday, e.g. 0 3 * * * (daily at 03:00). Seconds are not supported.',
  'trigger.overlap': 'When runs overlap',
  'trigger.overlap.skip': 'Skip this run',
  'trigger.overlap.queue': 'Queue this run',
  'incremental.mode': 'Incremental policy',
  'incremental.snapshot': 'Full snapshot',
  'incremental.watermark': 'Watermark',
  'incremental.cdc': 'CDC log',
  'incremental.watermark_column': 'Watermark column',
  'incremental.tie_breaker': 'Tie-breaker column',
  'incremental.overlap_window': 'Overlap window (ms)',
  'incremental.watermark_delivery_note': 'Watermark jobs do not yet support append semantics. InitialValue, overlap windows, and independent commit intervals are not wired to the engine and therefore have no editable controls.',
  'incremental.watermark_mixed_note': 'This task has per-object watermark differences. The first is shown; editing either field unifies all object mappings.',
  'incremental.initial_snapshot': 'Run a full snapshot before the first stream',
  'incremental.cdc_adapter': 'CDC adapter',
  'incremental.select_cdc_adapter': 'Selected automatically from source type',
  'incremental.cdc_probe_ready': 'The automatically selected CDC adapter is ready for this connection, permissions, and topology.',
  'incremental.cdc_probe_unready': 'The automatically selected CDC adapter is not ready.',
  'incremental.start_position': 'Start position',
  'incremental.position.latest': 'Latest position',
  'incremental.position.earliest': 'Earliest position',
  'incremental.position.checkpoint': 'Last checkpoint',
  'incremental.cdc_safety_title': 'CDC start-position boundary',
  'incremental.cdc_safety_note': 'The current guarantee is at-least-once consumption after a newly created latest barrier, or continuation from this task\'s existing checkpoint.',
  'incremental.cdc_snapshot_gap_warning': 'A separate snapshot followed by latest leaves a change window and may miss changes in that window. Seamless handoff is not guaranteed.',
  'incremental.cdc_checkpoint_unavailable': 'This task has no usable checkpoint, so checkpoint start is unavailable.',
  'preflight.title': 'Preflight',
  'preflight.stale': 'Configuration changed; run preflight again',
  'preflight.not_run': 'Preflight has not run',
  'preflight.running': 'Checking endpoints, mappings, and execution policy',
  'preflight.blocked': '{count} blockers',
  'preflight.warning': '{count} warnings',
  'preflight.passed': 'Preflight passed',
  'preflight.empty': 'Complete the configuration and run preflight. Issues link back to their stage.',
  'preflight.open_issue': 'Locate',
  'preflight.current_revision': 'Based on task revision {revision}',
  'preflight.approval_required': 'Production write approval required',
  'preflight.approval_not_required': 'No production write approval required',
  'preflight.approval_fail_closed': 'Save-to-production and run stay disabled until countdown confirmation grants a one-time token.',
  'preflight.approval_granted': 'One-time production authorization granted',
  'preflight.approval_begin_countdown': 'Begin server 10-second confirmation',
  'preflight.approval_beginning': 'Starting server confirmation',
  'preflight.approval_countdown': 'Wait {seconds} seconds',
  'preflight.approval_confirm': 'Confirm production write and grant token',
  'preflight.approving': 'Requesting authorization',
  'preflight.approval_expires': 'The token is memory-only, expires at {expiresAt}, and is invalidated after save or run.',
  'preflight.severity.blocker': 'Blocker',
  'preflight.severity.warning': 'Warning',
  'preflight.severity.info': 'Info',
  'preflight.index_remediation.title': 'Unmigrated indexes ({count})',
  'preflight.index_remediation.columns': 'Columns: {columns}',
  'preflight.index_remediation.copy': 'Copy remediation DDL',
  'preflight.index_remediation.copy_failed': 'Copy failed. Copy the DDL manually from the list below.',
  'runs.title': 'Run history',
  'runs.subtitle': 'Review each run’s status and results. Active stages and events update automatically.',
  'runs.subtitle_compare': 'Review each comparison’s status and results. Active stages and events update automatically.',
  'runs.empty_title': 'No runs yet',
  'runs.empty_desc': 'After a task runs, writes, failures, and sync progress appear here.',
  'runs.empty_desc_compare': 'After a comparison runs, the results appear here.',
  'runs.id': 'Run ID',
  'runs.task': 'Task',
  'runs.status': 'Status',
  'runs.started_at': 'Started',
  'runs.rows_written': 'Rows written',
  'runs.rows_failed': 'Error rows',
  'runs.checkpoint': 'Sync progress',
  'runs.view_errors': 'View error rows',
  'runs.view_details': 'View run details',
  'runs.back_to_list': 'Back to run history',
  'runs.actions': 'Actions',
  'runs.cancel': 'Cancel',
  'runs.resume': 'Resume',
  'runs.retry': 'Retry run',
  'runs.delete': 'Delete record',
  'runs.clear_terminal': 'Clear completed records',
  'runs.pagination': 'Run history pagination',
  'runs.page': 'Page {page}',
  'runs.page_size': 'Per page',
  'runs.total': '{total} total',
  'runs.previous_page': 'Previous page',
  'runs.next_page': 'Next page',
  'runs.delete_confirm': 'Delete this run record and its error rows and event details? Sync progress is kept.',
  'runs.clear_terminal_confirm': 'Clear all completed run records and their error rows and event details? Sync progress is kept.',
  'runs.delete_confirm_title': 'Delete run record',
  'runs.clear_terminal_confirm_title': 'Clear completed records',
  'events.title': 'Event timeline',
  'events.title_secondary': 'Run process',
  'events.select_run': 'Select a run to view its events.',
  'events.empty': 'This run has no persisted events.',
  'errors.title': 'Error rows',
  'errors.empty_title': 'No quarantined rows',
  'errors.empty_desc': 'Choose a failed run to inspect, retry, or export bad rows.',
  'errors.task_failure_title': 'This run failed before row processing',
  'errors.task_failure_desc': 'No retryable error rows were created. Correct the task configuration before running it again.',
  'errors.source': 'Source object',
  'errors.reason': 'Reason',
  'errors.payload': 'Payload preview',
  'errors.retryable': 'Retryable',
  'errors.retry': 'Retry row',
  'errors.retry_unavailable': 'The backend does not expose an error-row retry API, so this action stays disabled.',
  'errors.discard': 'Discard',
  'errors.discarded': 'Discarded',
  'compare.title': 'Compare result',
  'compare.empty': 'The selected run has no compare result to display.',
  'compare.table': 'Table',
  'compare.inserts': 'Inserts',
  'compare.updates': 'Updates',
  'compare.deletes': 'Deletes',
  'compare.same': 'Same',
  'compare.same_rows': '{count} rows',
  'compare.schema_diff': 'Schema diff',
  'compare.status_same': 'Identical',
  'compare.status_diff': 'Different',
  'compare.status_blocked': 'Not compared',
  'compare.source': 'Source',
  'compare.target': 'Target',
  'compare.missing_columns': 'Missing in target',
  'compare.schema_warning':
    'The two tables differ structurally in {count} place(s). This was a data-only compare, so the details are not expanded — switch to structure only or data and structure to see them, and align the target before syncing.',
  'compare.diff_kind.missing_in_target': 'Missing in target',
  'compare.diff_kind.extra_in_target': 'Extra in target',
  'compare.diff_kind.type': 'Type differs',
  'compare.diff_kind.nullable': 'Nullability differs',
  'compare.actions.repair_sql': 'Generate repair SQL',
  'compare.actions.ai_sql': 'Analyze diffs with AI',
  'compare.actions.sync_diff': 'Sync differences',
  'compare.repair_sql_tab': 'Compare repair SQL',
  'compare.sync_task_name': '{name} · Diff sync',
  'checkpoint.title': 'Sync progress',
  'checkpoint.empty': 'The selected run has no saved sync progress.',
  'checkpoint.kind': 'Kind',
  'checkpoint.phase': 'Phase',
  'checkpoint.updated_at': 'Updated',
  'checkpoint.cursor': 'Position',
  'checkpoint.reset': 'Reset sync progress',
  'checkpoint.reset_confirm_title': 'Reset sync progress',
  'checkpoint.reset_warning': 'Reset removes the resume position. Continuous incremental sync can then start only from new changes after the reset.',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.refresh': 'Refresh',
  'common.dismiss': 'Dismiss',
  'common.details': 'View details',
  'common.retry': 'Retry',
  'common.cancel': 'Cancel',
  ...dataSyncScheduleTextsEnUS, ...dataSyncRunEventTextsEnUS,
  ...dataSyncValidationTextsEnUS,
  'cdc.title': 'CDC source status',
  'cdc.subtitle': 'Status comes from adapter probes and task checkpoints. Lag is never inferred when the backend does not report it.',
  'cdc.empty_title': 'No CDC sources to monitor',
  'cdc.empty_desc': 'Create a CDC task and probe its permissions to see source health here.',
  'cdc.lag_unknown': 'Lag not reported',
  'cdc.status.ready': 'Adapter ready',
  'cdc.status.probing': 'Probing',
  'cdc.status.lagging': 'Lagging',
  'cdc.status.offline': 'Source offline',
  'cdc.status.unsupported': 'Unsupported',
  'cdc.status.unknown': 'Unknown',
  'status.queued': 'Queued',
  'status.running': 'Running',
  'status.cancelling': 'Cancelling',
  'status.preflighting': 'Preflighting',
  'status.snapshotting': 'Snapshotting',
  'status.catching_up': 'Catching up',
  'status.streaming': 'Streaming',
  'status.paused': 'Paused',
  'status.succeeded': 'Succeeded',
  'status.partial': 'Partial',
  'status.failed': 'Failed',
  'status.canceled': 'Canceled',
  'status.cancelled': 'Cancelled',
  'status.interrupted': 'Interrupted',
};
