#!/usr/bin/env python3

import importlib.util
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SCRIPT = ROOT / "tools" / "verify-driver-agent-fingerprints.py"

SPHINX_REVISION = "src-" + "a1b2c3d4e5f60718"
SQLSERVER_REVISION = "src-" + "0f9e8d7c6b5a4321"
STALE_REVISION = "src-" + "0000000000000001"


def load_module():
    spec = importlib.util.spec_from_file_location(
        "verify_driver_agent_fingerprints", SCRIPT
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def write_agent(path: Path, revision: str):
    marker = ("agent-revision:" + revision).encode("ascii")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(b"GO binary payload\x00" + marker + b"\x00payload-end")


def write_revision_map(path: Path, entries: dict):
    lines = [
        "// Code generated by tools/generate-driver-agent-revisions.sh; DO NOT EDIT.",
        "",
        "package db",
        "",
        "func init() {",
        "\toptionalDriverAgentRevisions = map[string]string{",
    ]
    for driver, revision in sorted(entries.items()):
        lines.append(f'\t\t"{driver}":        "{revision}",')
    lines.append("\t}")
    lines.append("}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def run_tool(*args: str):
    return subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        cwd=ROOT,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )


class VerifyDriverAgentFingerprintsBinariesTest(unittest.TestCase):
    def test_passes_when_embedded_revisions_match_map(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            tmpdir = Path(tmp)
            assets_dir = tmpdir / "release-assets"
            write_agent(assets_dir / "drivers" / "Windows" / "sphinx-driver-agent-windows-amd64.exe", SPHINX_REVISION)

            # zip 鎴愬憳閲岀殑 agent 鍚屾牱瑕佽鎵埌锛堟墦鍖呭悗鐨勫彂甯冨舰鎬侊級
            import zipfile
            zip_path = assets_dir / "sqlserver-driver-agent-linux-amd64.zip"
            with zipfile.ZipFile(zip_path, "w") as archive:
                archive.writestr("Linux/sqlserver-driver-agent-linux-amd64", SQLSERVER_REVISION.encode("ascii"))

            maps = {
                "windows/amd64": {"sphinx": SPHINX_REVISION},
                "linux/amd64": {"sqlserver": SQLSERVER_REVISION},
            }
            checked, failures, skipped = module.verify_binaries(assets_dir, maps)
            self.assertEqual(2, checked)
            self.assertEqual([], failures)

    def test_fails_on_stale_revision(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            assets_dir = Path(tmp) / "release-assets"
            write_agent(
                assets_dir / "drivers" / "Windows" / "sphinx-driver-agent-windows-amd64.exe",
                STALE_REVISION,
            )
            checked, failures, skipped = module.verify_binaries(
                assets_dir, {"windows/amd64": {"sphinx": SPHINX_REVISION}}
            )
            self.assertEqual(1, checked)
            self.assertEqual(1, len(failures))
            self.assertIn(STALE_REVISION, failures[0])
            self.assertIn(SPHINX_REVISION, failures[0])

    def test_fails_when_binary_has_no_or_ambiguous_fingerprint(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            assets_dir = Path(tmp) / "release-assets"
            empty = assets_dir / "drivers" / "Windows" / "sphinx-driver-agent-windows-amd64.exe"
            empty.parent.mkdir(parents=True, exist_ok=True)
            empty.write_bytes(b"no fingerprint here")
            ambiguous = assets_dir / "drivers" / "Windows" / "duckdb-driver-agent-windows-amd64.exe"
            ambiguous.write_bytes(
                b"x" + ("src-" + "a" * 16).encode("ascii") + b"y" + ("src-" + "b" * 16).encode("ascii")
            )
            checked, failures, skipped = module.verify_binaries(
                assets_dir,
                {
                    "windows/amd64": {"sphinx": SPHINX_REVISION, "duckdb": SPHINX_REVISION},
                },
            )
            # duckdb 完成了比对（期望值不在内嵌集合）；sphinx 无指纹未计入
            self.assertEqual(1, checked)
            self.assertEqual(2, len(failures))

    def test_passes_when_expected_revision_among_multiple_embedded(self):
        # agent 内嵌整张 revision map：只要包含本驱动的 canonical 指纹即通过
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            assets_dir = Path(tmp) / "release-assets"
            exe = assets_dir / "drivers" / "Windows" / "duckdb-driver-agent-windows-amd64.exe"
            exe.parent.mkdir(parents=True, exist_ok=True)
            exe.write_bytes(
                b"map:"
                + ("src-" + "a" * 16).encode("ascii")
                + b","
                + SPHINX_REVISION.encode("ascii")
                + b","
                + ("src-" + "b" * 16).encode("ascii")
            )
            checked, failures, skipped = module.verify_binaries(
                assets_dir, {"windows/amd64": {"duckdb": SPHINX_REVISION}}
            )
            self.assertEqual(1, checked)
            self.assertEqual([], failures)

    def test_mongodb_v1_variant_requires_fingerprint_but_skips_value(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            assets_dir = Path(tmp) / "release-assets"
            write_agent(
                assets_dir / "drivers" / "Windows" / "mongodb-driver-agent-v1-windows-amd64.exe",
                STALE_REVISION,
            )
            write_agent(
                assets_dir / "drivers" / "Windows" / "mongodb-driver-agent-v2-windows-amd64.exe",
                SQLSERVER_REVISION,
            )
            checked, failures, skipped = module.verify_binaries(
                assets_dir, {"windows/amd64": {"mongodb": SQLSERVER_REVISION}}
            )
            self.assertEqual(2, checked)
            self.assertEqual([], failures)

    def test_reports_platform_missing_from_assets_dir(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            assets_dir = Path(tmp) / "release-assets"
            assets_dir.mkdir(parents=True, exist_ok=True)
            checked, failures, skipped = module.verify_binaries(
                assets_dir, {"windows/amd64": {"sphinx": SPHINX_REVISION}}
            )
            self.assertEqual(0, checked)
            self.assertEqual(1, len(failures))
            self.assertIn("windows/amd64", failures[0])

    def test_dynamic_probe_platform_uses_prober_result(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            assets_dir = Path(tmp) / "release-assets"
            write_agent(assets_dir / "Linux" / "sphinx-driver-agent-linux-amd64", STALE_REVISION)

            probes = []
            records = {}

            def fake_prober(payload: bytes) -> str:
                probes.append(payload)
                return records.setdefault("value", SPHINX_REVISION)

            checked, failures, skipped = module.verify_binaries(
                assets_dir,
                {"linux/amd64": {"sphinx": SPHINX_REVISION}},
                dynamic_probe_platforms=("linux/amd64",),
                prober=fake_prober,
            )
            self.assertEqual(1, len(probes))
            self.assertEqual(1, checked)
            self.assertEqual([], failures)
            self.assertEqual([], skipped)

            # 指纹与 map 不一致时同样要失败
            records["value"] = STALE_REVISION
            checked, failures, skipped = module.verify_binaries(
                assets_dir,
                {"linux/amd64": {"sphinx": SPHINX_REVISION}},
                dynamic_probe_platforms=("linux/amd64",),
                prober=fake_prober,
            )
            self.assertEqual(1, checked)
            self.assertEqual(1, len(failures))
            self.assertIn(STALE_REVISION, failures[0])

    def test_dynamic_probe_error_is_reported_as_failure(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            assets_dir = Path(tmp) / "release-assets"
            write_agent(assets_dir / "Linux" / "sphinx-driver-agent-linux-amd64", STALE_REVISION)

            def broken_prober(payload: bytes) -> str:
                raise RuntimeError("agent 无法启动")

            checked, failures, skipped = module.verify_binaries(
                assets_dir,
                {"linux/amd64": {"sphinx": SPHINX_REVISION}},
                dynamic_probe_platforms=("linux/amd64",),
                prober=broken_prober,
            )
            self.assertEqual(0, checked)
            self.assertEqual(1, len(failures))
            self.assertIn("agent 无法启动", failures[0])

    def test_skip_platform_is_reported_but_not_failed(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            assets_dir = Path(tmp) / "release-assets"
            write_agent(assets_dir / "Linux" / "sphinx-driver-agent-linux-arm64", STALE_REVISION)

            checked, failures, skipped = module.verify_binaries(
                assets_dir,
                {"linux/arm64": {"sphinx": SPHINX_REVISION}},
                skip_platforms=("linux/arm64",),
            )
            self.assertEqual(0, checked)
            self.assertEqual([], failures)
            self.assertEqual(1, len(skipped))
            self.assertIn("linux/arm64", skipped[0])

    def test_doris_is_canonical_and_diros_is_a_legacy_filename_alias(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            assets_dir = Path(tmp) / "release-assets"
            write_agent(assets_dir / "MacOS" / "doris-driver-agent-darwin-amd64", SPHINX_REVISION)
            checked, failures, skipped = module.verify_binaries(
                assets_dir, {"darwin/amd64": {"doris": SPHINX_REVISION}}
            )
            self.assertEqual(1, checked)
            self.assertEqual([], failures)

            # 已发布的历史资产仍使用 diros 文件名，也必须匹配 Doris canonical key。
            write_agent(assets_dir / "MacOS" / "diros-driver-agent-darwin-amd64", SPHINX_REVISION)
            checked, failures, skipped = module.verify_binaries(
                assets_dir, {"darwin/amd64": {"doris": SPHINX_REVISION}}
            )
            self.assertEqual(2, checked)
            self.assertEqual([], failures)

    def test_parse_revision_maps_normalizes_legacy_diros_key_to_doris(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            revision_map = Path(tmp) / "driver_agent_revisions_gen.go"
            write_revision_map(revision_map, {"diros": SPHINX_REVISION})

            maps = module.parse_revision_maps([f"darwin/amd64={revision_map}"])

            self.assertEqual({"doris": SPHINX_REVISION}, maps["darwin/amd64"])

    def test_parse_revision_maps_rejects_conflicting_doris_aliases(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            revision_map = Path(tmp) / "driver_agent_revisions_gen.go"
            write_revision_map(
                revision_map,
                {"doris": SPHINX_REVISION, "diros": STALE_REVISION},
            )

            with self.assertRaisesRegex(SystemExit, "conflicting aliases for doris"):
                module.parse_revision_maps([f"darwin/amd64={revision_map}"])


class VerifyDriverAgentFingerprintsPublishedTest(unittest.TestCase):
    def build_manifest(self, entries):
        assets = {}
        for name, payload in entries.items():
            assets[name] = payload
        return {"schemaVersion": 1, "generatedFrom": "0" * 40, "assets": assets}

    def test_passes_when_published_revisions_match_map(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            tmpdir = Path(tmp)
            manifest = tmpdir / "manifest.json"
            manifest.write_text(
                json.dumps(self.build_manifest(
                    {
                        "sphinx-driver-agent-windows-amd64": {
                            "driver": "sphinx",
                            "driverType": "sphinx",
                            "platform": "windows/amd64",
                            "revision": SPHINX_REVISION,
                        }
                    }
                )),
                encoding="utf-8",
            )
            checked, failures = module.verify_published(
                manifest, {"windows/amd64": {"sphinx": SPHINX_REVISION}}
            )
            self.assertEqual(1, checked)
            self.assertEqual([], failures)

    def test_legacy_diros_manifest_entry_matches_doris_revision_map(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            manifest = Path(tmp) / "manifest.json"
            manifest.write_text(
                json.dumps(self.build_manifest(
                    {
                        "diros-driver-agent-darwin-amd64": {
                            "driver": "diros",
                            "driverType": "diros",
                            "platform": "darwin/amd64",
                            "revision": SPHINX_REVISION,
                        }
                    }
                )),
                encoding="utf-8",
            )

            checked, failures = module.verify_published(
                manifest, {"darwin/amd64": {"doris": SPHINX_REVISION}}
            )

            self.assertEqual(1, checked)
            self.assertEqual([], failures)

    def test_fails_when_published_revision_is_stale(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            tmpdir = Path(tmp)
            manifest = tmpdir / "manifest.json"
            manifest.write_text(
                json.dumps(self.build_manifest(
                    {
                        "sphinx-driver-agent-windows-amd64": {
                            "driver": "sphinx",
                            "driverType": "sphinx",
                            "platform": "windows/amd64",
                            "revision": STALE_REVISION,
                        }
                    }
                )),
                encoding="utf-8",
            )
            checked, failures = module.verify_published(
                manifest, {"windows/amd64": {"sphinx": SPHINX_REVISION}}
            )
            self.assertEqual(1, checked)
            self.assertEqual(1, len(failures))
            self.assertIn(SPHINX_REVISION, failures[0])

    def test_fails_when_manifest_is_missing_driver_asset(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            tmpdir = Path(tmp)
            manifest = tmpdir / "manifest.json"
            manifest.write_text(
                json.dumps(self.build_manifest({})),
                encoding="utf-8",
            )
            checked, failures = module.verify_published(
                manifest, {"windows/amd64": {"sphinx": SPHINX_REVISION}}
            )
            self.assertEqual(0, checked)
            self.assertEqual(1, len(failures))
            self.assertIn("缺少该驱动资产", failures[0])

    def test_skips_duckdb_on_windows_arm64(self):
        module = load_module()
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            manifest = Path(tmp) / "manifest.json"
            manifest.write_text(
                json.dumps(self.build_manifest({})),
                encoding="utf-8",
            )

            checked, failures = module.verify_published(
                manifest,
                {"windows/arm64": {"duckdb": SPHINX_REVISION}},
            )

            self.assertEqual(0, checked)
            self.assertEqual([], failures)

    def test_cli_reports_mismatch_with_nonzero_exit(self):
        with tempfile.TemporaryDirectory(prefix="gonavi-fingerprint-test-") as tmp:
            tmpdir = Path(tmp)
            manifest = tmpdir / "manifest.json"
            manifest.write_text(
                json.dumps(self.build_manifest(
                    {
                        "sphinx-driver-agent-windows-amd64": {
                            "driver": "sphinx",
                            "driverType": "sphinx",
                            "platform": "windows/amd64",
                            "revision": STALE_REVISION,
                        }
                    }
                )),
                encoding="utf-8",
            )
            gen_map = tmpdir / "driver_agent_revisions_gen.go"
            write_revision_map(gen_map, {"sphinx": SPHINX_REVISION})

            proc = run_tool(
                "published",
                "--manifest",
                str(manifest),
                "--revision-map",
                f"windows/amd64={gen_map}",
            )
            self.assertNotEqual(0, proc.returncode)
            self.assertIn("MISMATCH", proc.stdout)


if __name__ == "__main__":
    unittest.main()
