// Code generated by tools/generate-driver-agent-revisions.sh; DO NOT EDIT.

package db

func init() {
	optionalDriverAgentRevisions = map[string]string{
		"mariadb":       "src-822403cf32062f85",
		"oceanbase":     "src-d9fa58e1d15020d6",
		"diros":         "src-c5ddd937d84c1bb4",
		"starrocks":     "src-b0c4ac205df1b6c0",
		"sphinx":        "src-cbe751dfd50ceac6",
		"sqlserver":     "src-2d494f4c6b84548a",
		"sqlite":        "src-8dfe96e1455d8b7e",
		"duckdb":        "src-08bc0f1cb754e605",
		"dameng":        "src-ffd9f19f2f9e521c",
		"kingbase":      "src-ba451dd57a5c8453",
		"highgo":        "src-2a387553c4c395ab",
		"vastbase":      "src-29f64cbfdf8d4325",
		"opengauss":     "src-51409fe773acdaa3",
		"gaussdb":       "src-bd53f89daefeb5c3",
		"iris":          "src-0219daeee8340eaa",
		"cache":         "src-ec52cdcb00246b14",
		"mongodb":       "src-34d3ac39e12ee204",
		"tdengine":      "src-c7fd9582e0d2573b",
		"iotdb":         "src-c9c578e13c702bbf",
		"clickhouse":    "src-0a402e134b7233f1",
		"elasticsearch": "src-73969780372effbf",
		"trino":         "src-d2d26c1a10822ccb",
	}
}
