// Code generated by tools/generate-driver-agent-revisions.sh; DO NOT EDIT.

package db

func init() {
	optionalDriverAgentRevisions = map[string]string{
		"mariadb":       "src-818fa6e60ac9e975",
		"oceanbase":     "src-44f39c36b12dc502",
		"diros":         "src-86675dc291548f53",
		"starrocks":     "src-bd1da5d843a29021",
		"sphinx":        "src-ba3d674e7d799889",
		"sqlserver":     "src-5dc3c2a12ff1f4ad",
		"sqlite":        "src-896952ca75adc5c5",
		"duckdb":        "src-256a2c01bc2a3987",
		"dameng":        "src-f16e914225f46dc5",
		"kingbase":      "src-2dcddae3a16ba121",
		"highgo":        "src-1b7089f8bb347c99",
		"vastbase":      "src-7c851a5ba3e75b63",
		"opengauss":     "src-d649d929fa516903",
		"gaussdb":       "src-ee064ab25528ec83",
		"iris":          "src-b0effb8d1fa50c1b",
		"mongodb":       "src-fb5dd802636c31b2",
		"tdengine":      "src-bc0fa736fcb26d35",
		"iotdb":         "src-f6e4e0627a745096",
		"clickhouse":    "src-7ad31ab80797b81a",
		"elasticsearch": "src-3c9b967fc432a877",
		"trino":         "src-9bd8f96175170e24",
	}
}
