// Code generated by tools/generate-driver-agent-revisions.sh; DO NOT EDIT.

package db

func init() {
	optionalDriverAgentRevisions = map[string]string{
		"mariadb":       "src-453bbda0e798c630",
		"oceanbase":     "src-781e82ab0f0d16b3",
		"diros":         "src-5267d6e77d574dca",
		"starrocks":     "src-64c8d5709c817d2f",
		"sphinx":        "src-49b067f33dc4a6c2",
		"sqlserver":     "src-e03b09a949e349d1",
		"sqlite":        "src-fc840ce80a56ec0f",
		"duckdb":        "src-54d0eef604419ec4",
		"dameng":        "src-2bef14bbd9e422e4",
		"kingbase":      "src-1ccfbf6694ce620f",
		"highgo":        "src-e826dd90d87903f3",
		"vastbase":      "src-dd4a53092e3dface",
		"opengauss":     "src-394167cdbd0a868a",
		"gaussdb":       "src-766debbcc1850fce",
		"iris":          "src-f443ccad0a9a1c3f",
		"mongodb":       "src-ebf664aa1ae713eb",
		"tdengine":      "src-d31c6a45a99a1e0e",
		"iotdb":         "src-0cdf32eb1c4d9965",
		"clickhouse":    "src-5e7fd89b6f3d82e9",
		"elasticsearch": "src-ba63c309637a5cc8",
		"trino":         "src-f38f259400f25695",
	}
}
