//go:build gonavi_full_drivers || gonavi_sqlserver_driver

package db

import (
	"context"
	"database/sql"
	"fmt"
	"net"
	"strconv"
	"strings"
	"time"

	"GoNavi-Wails/internal/connection"
	"GoNavi-Wails/internal/logger"
	"GoNavi-Wails/internal/ssh"
	"GoNavi-Wails/internal/utils"

	"github.com/golang-sql/sqlexp"
	_ "github.com/microsoft/go-mssqldb"
)

type SqlServerDB struct {
	conn        *sql.DB
	pingTimeout time.Duration
	forwarder   *ssh.LocalForwarder

	acquireLocalForwarder func(connection.SSHConfig, string, int) (*ssh.LocalForwarder, error)
	openDB                func(string, string) (*sql.DB, error)
	releaseLocalForwarder func(*ssh.LocalForwarder) error
}

func (s *SqlServerDB) acquireForwarder(config connection.SSHConfig, host string, port int) (*ssh.LocalForwarder, error) {
	if s.acquireLocalForwarder != nil {
		return s.acquireLocalForwarder(config, host, port)
	}
	return ssh.AcquireLocalForwarder(config, host, port)
}

func (s *SqlServerDB) openSQLDB(driverName, dsn string) (*sql.DB, error) {
	if s.openDB != nil {
		return s.openDB(driverName, dsn)
	}
	return sql.Open(driverName, dsn)
}

func (s *SqlServerDB) releaseForwarder(forwarder *ssh.LocalForwarder) error {
	if s.releaseLocalForwarder != nil {
		return s.releaseLocalForwarder(forwarder)
	}
	if forwarder == nil {
		return nil
	}
	return forwarder.Release()
}

type sqlServerSessionExecer struct {
	conn *sql.Conn
}

func scanSQLServerRowsWithMessages(ctx context.Context, rows *sql.Rows, retmsg *sqlexp.ReturnMessage) ([]connection.ResultSetData, []string, error) {
	if rows == nil {
		return []connection.ResultSetData{emptySQLServerRowsResultSet()}, nil, nil
	}
	if ctx == nil {
		ctx = context.Background()
	}

	var (
		resultSets  []connection.ResultSetData
		messages    []string
		allMessages []string
	)
	active := true
	for active {
		if err := ctx.Err(); err != nil {
			return resultSets, messages, err
		}
		raw := retmsg.Message(ctx)
		if err := ctx.Err(); err != nil {
			return resultSets, messages, err
		}
		switch msg := raw.(type) {
		case sqlexp.MsgNotice:
			text := strings.TrimSpace(fmt.Sprint(msg.Message))
			if text != "" {
				messages = append(messages, text)
				allMessages = append(allMessages, text)
			}
		case sqlexp.MsgNext:
			data, cols, truncated, err := scanRowsForDialectWithPreview(rows, "", true, RowBudgetFromContext(ctx))
			if err != nil {
				return resultSets, messages, err
			}
			if data == nil {
				data = []map[string]interface{}{}
			}
			if cols == nil {
				cols = []string{}
			}
			resultSets = append(resultSets, connection.ResultSetData{
				Rows:      data,
				Columns:   cols,
				Messages:  append([]string(nil), messages...),
				Truncated: truncated,
			})
			if truncated {
				// 达到行预算：停止读取，剩余结果集与消息不再消费。
				return resultSets, allMessages, nil
			}
			messages = nil
		case sqlexp.MsgRowsAffected:
			resultSets = append(resultSets, connection.ResultSetData{
				Rows:     []map[string]interface{}{{"affectedRows": msg.Count}},
				Columns:  []string{"affectedRows"},
				Messages: append([]string(nil), messages...),
			})
			messages = nil
		case sqlexp.MsgNextResultSet:
			// Only MsgNext proves a row set is ready. Calling Columns at an empty
			// boundary drains later DONE and PRINT tokens in go-mssqldb Rowsq.
			active = rows.NextResultSet()
		case sqlexp.MsgError:
			return resultSets, messages, msg.Error
		default:
			active = false
		}
	}
	if len(messages) > 0 {
		resultSets = append(resultSets, connection.ResultSetData{
			Rows:     []map[string]interface{}{},
			Columns:  []string{},
			Messages: append([]string(nil), messages...),
		})
	}
	if len(resultSets) == 0 {
		resultSets = []connection.ResultSetData{emptySQLServerRowsResultSet()}
	}
	if err := rows.Err(); err != nil {
		return resultSets, allMessages, err
	}
	return resultSets, allMessages, nil
}

func emptySQLServerRowsResultSet() connection.ResultSetData {
	return connection.ResultSetData{
		Rows:    []map[string]interface{}{},
		Columns: []string{},
	}
}

// quoteBracket escapes ] in identifiers for safe use in SQL Server [bracket] notation
func quoteBracket(name string) string {
	return strings.ReplaceAll(name, "]", "]]")
}

// quoteSQLServerChangeIdentifier removes one existing bracket delimiter, then
// escapes the identifier contents exactly once for DML generated by the table
// editor.
func quoteSQLServerChangeIdentifier(name string) string {
	n := name
	trimmed := strings.TrimSpace(name)
	if len(trimmed) >= 2 && trimmed[0] == '[' && trimmed[len(trimmed)-1] == ']' {
		n = strings.ReplaceAll(trimmed[1:len(trimmed)-1], "]]", "]")
	}
	if strings.TrimSpace(n) == "" {
		return "[]"
	}
	return "[" + strings.ReplaceAll(n, "]", "]]") + "]"
}

func (s *SqlServerDB) Connect(config connection.ConnectionConfig) (err error) {
	_ = s.Close()
	defer func() {
		if err != nil {
			_ = s.Close()
		}
	}()

	var dsn string

	if config.UseSSH {
		logger.Infof("SQL Server 使用 SSH 连接：地址=%s:%d 用户=%s", config.Host, config.Port, config.User)

		forwarder, err := s.acquireForwarder(config.SSH, config.Host, config.Port)
		if err != nil {
			return fmt.Errorf("创建 SSH 隧道失败：%w", err)
		}
		s.forwarder = forwarder

		host, portStr, err := net.SplitHostPort(forwarder.LocalAddr)
		if err != nil {
			return fmt.Errorf("解析本地转发地址失败：%w", err)
		}

		port, err := strconv.Atoi(portStr)
		if err != nil {
			return fmt.Errorf("解析本地端口失败：%w", err)
		}

		localConfig := config
		localConfig.Host = host
		localConfig.Port = port
		localConfig.UseSSH = false

		dsn = s.dsnForRemoteHost(localConfig, config.Host)
		logger.Infof("SQL Server 通过本地端口转发连接：%s -> %s:%d", forwarder.LocalAddr, config.Host, config.Port)
	} else {
		dsn = s.getDSN(config)
	}

	db, err := s.openSQLDB("sqlserver", dsn)
	if err != nil {
		return wrapDatabaseConnectionOpenError(err)
	}
	configureSQLConnectionPool(db, "sqlserver")
	s.conn = db
	s.pingTimeout = getConnectTimeout(config)

	verificationStartedAt := time.Now()
	if err := s.Ping(); err != nil {
		_ = db.Close()
		s.conn = nil
		if s.forwarder == nil {
			return wrapDatabaseConnectionVerifyError(err)
		}
		return wrapDatabaseConnectionVerifyErrorWithForwarder(err, s.forwarder, verificationStartedAt)
	}
	return nil
}

func (s *SqlServerDB) Close() error {
	if s.forwarder != nil {
		if err := s.releaseForwarder(s.forwarder); err != nil {
			logger.Warnf("关闭 SQL Server SSH 端口转发失败：%v", err)
		}
		s.forwarder = nil
	}

	if s.conn != nil {
		return s.conn.Close()
	}
	return nil
}

func (s *SqlServerDB) Ping() error {
	if s.conn == nil {
		return fmt.Errorf("连接未打开")
	}
	timeout := s.pingTimeout
	if timeout <= 0 {
		timeout = 5 * time.Second
	}
	ctx, cancel := utils.ContextWithTimeout(timeout)
	defer cancel()
	return s.conn.PingContext(ctx)
}

func (s *SqlServerDB) QueryMulti(query string) ([]connection.ResultSetData, error) {
	results, _, err := s.QueryMultiWithMessages(query)
	return results, err
}

func (s *SqlServerDB) QueryMultiWithMessages(query string) ([]connection.ResultSetData, []string, error) {
	if s.conn == nil {
		return nil, nil, fmt.Errorf("连接未打开")
	}
	ctx := context.Background()
	retmsg := &sqlexp.ReturnMessage{}
	rows, err := s.conn.QueryContext(ctx, query, retmsg)
	if err != nil {
		return nil, nil, err
	}
	defer rows.Close()
	return scanSQLServerRowsWithMessages(ctx, rows, retmsg)
}

func (s *SqlServerDB) QueryMultiContext(ctx context.Context, query string) ([]connection.ResultSetData, error) {
	results, _, err := s.QueryMultiContextWithMessages(ctx, query)
	return results, err
}

func (s *SqlServerDB) QueryMultiContextWithMessages(ctx context.Context, query string) ([]connection.ResultSetData, []string, error) {
	if s.conn == nil {
		return nil, nil, fmt.Errorf("连接未打开")
	}
	retmsg := &sqlexp.ReturnMessage{}
	rows, err := s.conn.QueryContext(ctx, query, retmsg)
	if err != nil {
		return nil, nil, err
	}
	defer rows.Close()
	return scanSQLServerRowsWithMessages(ctx, rows, retmsg)
}

func (s *SqlServerDB) QueryContext(ctx context.Context, query string) ([]map[string]interface{}, []string, error) {
	rows, columns, _, err := s.QueryContextWithMessages(ctx, query)
	return rows, columns, err
}

func (s *SqlServerDB) QueryContextWithMessages(ctx context.Context, query string) ([]map[string]interface{}, []string, []string, error) {
	if s.conn == nil {
		return nil, nil, nil, fmt.Errorf("连接未打开")
	}

	resultSets, messages, err := s.QueryMultiContextWithMessages(ctx, query)
	if err != nil {
		return nil, nil, nil, err
	}
	if len(resultSets) == 0 {
		return []map[string]interface{}{}, []string{}, messages, nil
	}
	first := resultSets[0]
	if first.Rows == nil {
		first.Rows = []map[string]interface{}{}
	}
	if first.Columns == nil {
		first.Columns = []string{}
	}
	return first.Rows, first.Columns, messages, nil
}

func (s *SqlServerDB) Query(query string) ([]map[string]interface{}, []string, error) {
	rows, columns, _, err := s.QueryWithMessages(query)
	return rows, columns, err
}

func (s *SqlServerDB) QueryWithMessages(query string) ([]map[string]interface{}, []string, []string, error) {
	ctx, cancel := sqlServerMetadataQueryContext(s)
	defer cancel()
	return s.QueryContextWithMessages(ctx, query)
}

func (s *SqlServerDB) ExecContext(ctx context.Context, query string) (int64, error) {
	if s.conn == nil {
		return 0, fmt.Errorf("连接未打开")
	}
	res, err := s.conn.ExecContext(ctx, query)
	if err != nil {
		return 0, err
	}
	return sqlServerRowsAffected(query, res)
}

func (s *SqlServerDB) ExecBatchContext(ctx context.Context, query string) (int64, error) {
	if s.conn == nil {
		return 0, fmt.Errorf("连接未打开")
	}
	res, err := s.conn.ExecContext(ctx, query)
	if err != nil {
		return 0, err
	}
	return sqlServerRowsAffected(query, res)
}

func (s *SqlServerDB) OpenSessionExecer(ctx context.Context) (StatementExecer, error) {
	if s.conn == nil {
		return nil, fmt.Errorf("连接未打开")
	}
	conn, err := s.conn.Conn(ctx)
	if err != nil {
		return nil, err
	}
	return &sqlServerSessionExecer{conn: conn}, nil
}

func (s *SqlServerDB) Exec(query string) (int64, error) {
	if s.conn == nil {
		return 0, fmt.Errorf("连接未打开")
	}
	res, err := s.conn.Exec(query)
	if err != nil {
		return 0, err
	}
	return sqlServerRowsAffected(query, res)
}
